[2021-12-10 08:51:13,657] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: scraping_daft_cork.persist_data scheduled__2021-12-09T01:00:00+00:00 [queued]>
[2021-12-10 08:51:13,716] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: scraping_daft_cork.persist_data scheduled__2021-12-09T01:00:00+00:00 [queued]>
[2021-12-10 08:51:13,717] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-10 08:51:13,718] {taskinstance.py:1242} INFO - Starting attempt 1 of 3
[2021-12-10 08:51:13,721] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-10 08:51:13,775] {taskinstance.py:1262} INFO - Executing <Task(SparkSubmitOperator): persist_data> on 2021-12-09 01:00:00+00:00
[2021-12-10 08:51:13,798] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'scraping_daft_cork', 'persist_data', 'scheduled__2021-12-09T01:00:00+00:00', '--job-id', '992', '--raw', '--subdir', 'DAGS_FOLDER/scraping_daft_cork.py', '--cfg-path', '/tmp/tmpa5q1zds5', '--error-file', '/tmp/tmp9zoq17ct']
[2021-12-10 08:51:13,802] {standard_task_runner.py:77} INFO - Job 992: Subtask persist_data
[2021-12-10 08:51:13,789] {standard_task_runner.py:52} INFO - Started process 30703 to run task
[2021-12-10 08:51:13,993] {logging_mixin.py:109} INFO - Running <TaskInstance: scraping_daft_cork.persist_data scheduled__2021-12-09T01:00:00+00:00 [running]> on host 041e6f8654c3
[2021-12-10 08:51:14,338] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=clemoni
AIRFLOW_CTX_DAG_ID=scraping_daft_cork
AIRFLOW_CTX_TASK_ID=persist_data
AIRFLOW_CTX_EXECUTION_DATE=2021-12-09T01:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-09T01:00:00+00:00
[2021-12-10 08:51:14,378] {base.py:79} INFO - Using connection to: id: spark_default. Host: spark://spark:7077, Port: None, Schema: , Login: ***, Password: ***, extra: {}
[2021-12-10 08:51:14,383] {spark_submit.py:362} INFO - Spark-Submit cmd: spark-submit --master spark://spark:7077 --conf spark.master=spark://spark:7077 --name persist data --verbose /opt/***/jobs/persist_db.py cork
[2021-12-10 08:51:20,008] {spark_submit.py:523} INFO - Using properties file: null
[2021-12-10 08:51:20,312] {spark_submit.py:523} INFO - WARNING: An illegal reflective access operation has occurred
[2021-12-10 08:51:20,319] {spark_submit.py:523} INFO - WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/home/***/.local/lib/python3.6/site-packages/pyspark/jars/spark-unsafe_2.12-3.2.0.jar) to constructor java.nio.DirectByteBuffer(long,int)
[2021-12-10 08:51:20,321] {spark_submit.py:523} INFO - WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
[2021-12-10 08:51:20,324] {spark_submit.py:523} INFO - WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[2021-12-10 08:51:20,330] {spark_submit.py:523} INFO - WARNING: All illegal access operations will be denied in a future release
[2021-12-10 08:51:20,422] {spark_submit.py:523} INFO - Parsed arguments:
[2021-12-10 08:51:20,428] {spark_submit.py:523} INFO - master                  spark://spark:7077
[2021-12-10 08:51:20,431] {spark_submit.py:523} INFO - deployMode              null
[2021-12-10 08:51:20,432] {spark_submit.py:523} INFO - executorMemory          null
[2021-12-10 08:51:20,437] {spark_submit.py:523} INFO - executorCores           null
[2021-12-10 08:51:20,439] {spark_submit.py:523} INFO - totalExecutorCores      null
[2021-12-10 08:51:20,440] {spark_submit.py:523} INFO - propertiesFile          null
[2021-12-10 08:51:20,441] {spark_submit.py:523} INFO - driverMemory            null
[2021-12-10 08:51:20,442] {spark_submit.py:523} INFO - driverCores             null
[2021-12-10 08:51:20,443] {spark_submit.py:523} INFO - driverExtraClassPath    null
[2021-12-10 08:51:20,444] {spark_submit.py:523} INFO - driverExtraLibraryPath  null
[2021-12-10 08:51:20,446] {spark_submit.py:523} INFO - driverExtraJavaOptions  null
[2021-12-10 08:51:20,448] {spark_submit.py:523} INFO - supervise               false
[2021-12-10 08:51:20,449] {spark_submit.py:523} INFO - queue                   null
[2021-12-10 08:51:20,450] {spark_submit.py:523} INFO - numExecutors            null
[2021-12-10 08:51:20,451] {spark_submit.py:523} INFO - files                   null
[2021-12-10 08:51:20,452] {spark_submit.py:523} INFO - pyFiles                 null
[2021-12-10 08:51:20,453] {spark_submit.py:523} INFO - archives                null
[2021-12-10 08:51:20,455] {spark_submit.py:523} INFO - mainClass               null
[2021-12-10 08:51:20,456] {spark_submit.py:523} INFO - primaryResource         file:/opt/***/jobs/persist_db.py
[2021-12-10 08:51:20,456] {spark_submit.py:523} INFO - name                    persist data
[2021-12-10 08:51:20,458] {spark_submit.py:523} INFO - childArgs               [cork]
[2021-12-10 08:51:20,459] {spark_submit.py:523} INFO - jars                    null
[2021-12-10 08:51:20,460] {spark_submit.py:523} INFO - packages                null
[2021-12-10 08:51:20,461] {spark_submit.py:523} INFO - packagesExclusions      null
[2021-12-10 08:51:20,462] {spark_submit.py:523} INFO - repositories            null
[2021-12-10 08:51:20,463] {spark_submit.py:523} INFO - verbose                 true
[2021-12-10 08:51:20,464] {spark_submit.py:523} INFO - 
[2021-12-10 08:51:20,465] {spark_submit.py:523} INFO - Spark properties used, including those specified through
[2021-12-10 08:51:20,466] {spark_submit.py:523} INFO - --conf and those from the properties file null:
[2021-12-10 08:51:20,467] {spark_submit.py:523} INFO - (spark.master,spark://spark:7077)
[2021-12-10 08:51:20,467] {spark_submit.py:523} INFO - 
[2021-12-10 08:51:20,469] {spark_submit.py:523} INFO - 
[2021-12-10 08:51:21,268] {spark_submit.py:523} INFO - Main class:
[2021-12-10 08:51:21,270] {spark_submit.py:523} INFO - org.apache.spark.deploy.PythonRunner
[2021-12-10 08:51:21,272] {spark_submit.py:523} INFO - Arguments:
[2021-12-10 08:51:21,275] {spark_submit.py:523} INFO - file:/opt/***/jobs/persist_db.py
[2021-12-10 08:51:21,276] {spark_submit.py:523} INFO - null
[2021-12-10 08:51:21,277] {spark_submit.py:523} INFO - cork
[2021-12-10 08:51:21,278] {spark_submit.py:523} INFO - --verbose
[2021-12-10 08:51:21,280] {spark_submit.py:523} INFO - Spark config:
[2021-12-10 08:51:21,282] {spark_submit.py:523} INFO - (spark.master,spark://spark:7077)
[2021-12-10 08:51:21,284] {spark_submit.py:523} INFO - (spark.app.name,persist data)
[2021-12-10 08:51:21,286] {spark_submit.py:523} INFO - (spark.submit.pyFiles,)
[2021-12-10 08:51:21,287] {spark_submit.py:523} INFO - (spark.submit.deployMode,client)
[2021-12-10 08:51:21,288] {spark_submit.py:523} INFO - Classpath elements:
[2021-12-10 08:51:21,291] {spark_submit.py:523} INFO - 
[2021-12-10 08:51:21,297] {spark_submit.py:523} INFO - 
[2021-12-10 08:51:21,298] {spark_submit.py:523} INFO - 
[2021-12-10 08:51:23,255] {spark_submit.py:523} INFO - Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
[2021-12-10 08:51:23,277] {spark_submit.py:523} INFO - 21/12/10 08:51:23 INFO SparkContext: Running Spark version 3.2.0
[2021-12-10 08:51:23,575] {spark_submit.py:523} INFO - 21/12/10 08:51:23 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2021-12-10 08:51:23,945] {spark_submit.py:523} INFO - 21/12/10 08:51:23 INFO ResourceUtils: ==============================================================
[2021-12-10 08:51:23,946] {spark_submit.py:523} INFO - 21/12/10 08:51:23 INFO ResourceUtils: No custom resources configured for spark.driver.
[2021-12-10 08:51:23,948] {spark_submit.py:523} INFO - 21/12/10 08:51:23 INFO ResourceUtils: ==============================================================
[2021-12-10 08:51:23,949] {spark_submit.py:523} INFO - 21/12/10 08:51:23 INFO SparkContext: Submitted application: Persist DB
[2021-12-10 08:51:23,993] {spark_submit.py:523} INFO - 21/12/10 08:51:23 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2021-12-10 08:51:24,014] {spark_submit.py:523} INFO - 21/12/10 08:51:24 INFO ResourceProfile: Limiting resource is cpu
[2021-12-10 08:51:24,015] {spark_submit.py:523} INFO - 21/12/10 08:51:24 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2021-12-10 08:51:24,121] {spark_submit.py:523} INFO - 21/12/10 08:51:24 INFO SecurityManager: Changing view acls to: ***
[2021-12-10 08:51:24,122] {spark_submit.py:523} INFO - 21/12/10 08:51:24 INFO SecurityManager: Changing modify acls to: ***
[2021-12-10 08:51:24,123] {spark_submit.py:523} INFO - 21/12/10 08:51:24 INFO SecurityManager: Changing view acls groups to:
[2021-12-10 08:51:24,125] {spark_submit.py:523} INFO - 21/12/10 08:51:24 INFO SecurityManager: Changing modify acls groups to:
[2021-12-10 08:51:24,126] {spark_submit.py:523} INFO - 21/12/10 08:51:24 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(***); groups with view permissions: Set(); users  with modify permissions: Set(***); groups with modify permissions: Set()
[2021-12-10 08:51:24,837] {spark_submit.py:523} INFO - 21/12/10 08:51:24 INFO Utils: Successfully started service 'sparkDriver' on port 43709.
[2021-12-10 08:51:24,909] {spark_submit.py:523} INFO - 21/12/10 08:51:24 INFO SparkEnv: Registering MapOutputTracker
[2021-12-10 08:51:24,987] {spark_submit.py:523} INFO - 21/12/10 08:51:24 INFO SparkEnv: Registering BlockManagerMaster
[2021-12-10 08:51:25,030] {spark_submit.py:523} INFO - 21/12/10 08:51:25 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2021-12-10 08:51:25,032] {spark_submit.py:523} INFO - 21/12/10 08:51:25 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2021-12-10 08:51:25,046] {spark_submit.py:523} INFO - 21/12/10 08:51:25 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2021-12-10 08:51:25,103] {spark_submit.py:523} INFO - 21/12/10 08:51:25 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-bc2ea2fa-be9b-4ac4-a1af-a7b57f65f613
[2021-12-10 08:51:25,145] {spark_submit.py:523} INFO - 21/12/10 08:51:25 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2021-12-10 08:51:25,179] {spark_submit.py:523} INFO - 21/12/10 08:51:25 INFO SparkEnv: Registering OutputCommitCoordinator
[2021-12-10 08:51:25,606] {spark_submit.py:523} INFO - 21/12/10 08:51:25 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2021-12-10 08:51:25,608] {spark_submit.py:523} INFO - 21/12/10 08:51:25 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.
[2021-12-10 08:51:25,610] {spark_submit.py:523} INFO - 21/12/10 08:51:25 WARN Utils: Service 'SparkUI' could not bind on port 4042. Attempting port 4043.
[2021-12-10 08:51:25,611] {spark_submit.py:523} INFO - 21/12/10 08:51:25 WARN Utils: Service 'SparkUI' could not bind on port 4043. Attempting port 4044.
[2021-12-10 08:51:25,612] {spark_submit.py:523} INFO - 21/12/10 08:51:25 WARN Utils: Service 'SparkUI' could not bind on port 4044. Attempting port 4045.
[2021-12-10 08:51:25,615] {spark_submit.py:523} INFO - 21/12/10 08:51:25 WARN Utils: Service 'SparkUI' could not bind on port 4045. Attempting port 4046.
[2021-12-10 08:51:25,617] {spark_submit.py:523} INFO - 21/12/10 08:51:25 WARN Utils: Service 'SparkUI' could not bind on port 4046. Attempting port 4047.
[2021-12-10 08:51:25,619] {spark_submit.py:523} INFO - 21/12/10 08:51:25 WARN Utils: Service 'SparkUI' could not bind on port 4047. Attempting port 4048.
[2021-12-10 08:51:25,621] {spark_submit.py:523} INFO - 21/12/10 08:51:25 WARN Utils: Service 'SparkUI' could not bind on port 4048. Attempting port 4049.
[2021-12-10 08:51:25,639] {spark_submit.py:523} INFO - 21/12/10 08:51:25 INFO Utils: Successfully started service 'SparkUI' on port 4049.
[2021-12-10 08:51:25,748] {spark_submit.py:523} INFO - 21/12/10 08:51:25 INFO SparkUI: Bound SparkUI to 0.0.0.0, and started at http://041e6f8654c3:4049
[2021-12-10 08:51:26,206] {spark_submit.py:523} INFO - 21/12/10 08:51:26 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2021-12-10 08:51:26,374] {spark_submit.py:523} INFO - 21/12/10 08:51:26 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master spark:7077
[2021-12-10 08:51:26,375] {spark_submit.py:523} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2021-12-10 08:51:26,376] {spark_submit.py:523} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:301)
[2021-12-10 08:51:26,377] {spark_submit.py:523} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2021-12-10 08:51:26,378] {spark_submit.py:523} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:101)
[2021-12-10 08:51:26,379] {spark_submit.py:523} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:109)
[2021-12-10 08:51:26,380] {spark_submit.py:523} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:107)
[2021-12-10 08:51:26,382] {spark_submit.py:523} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2021-12-10 08:51:26,383] {spark_submit.py:523} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2021-12-10 08:51:26,384] {spark_submit.py:523} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2021-12-10 08:51:26,385] {spark_submit.py:523} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2021-12-10 08:51:26,387] {spark_submit.py:523} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-10 08:51:26,388] {spark_submit.py:523} INFO - Caused by: java.io.IOException: Failed to connect to spark:7077
[2021-12-10 08:51:26,389] {spark_submit.py:523} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:288)
[2021-12-10 08:51:26,391] {spark_submit.py:523} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:218)
[2021-12-10 08:51:26,391] {spark_submit.py:523} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:230)
[2021-12-10 08:51:26,393] {spark_submit.py:523} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2021-12-10 08:51:26,394] {spark_submit.py:523} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2021-12-10 08:51:26,396] {spark_submit.py:523} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2021-12-10 08:51:26,397] {spark_submit.py:523} INFO - ... 4 more
[2021-12-10 08:51:26,399] {spark_submit.py:523} INFO - Caused by: java.net.UnknownHostException: spark
[2021-12-10 08:51:26,400] {spark_submit.py:523} INFO - at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
[2021-12-10 08:51:26,401] {spark_submit.py:523} INFO - at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509)
[2021-12-10 08:51:26,403] {spark_submit.py:523} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1368)
[2021-12-10 08:51:26,404] {spark_submit.py:523} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1302)
[2021-12-10 08:51:26,405] {spark_submit.py:523} INFO - at java.base/java.net.InetAddress.getByName(InetAddress.java:1252)
[2021-12-10 08:51:26,406] {spark_submit.py:523} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156)
[2021-12-10 08:51:26,407] {spark_submit.py:523} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153)
[2021-12-10 08:51:26,408] {spark_submit.py:523} INFO - at java.base/java.security.AccessController.doPrivileged(Native Method)
[2021-12-10 08:51:26,410] {spark_submit.py:523} INFO - at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153)
[2021-12-10 08:51:26,415] {spark_submit.py:523} INFO - at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41)
[2021-12-10 08:51:26,416] {spark_submit.py:523} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
[2021-12-10 08:51:26,418] {spark_submit.py:523} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53)
[2021-12-10 08:51:26,419] {spark_submit.py:523} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
[2021-12-10 08:51:26,420] {spark_submit.py:523} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
[2021-12-10 08:51:26,422] {spark_submit.py:523} INFO - at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
[2021-12-10 08:51:26,423] {spark_submit.py:523} INFO - at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:206)
[2021-12-10 08:51:26,423] {spark_submit.py:523} INFO - at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46)
[2021-12-10 08:51:26,425] {spark_submit.py:523} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:180)
[2021-12-10 08:51:26,425] {spark_submit.py:523} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:166)
[2021-12-10 08:51:26,426] {spark_submit.py:523} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
[2021-12-10 08:51:26,427] {spark_submit.py:523} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
[2021-12-10 08:51:26,428] {spark_submit.py:523} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
[2021-12-10 08:51:26,429] {spark_submit.py:523} INFO - at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
[2021-12-10 08:51:26,429] {spark_submit.py:523} INFO - at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
[2021-12-10 08:51:26,430] {spark_submit.py:523} INFO - at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
[2021-12-10 08:51:26,431] {spark_submit.py:523} INFO - at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
[2021-12-10 08:51:26,432] {spark_submit.py:523} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:1008)
[2021-12-10 08:51:26,433] {spark_submit.py:523} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:516)
[2021-12-10 08:51:26,434] {spark_submit.py:523} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
[2021-12-10 08:51:26,434] {spark_submit.py:523} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
[2021-12-10 08:51:26,436] {spark_submit.py:523} INFO - at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[2021-12-10 08:51:26,437] {spark_submit.py:523} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
[2021-12-10 08:51:26,438] {spark_submit.py:523} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[2021-12-10 08:51:26,439] {spark_submit.py:523} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[2021-12-10 08:51:26,441] {spark_submit.py:523} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2021-12-10 08:51:26,442] {spark_submit.py:523} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2021-12-10 08:51:26,443] {spark_submit.py:523} INFO - ... 1 more
[2021-12-10 08:51:46,171] {spark_submit.py:523} INFO - 21/12/10 08:51:46 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2021-12-10 08:51:46,194] {spark_submit.py:523} INFO - 21/12/10 08:51:46 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master spark:7077
[2021-12-10 08:51:46,195] {spark_submit.py:523} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2021-12-10 08:51:46,196] {spark_submit.py:523} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:301)
[2021-12-10 08:51:46,197] {spark_submit.py:523} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2021-12-10 08:51:46,198] {spark_submit.py:523} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:101)
[2021-12-10 08:51:46,198] {spark_submit.py:523} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:109)
[2021-12-10 08:51:46,199] {spark_submit.py:523} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:107)
[2021-12-10 08:51:46,200] {spark_submit.py:523} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2021-12-10 08:51:46,201] {spark_submit.py:523} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2021-12-10 08:51:46,202] {spark_submit.py:523} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2021-12-10 08:51:46,203] {spark_submit.py:523} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2021-12-10 08:51:46,203] {spark_submit.py:523} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-10 08:51:46,204] {spark_submit.py:523} INFO - Caused by: java.io.IOException: Failed to connect to spark:7077
[2021-12-10 08:51:46,205] {spark_submit.py:523} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:288)
[2021-12-10 08:51:46,206] {spark_submit.py:523} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:218)
[2021-12-10 08:51:46,206] {spark_submit.py:523} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:230)
[2021-12-10 08:51:46,207] {spark_submit.py:523} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2021-12-10 08:51:46,208] {spark_submit.py:523} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2021-12-10 08:51:46,209] {spark_submit.py:523} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2021-12-10 08:51:46,210] {spark_submit.py:523} INFO - ... 4 more
[2021-12-10 08:51:46,210] {spark_submit.py:523} INFO - Caused by: java.net.UnknownHostException: spark
[2021-12-10 08:51:46,211] {spark_submit.py:523} INFO - at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
[2021-12-10 08:51:46,212] {spark_submit.py:523} INFO - at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509)
[2021-12-10 08:51:46,213] {spark_submit.py:523} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1368)
[2021-12-10 08:51:46,214] {spark_submit.py:523} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1302)
[2021-12-10 08:51:46,214] {spark_submit.py:523} INFO - at java.base/java.net.InetAddress.getByName(InetAddress.java:1252)
[2021-12-10 08:51:46,215] {spark_submit.py:523} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156)
[2021-12-10 08:51:46,216] {spark_submit.py:523} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153)
[2021-12-10 08:51:46,217] {spark_submit.py:523} INFO - at java.base/java.security.AccessController.doPrivileged(Native Method)
[2021-12-10 08:51:46,218] {spark_submit.py:523} INFO - at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153)
[2021-12-10 08:51:46,219] {spark_submit.py:523} INFO - at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41)
[2021-12-10 08:51:46,220] {spark_submit.py:523} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
[2021-12-10 08:51:46,221] {spark_submit.py:523} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53)
[2021-12-10 08:51:46,222] {spark_submit.py:523} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
[2021-12-10 08:51:46,223] {spark_submit.py:523} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
[2021-12-10 08:51:46,224] {spark_submit.py:523} INFO - at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
[2021-12-10 08:51:46,225] {spark_submit.py:523} INFO - at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:206)
[2021-12-10 08:51:46,226] {spark_submit.py:523} INFO - at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46)
[2021-12-10 08:51:46,226] {spark_submit.py:523} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:180)
[2021-12-10 08:51:46,227] {spark_submit.py:523} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:166)
[2021-12-10 08:51:46,228] {spark_submit.py:523} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
[2021-12-10 08:51:46,229] {spark_submit.py:523} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
[2021-12-10 08:51:46,230] {spark_submit.py:523} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
[2021-12-10 08:51:46,231] {spark_submit.py:523} INFO - at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
[2021-12-10 08:51:46,231] {spark_submit.py:523} INFO - at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
[2021-12-10 08:51:46,232] {spark_submit.py:523} INFO - at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
[2021-12-10 08:51:46,233] {spark_submit.py:523} INFO - at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
[2021-12-10 08:51:46,234] {spark_submit.py:523} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:1008)
[2021-12-10 08:51:46,235] {spark_submit.py:523} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:516)
[2021-12-10 08:51:46,236] {spark_submit.py:523} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
[2021-12-10 08:51:46,236] {spark_submit.py:523} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
[2021-12-10 08:51:46,237] {spark_submit.py:523} INFO - at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[2021-12-10 08:51:46,238] {spark_submit.py:523} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
[2021-12-10 08:51:46,238] {spark_submit.py:523} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[2021-12-10 08:51:46,239] {spark_submit.py:523} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[2021-12-10 08:51:46,240] {spark_submit.py:523} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2021-12-10 08:51:46,240] {spark_submit.py:523} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2021-12-10 08:51:46,241] {spark_submit.py:523} INFO - ... 1 more
[2021-12-10 08:52:06,139] {spark_submit.py:523} INFO - 21/12/10 08:52:06 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2021-12-10 08:52:06,159] {spark_submit.py:523} INFO - 21/12/10 08:52:06 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master spark:7077
[2021-12-10 08:52:06,160] {spark_submit.py:523} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2021-12-10 08:52:06,161] {spark_submit.py:523} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:301)
[2021-12-10 08:52:06,163] {spark_submit.py:523} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2021-12-10 08:52:06,164] {spark_submit.py:523} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:101)
[2021-12-10 08:52:06,164] {spark_submit.py:523} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:109)
[2021-12-10 08:52:06,165] {spark_submit.py:523} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:107)
[2021-12-10 08:52:06,167] {spark_submit.py:523} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2021-12-10 08:52:06,168] {spark_submit.py:523} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2021-12-10 08:52:06,168] {spark_submit.py:523} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2021-12-10 08:52:06,169] {spark_submit.py:523} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2021-12-10 08:52:06,170] {spark_submit.py:523} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-10 08:52:06,171] {spark_submit.py:523} INFO - Caused by: java.io.IOException: Failed to connect to spark:7077
[2021-12-10 08:52:06,172] {spark_submit.py:523} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:288)
[2021-12-10 08:52:06,173] {spark_submit.py:523} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:218)
[2021-12-10 08:52:06,173] {spark_submit.py:523} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:230)
[2021-12-10 08:52:06,174] {spark_submit.py:523} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2021-12-10 08:52:06,175] {spark_submit.py:523} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2021-12-10 08:52:06,176] {spark_submit.py:523} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2021-12-10 08:52:06,177] {spark_submit.py:523} INFO - ... 4 more
[2021-12-10 08:52:06,178] {spark_submit.py:523} INFO - Caused by: java.net.UnknownHostException: spark
[2021-12-10 08:52:06,179] {spark_submit.py:523} INFO - at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
[2021-12-10 08:52:06,180] {spark_submit.py:523} INFO - at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509)
[2021-12-10 08:52:06,181] {spark_submit.py:523} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1368)
[2021-12-10 08:52:06,182] {spark_submit.py:523} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1302)
[2021-12-10 08:52:06,183] {spark_submit.py:523} INFO - at java.base/java.net.InetAddress.getByName(InetAddress.java:1252)
[2021-12-10 08:52:06,184] {spark_submit.py:523} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156)
[2021-12-10 08:52:06,185] {spark_submit.py:523} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153)
[2021-12-10 08:52:06,186] {spark_submit.py:523} INFO - at java.base/java.security.AccessController.doPrivileged(Native Method)
[2021-12-10 08:52:06,186] {spark_submit.py:523} INFO - at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153)
[2021-12-10 08:52:06,187] {spark_submit.py:523} INFO - at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41)
[2021-12-10 08:52:06,188] {spark_submit.py:523} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
[2021-12-10 08:52:06,189] {spark_submit.py:523} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53)
[2021-12-10 08:52:06,190] {spark_submit.py:523} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
[2021-12-10 08:52:06,191] {spark_submit.py:523} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
[2021-12-10 08:52:06,192] {spark_submit.py:523} INFO - at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
[2021-12-10 08:52:06,194] {spark_submit.py:523} INFO - at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:206)
[2021-12-10 08:52:06,195] {spark_submit.py:523} INFO - at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46)
[2021-12-10 08:52:06,195] {spark_submit.py:523} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:180)
[2021-12-10 08:52:06,196] {spark_submit.py:523} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:166)
[2021-12-10 08:52:06,197] {spark_submit.py:523} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
[2021-12-10 08:52:06,198] {spark_submit.py:523} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
[2021-12-10 08:52:06,199] {spark_submit.py:523} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
[2021-12-10 08:52:06,199] {spark_submit.py:523} INFO - at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
[2021-12-10 08:52:06,200] {spark_submit.py:523} INFO - at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
[2021-12-10 08:52:06,201] {spark_submit.py:523} INFO - at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
[2021-12-10 08:52:06,202] {spark_submit.py:523} INFO - at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
[2021-12-10 08:52:06,202] {spark_submit.py:523} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:1008)
[2021-12-10 08:52:06,203] {spark_submit.py:523} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:516)
[2021-12-10 08:52:06,204] {spark_submit.py:523} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
[2021-12-10 08:52:06,204] {spark_submit.py:523} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
[2021-12-10 08:52:06,205] {spark_submit.py:523} INFO - at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[2021-12-10 08:52:06,206] {spark_submit.py:523} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
[2021-12-10 08:52:06,206] {spark_submit.py:523} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[2021-12-10 08:52:06,207] {spark_submit.py:523} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[2021-12-10 08:52:06,208] {spark_submit.py:523} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2021-12-10 08:52:06,209] {spark_submit.py:523} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2021-12-10 08:52:06,209] {spark_submit.py:523} INFO - ... 1 more
[2021-12-10 08:52:26,139] {spark_submit.py:523} INFO - 21/12/10 08:52:26 ERROR StandaloneSchedulerBackend: Application has been killed. Reason: All masters are unresponsive! Giving up.
[2021-12-10 08:52:26,142] {spark_submit.py:523} INFO - 21/12/10 08:52:26 WARN StandaloneSchedulerBackend: Application ID is not initialized yet.
[2021-12-10 08:52:26,156] {spark_submit.py:523} INFO - 21/12/10 08:52:26 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 46615.
[2021-12-10 08:52:26,158] {spark_submit.py:523} INFO - 21/12/10 08:52:26 INFO NettyBlockTransferService: Server created on 041e6f8654c3:46615
[2021-12-10 08:52:26,162] {spark_submit.py:523} INFO - 21/12/10 08:52:26 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2021-12-10 08:52:26,170] {spark_submit.py:523} INFO - 21/12/10 08:52:26 INFO SparkUI: Stopped Spark web UI at http://041e6f8654c3:4049
[2021-12-10 08:52:26,176] {spark_submit.py:523} INFO - 21/12/10 08:52:26 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 041e6f8654c3, 46615, None)
[2021-12-10 08:52:26,182] {spark_submit.py:523} INFO - 21/12/10 08:52:26 INFO BlockManagerMasterEndpoint: Registering block manager 041e6f8654c3:46615 with 434.4 MiB RAM, BlockManagerId(driver, 041e6f8654c3, 46615, None)
[2021-12-10 08:52:26,186] {spark_submit.py:523} INFO - 21/12/10 08:52:26 INFO StandaloneSchedulerBackend: Shutting down all executors
[2021-12-10 08:52:26,187] {spark_submit.py:523} INFO - 21/12/10 08:52:26 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 041e6f8654c3, 46615, None)
[2021-12-10 08:52:26,188] {spark_submit.py:523} INFO - 21/12/10 08:52:26 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 041e6f8654c3, 46615, None)
[2021-12-10 08:52:26,192] {spark_submit.py:523} INFO - 21/12/10 08:52:26 INFO CoarseGrainedSchedulerBackend$DriverEndpoint: Asking each executor to shut down
[2021-12-10 08:52:26,204] {spark_submit.py:523} INFO - 21/12/10 08:52:26 WARN StandaloneAppClient$ClientEndpoint: Drop UnregisterApplication(null) because has not yet connected to master
[2021-12-10 08:52:26,222] {spark_submit.py:523} INFO - 21/12/10 08:52:26 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2021-12-10 08:52:26,248] {spark_submit.py:523} INFO - 21/12/10 08:52:26 INFO MemoryStore: MemoryStore cleared
[2021-12-10 08:52:26,250] {spark_submit.py:523} INFO - 21/12/10 08:52:26 INFO BlockManager: BlockManager stopped
[2021-12-10 08:52:26,262] {spark_submit.py:523} INFO - 21/12/10 08:52:26 INFO BlockManagerMaster: BlockManagerMaster stopped
[2021-12-10 08:52:26,269] {spark_submit.py:523} INFO - 21/12/10 08:52:26 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2021-12-10 08:52:26,294] {spark_submit.py:523} INFO - 21/12/10 08:52:26 INFO SparkContext: Successfully stopped SparkContext
[2021-12-10 08:52:26,469] {spark_submit.py:523} INFO - 21/12/10 08:52:26 ERROR SparkContext: Error initializing SparkContext.
[2021-12-10 08:52:26,470] {spark_submit.py:523} INFO - java.lang.IllegalArgumentException: requirement failed: Can only call getServletHandlers on a running MetricsSystem
[2021-12-10 08:52:26,471] {spark_submit.py:523} INFO - at scala.Predef$.require(Predef.scala:281)
[2021-12-10 08:52:26,472] {spark_submit.py:523} INFO - at org.apache.spark.metrics.MetricsSystem.getServletHandlers(MetricsSystem.scala:89)
[2021-12-10 08:52:26,473] {spark_submit.py:523} INFO - at org.apache.spark.SparkContext.<init>(SparkContext.scala:603)
[2021-12-10 08:52:26,474] {spark_submit.py:523} INFO - at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2021-12-10 08:52:26,475] {spark_submit.py:523} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2021-12-10 08:52:26,476] {spark_submit.py:523} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2021-12-10 08:52:26,477] {spark_submit.py:523} INFO - at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2021-12-10 08:52:26,478] {spark_submit.py:523} INFO - at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[2021-12-10 08:52:26,479] {spark_submit.py:523} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2021-12-10 08:52:26,480] {spark_submit.py:523} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2021-12-10 08:52:26,484] {spark_submit.py:523} INFO - at py4j.Gateway.invoke(Gateway.java:238)
[2021-12-10 08:52:26,485] {spark_submit.py:523} INFO - at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2021-12-10 08:52:26,489] {spark_submit.py:523} INFO - at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2021-12-10 08:52:26,495] {spark_submit.py:523} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2021-12-10 08:52:26,496] {spark_submit.py:523} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2021-12-10 08:52:26,497] {spark_submit.py:523} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-10 08:52:26,498] {spark_submit.py:523} INFO - 21/12/10 08:52:26 INFO SparkContext: SparkContext already stopped.
[2021-12-10 08:52:26,500] {spark_submit.py:523} INFO - Traceback (most recent call last):
[2021-12-10 08:52:26,501] {spark_submit.py:523} INFO - File "/opt/***/jobs/persist_db.py", line 52, in <module>
[2021-12-10 08:52:26,502] {spark_submit.py:523} INFO - .config("spark.driver.bindAddress", "localhost") \
[2021-12-10 08:52:26,506] {spark_submit.py:523} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/session.py", line 228, in getOrCreate
[2021-12-10 08:52:26,509] {spark_submit.py:523} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 392, in getOrCreate
[2021-12-10 08:52:26,510] {spark_submit.py:523} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 147, in __init__
[2021-12-10 08:52:26,514] {spark_submit.py:523} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 209, in _do_init
[2021-12-10 08:52:26,517] {spark_submit.py:523} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 329, in _initialize_context
[2021-12-10 08:52:26,518] {spark_submit.py:523} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/py4j-0.10.9.2-src.zip/py4j/java_gateway.py", line 1574, in __call__
[2021-12-10 08:52:26,519] {spark_submit.py:523} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/py4j-0.10.9.2-src.zip/py4j/protocol.py", line 328, in get_return_value
[2021-12-10 08:52:26,520] {spark_submit.py:523} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling None.org.apache.spark.api.java.JavaSparkContext.
[2021-12-10 08:52:26,521] {spark_submit.py:523} INFO - : java.lang.IllegalArgumentException: requirement failed: Can only call getServletHandlers on a running MetricsSystem
[2021-12-10 08:52:26,523] {spark_submit.py:523} INFO - at scala.Predef$.require(Predef.scala:281)
[2021-12-10 08:52:26,524] {spark_submit.py:523} INFO - at org.apache.spark.metrics.MetricsSystem.getServletHandlers(MetricsSystem.scala:89)
[2021-12-10 08:52:26,525] {spark_submit.py:523} INFO - at org.apache.spark.SparkContext.<init>(SparkContext.scala:603)
[2021-12-10 08:52:26,526] {spark_submit.py:523} INFO - at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2021-12-10 08:52:26,527] {spark_submit.py:523} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2021-12-10 08:52:26,528] {spark_submit.py:523} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2021-12-10 08:52:26,529] {spark_submit.py:523} INFO - at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2021-12-10 08:52:26,530] {spark_submit.py:523} INFO - at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[2021-12-10 08:52:26,530] {spark_submit.py:523} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2021-12-10 08:52:26,531] {spark_submit.py:523} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2021-12-10 08:52:26,532] {spark_submit.py:523} INFO - at py4j.Gateway.invoke(Gateway.java:238)
[2021-12-10 08:52:26,533] {spark_submit.py:523} INFO - at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2021-12-10 08:52:26,534] {spark_submit.py:523} INFO - at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2021-12-10 08:52:26,535] {spark_submit.py:523} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2021-12-10 08:52:26,536] {spark_submit.py:523} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2021-12-10 08:52:26,536] {spark_submit.py:523} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-10 08:52:26,537] {spark_submit.py:523} INFO - 
[2021-12-10 08:52:26,596] {spark_submit.py:523} INFO - 21/12/10 08:52:26 INFO ShutdownHookManager: Shutdown hook called
[2021-12-10 08:52:26,597] {spark_submit.py:523} INFO - 21/12/10 08:52:26 INFO ShutdownHookManager: Deleting directory /tmp/spark-b70b18c2-664b-4680-9d4f-0d360f3813bf
[2021-12-10 08:52:26,603] {spark_submit.py:523} INFO - 21/12/10 08:52:26 INFO ShutdownHookManager: Deleting directory /tmp/spark-68c91eef-165e-4030-9ff0-dc85dee3cb29
[2021-12-10 08:52:26,729] {taskinstance.py:1703} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 179, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 452, in submit
    self._mask_cmd(spark_submit_cmd), returncode
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark:7077 --conf spark.master=spark://spark:7077 --name persist data --verbose /opt/***/jobs/persist_db.py cork. Error code is: 1.
[2021-12-10 08:52:26,736] {taskinstance.py:1280} INFO - Marking task as UP_FOR_RETRY. dag_id=scraping_daft_cork, task_id=persist_data, execution_date=20211209T010000, start_date=20211210T085113, end_date=20211210T085226
[2021-12-10 08:52:26,758] {standard_task_runner.py:91} ERROR - Failed to execute job 992 for task persist_data
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 179, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 452, in submit
    self._mask_cmd(spark_submit_cmd), returncode
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark:7077 --conf spark.master=spark://spark:7077 --name persist data --verbose /opt/***/jobs/persist_db.py cork. Error code is: 1.
[2021-12-10 08:52:26,800] {local_task_job.py:154} INFO - Task exited with return code 1
[2021-12-10 08:52:26,881] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
