[2021-12-29 12:10:01,007] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: scraping_daft_clare.persist_data scheduled__2021-12-28T09:15:00+00:00 [queued]>
[2021-12-29 12:10:01,031] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: scraping_daft_clare.persist_data scheduled__2021-12-28T09:15:00+00:00 [queued]>
[2021-12-29 12:10:01,032] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-29 12:10:01,034] {taskinstance.py:1242} INFO - Starting attempt 3 of 4
[2021-12-29 12:10:01,035] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-29 12:10:01,058] {taskinstance.py:1262} INFO - Executing <Task(SparkSubmitOperator): persist_data> on 2021-12-28 09:15:00+00:00
[2021-12-29 12:10:01,070] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'scraping_daft_clare', 'persist_data', 'scheduled__2021-12-28T09:15:00+00:00', '--job-id', '5370', '--raw', '--subdir', 'DAGS_FOLDER/scraping_daft_clare.py', '--cfg-path', '/tmp/tmpkf4_itos', '--error-file', '/tmp/tmpmxv1bwfh']
[2021-12-29 12:10:01,072] {standard_task_runner.py:77} INFO - Job 5370: Subtask persist_data
[2021-12-29 12:10:01,064] {standard_task_runner.py:52} INFO - Started process 31515 to run task
[2021-12-29 12:10:01,214] {logging_mixin.py:109} INFO - Running <TaskInstance: scraping_daft_clare.persist_data scheduled__2021-12-28T09:15:00+00:00 [running]> on host 6bdda4c19a85
[2021-12-29 12:10:01,418] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=clement.liscoet@gmail.com
AIRFLOW_CTX_DAG_OWNER=clemoni
AIRFLOW_CTX_DAG_ID=scraping_daft_clare
AIRFLOW_CTX_TASK_ID=persist_data
AIRFLOW_CTX_EXECUTION_DATE=2021-12-28T09:15:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-28T09:15:00+00:00
[2021-12-29 12:10:01,447] {base.py:79} INFO - Using connection to: id: spark_default. Host: spark://spark:7077, Port: None, Schema: , Login: ***, Password: ***, extra: {}
[2021-12-29 12:10:01,451] {spark_submit.py:360} INFO - Spark-Submit cmd: spark-submit --master spark://spark:7077 --conf spark.master=spark://spark:7077 --name persist data --verbose /opt/***/jobs/persist_db.py clare
[2021-12-29 12:10:04,440] {spark_submit.py:514} INFO - Using properties file: null
[2021-12-29 12:10:04,608] {spark_submit.py:514} INFO - WARNING: An illegal reflective access operation has occurred
[2021-12-29 12:10:04,609] {spark_submit.py:514} INFO - WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/home/***/.local/lib/python3.6/site-packages/pyspark/jars/spark-unsafe_2.12-3.2.0.jar) to constructor java.nio.DirectByteBuffer(long,int)
[2021-12-29 12:10:04,610] {spark_submit.py:514} INFO - WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
[2021-12-29 12:10:04,612] {spark_submit.py:514} INFO - WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[2021-12-29 12:10:04,613] {spark_submit.py:514} INFO - WARNING: All illegal access operations will be denied in a future release
[2021-12-29 12:10:04,761] {spark_submit.py:514} INFO - Parsed arguments:
[2021-12-29 12:10:04,763] {spark_submit.py:514} INFO - master                  spark://spark:7077
[2021-12-29 12:10:04,764] {spark_submit.py:514} INFO - deployMode              null
[2021-12-29 12:10:04,766] {spark_submit.py:514} INFO - executorMemory          null
[2021-12-29 12:10:04,767] {spark_submit.py:514} INFO - executorCores           null
[2021-12-29 12:10:04,768] {spark_submit.py:514} INFO - totalExecutorCores      null
[2021-12-29 12:10:04,769] {spark_submit.py:514} INFO - propertiesFile          null
[2021-12-29 12:10:04,770] {spark_submit.py:514} INFO - driverMemory            null
[2021-12-29 12:10:04,771] {spark_submit.py:514} INFO - driverCores             null
[2021-12-29 12:10:04,772] {spark_submit.py:514} INFO - driverExtraClassPath    null
[2021-12-29 12:10:04,774] {spark_submit.py:514} INFO - driverExtraLibraryPath  null
[2021-12-29 12:10:04,776] {spark_submit.py:514} INFO - driverExtraJavaOptions  null
[2021-12-29 12:10:04,777] {spark_submit.py:514} INFO - supervise               false
[2021-12-29 12:10:04,778] {spark_submit.py:514} INFO - queue                   null
[2021-12-29 12:10:04,779] {spark_submit.py:514} INFO - numExecutors            null
[2021-12-29 12:10:04,780] {spark_submit.py:514} INFO - files                   null
[2021-12-29 12:10:04,781] {spark_submit.py:514} INFO - pyFiles                 null
[2021-12-29 12:10:04,782] {spark_submit.py:514} INFO - archives                null
[2021-12-29 12:10:04,784] {spark_submit.py:514} INFO - mainClass               null
[2021-12-29 12:10:04,786] {spark_submit.py:514} INFO - primaryResource         file:/opt/***/jobs/persist_db.py
[2021-12-29 12:10:04,788] {spark_submit.py:514} INFO - name                    persist data
[2021-12-29 12:10:04,790] {spark_submit.py:514} INFO - childArgs               [clare]
[2021-12-29 12:10:04,792] {spark_submit.py:514} INFO - jars                    null
[2021-12-29 12:10:04,794] {spark_submit.py:514} INFO - packages                null
[2021-12-29 12:10:04,796] {spark_submit.py:514} INFO - packagesExclusions      null
[2021-12-29 12:10:04,797] {spark_submit.py:514} INFO - repositories            null
[2021-12-29 12:10:04,798] {spark_submit.py:514} INFO - verbose                 true
[2021-12-29 12:10:04,800] {spark_submit.py:514} INFO - 
[2021-12-29 12:10:04,801] {spark_submit.py:514} INFO - Spark properties used, including those specified through
[2021-12-29 12:10:04,803] {spark_submit.py:514} INFO - --conf and those from the properties file null:
[2021-12-29 12:10:04,806] {spark_submit.py:514} INFO - (spark.master,spark://spark:7077)
[2021-12-29 12:10:04,808] {spark_submit.py:514} INFO - 
[2021-12-29 12:10:04,809] {spark_submit.py:514} INFO - 
[2021-12-29 12:10:06,152] {spark_submit.py:514} INFO - Main class:
[2021-12-29 12:10:06,154] {spark_submit.py:514} INFO - org.apache.spark.deploy.PythonRunner
[2021-12-29 12:10:06,155] {spark_submit.py:514} INFO - Arguments:
[2021-12-29 12:10:06,157] {spark_submit.py:514} INFO - file:/opt/***/jobs/persist_db.py
[2021-12-29 12:10:06,158] {spark_submit.py:514} INFO - null
[2021-12-29 12:10:06,161] {spark_submit.py:514} INFO - clare
[2021-12-29 12:10:06,172] {spark_submit.py:514} INFO - --verbose
[2021-12-29 12:10:06,179] {spark_submit.py:514} INFO - Spark config:
[2021-12-29 12:10:06,207] {spark_submit.py:514} INFO - (spark.master,spark://spark:7077)
[2021-12-29 12:10:06,213] {spark_submit.py:514} INFO - (spark.app.name,persist data)
[2021-12-29 12:10:06,214] {spark_submit.py:514} INFO - (spark.submit.pyFiles,)
[2021-12-29 12:10:06,216] {spark_submit.py:514} INFO - (spark.submit.deployMode,client)
[2021-12-29 12:10:06,217] {spark_submit.py:514} INFO - Classpath elements:
[2021-12-29 12:10:06,218] {spark_submit.py:514} INFO - 
[2021-12-29 12:10:06,219] {spark_submit.py:514} INFO - 
[2021-12-29 12:10:06,221] {spark_submit.py:514} INFO - 
[2021-12-29 12:10:10,499] {spark_submit.py:514} INFO - Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
[2021-12-29 12:10:10,584] {spark_submit.py:514} INFO - 21/12/29 12:10:10 INFO SparkContext: Running Spark version 3.2.0
[2021-12-29 12:10:11,282] {spark_submit.py:514} INFO - 21/12/29 12:10:11 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2021-12-29 12:10:12,708] {spark_submit.py:514} INFO - 21/12/29 12:10:12 INFO ResourceUtils: ==============================================================
[2021-12-29 12:10:12,710] {spark_submit.py:514} INFO - 21/12/29 12:10:12 INFO ResourceUtils: No custom resources configured for spark.driver.
[2021-12-29 12:10:12,713] {spark_submit.py:514} INFO - 21/12/29 12:10:12 INFO ResourceUtils: ==============================================================
[2021-12-29 12:10:12,716] {spark_submit.py:514} INFO - 21/12/29 12:10:12 INFO SparkContext: Submitted application: Persist DB
[2021-12-29 12:10:12,944] {spark_submit.py:514} INFO - 21/12/29 12:10:12 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2021-12-29 12:10:13,077] {spark_submit.py:514} INFO - 21/12/29 12:10:13 INFO ResourceProfile: Limiting resource is cpu
[2021-12-29 12:10:13,079] {spark_submit.py:514} INFO - 21/12/29 12:10:13 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2021-12-29 12:10:13,683] {spark_submit.py:514} INFO - 21/12/29 12:10:13 INFO SecurityManager: Changing view acls to: ***
[2021-12-29 12:10:13,690] {spark_submit.py:514} INFO - 21/12/29 12:10:13 INFO SecurityManager: Changing modify acls to: ***
[2021-12-29 12:10:13,693] {spark_submit.py:514} INFO - 21/12/29 12:10:13 INFO SecurityManager: Changing view acls groups to:
[2021-12-29 12:10:13,696] {spark_submit.py:514} INFO - 21/12/29 12:10:13 INFO SecurityManager: Changing modify acls groups to:
[2021-12-29 12:10:13,700] {spark_submit.py:514} INFO - 21/12/29 12:10:13 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(***); groups with view permissions: Set(); users  with modify permissions: Set(***); groups with modify permissions: Set()
[2021-12-29 12:10:16,233] {spark_submit.py:514} INFO - 21/12/29 12:10:16 INFO Utils: Successfully started service 'sparkDriver' on port 34617.
[2021-12-29 12:10:16,559] {spark_submit.py:514} INFO - 21/12/29 12:10:16 INFO SparkEnv: Registering MapOutputTracker
[2021-12-29 12:10:17,465] {spark_submit.py:514} INFO - 21/12/29 12:10:17 INFO SparkEnv: Registering BlockManagerMaster
[2021-12-29 12:10:17,764] {spark_submit.py:514} INFO - 21/12/29 12:10:17 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2021-12-29 12:10:17,775] {spark_submit.py:514} INFO - 21/12/29 12:10:17 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2021-12-29 12:10:17,821] {spark_submit.py:514} INFO - 21/12/29 12:10:17 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2021-12-29 12:10:17,953] {spark_submit.py:514} INFO - 21/12/29 12:10:17 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-e56f90d4-49e6-4b36-bc3d-1896c6da5d25
[2021-12-29 12:10:18,117] {spark_submit.py:514} INFO - 21/12/29 12:10:18 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2021-12-29 12:10:18,425] {spark_submit.py:514} INFO - 21/12/29 12:10:18 INFO SparkEnv: Registering OutputCommitCoordinator
[2021-12-29 12:10:20,566] {spark_submit.py:514} INFO - 21/12/29 12:10:20 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2021-12-29 12:10:21,101] {spark_submit.py:514} INFO - 21/12/29 12:10:21 INFO SparkUI: Bound SparkUI to 0.0.0.0, and started at http://6bdda4c19a85:4040
[2021-12-29 12:10:22,977] {spark_submit.py:514} INFO - 21/12/29 12:10:22 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2021-12-29 12:10:23,885] {spark_submit.py:514} INFO - 21/12/29 12:10:23 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master spark:7077
[2021-12-29 12:10:23,890] {spark_submit.py:514} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2021-12-29 12:10:23,891] {spark_submit.py:514} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:301)
[2021-12-29 12:10:23,895] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2021-12-29 12:10:23,899] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:101)
[2021-12-29 12:10:23,903] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:109)
[2021-12-29 12:10:23,906] {spark_submit.py:514} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:107)
[2021-12-29 12:10:23,908] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2021-12-29 12:10:23,911] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2021-12-29 12:10:23,913] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2021-12-29 12:10:23,915] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2021-12-29 12:10:23,924] {spark_submit.py:514} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-29 12:10:23,926] {spark_submit.py:514} INFO - Caused by: java.io.IOException: Failed to connect to spark:7077
[2021-12-29 12:10:23,929] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:288)
[2021-12-29 12:10:23,931] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:218)
[2021-12-29 12:10:23,933] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:230)
[2021-12-29 12:10:23,936] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2021-12-29 12:10:23,937] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2021-12-29 12:10:23,941] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2021-12-29 12:10:23,943] {spark_submit.py:514} INFO - ... 4 more
[2021-12-29 12:10:23,944] {spark_submit.py:514} INFO - Caused by: java.net.UnknownHostException: spark
[2021-12-29 12:10:23,948] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
[2021-12-29 12:10:23,953] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509)
[2021-12-29 12:10:23,954] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1368)
[2021-12-29 12:10:23,956] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1302)
[2021-12-29 12:10:23,958] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getByName(InetAddress.java:1252)
[2021-12-29 12:10:23,959] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156)
[2021-12-29 12:10:23,960] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153)
[2021-12-29 12:10:23,962] {spark_submit.py:514} INFO - at java.base/java.security.AccessController.doPrivileged(Native Method)
[2021-12-29 12:10:23,963] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153)
[2021-12-29 12:10:23,964] {spark_submit.py:514} INFO - at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41)
[2021-12-29 12:10:23,966] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
[2021-12-29 12:10:23,968] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53)
[2021-12-29 12:10:23,970] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
[2021-12-29 12:10:23,978] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
[2021-12-29 12:10:23,982] {spark_submit.py:514} INFO - at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
[2021-12-29 12:10:23,985] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:206)
[2021-12-29 12:10:23,986] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46)
[2021-12-29 12:10:23,988] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:180)
[2021-12-29 12:10:23,991] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:166)
[2021-12-29 12:10:23,992] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
[2021-12-29 12:10:23,994] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
[2021-12-29 12:10:23,996] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
[2021-12-29 12:10:23,997] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
[2021-12-29 12:10:23,999] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
[2021-12-29 12:10:24,002] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
[2021-12-29 12:10:24,004] {spark_submit.py:514} INFO - at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
[2021-12-29 12:10:24,008] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:1008)
[2021-12-29 12:10:24,013] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:516)
[2021-12-29 12:10:24,019] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
[2021-12-29 12:10:24,027] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
[2021-12-29 12:10:24,029] {spark_submit.py:514} INFO - at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[2021-12-29 12:10:24,030] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
[2021-12-29 12:10:24,031] {spark_submit.py:514} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[2021-12-29 12:10:24,032] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[2021-12-29 12:10:24,035] {spark_submit.py:514} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2021-12-29 12:10:24,036] {spark_submit.py:514} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2021-12-29 12:10:24,037] {spark_submit.py:514} INFO - ... 1 more
[2021-12-29 12:10:42,865] {spark_submit.py:514} INFO - 21/12/29 12:10:42 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2021-12-29 12:10:42,884] {spark_submit.py:514} INFO - 21/12/29 12:10:42 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master spark:7077
[2021-12-29 12:10:42,886] {spark_submit.py:514} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2021-12-29 12:10:42,887] {spark_submit.py:514} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:301)
[2021-12-29 12:10:42,887] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2021-12-29 12:10:42,888] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:101)
[2021-12-29 12:10:42,889] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:109)
[2021-12-29 12:10:42,890] {spark_submit.py:514} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:107)
[2021-12-29 12:10:42,891] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2021-12-29 12:10:42,891] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2021-12-29 12:10:42,892] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2021-12-29 12:10:42,893] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2021-12-29 12:10:42,895] {spark_submit.py:514} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-29 12:10:42,896] {spark_submit.py:514} INFO - Caused by: java.io.IOException: Failed to connect to spark:7077
[2021-12-29 12:10:42,897] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:288)
[2021-12-29 12:10:42,897] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:218)
[2021-12-29 12:10:42,898] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:230)
[2021-12-29 12:10:42,899] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2021-12-29 12:10:42,900] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2021-12-29 12:10:42,901] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2021-12-29 12:10:42,901] {spark_submit.py:514} INFO - ... 4 more
[2021-12-29 12:10:42,902] {spark_submit.py:514} INFO - Caused by: java.net.UnknownHostException: spark
[2021-12-29 12:10:42,903] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
[2021-12-29 12:10:42,904] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509)
[2021-12-29 12:10:42,904] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1368)
[2021-12-29 12:10:42,905] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1302)
[2021-12-29 12:10:42,906] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getByName(InetAddress.java:1252)
[2021-12-29 12:10:42,906] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156)
[2021-12-29 12:10:42,907] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153)
[2021-12-29 12:10:42,908] {spark_submit.py:514} INFO - at java.base/java.security.AccessController.doPrivileged(Native Method)
[2021-12-29 12:10:42,908] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153)
[2021-12-29 12:10:42,909] {spark_submit.py:514} INFO - at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41)
[2021-12-29 12:10:42,910] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
[2021-12-29 12:10:42,910] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53)
[2021-12-29 12:10:42,911] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
[2021-12-29 12:10:42,912] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
[2021-12-29 12:10:42,912] {spark_submit.py:514} INFO - at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
[2021-12-29 12:10:42,913] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:206)
[2021-12-29 12:10:42,914] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46)
[2021-12-29 12:10:42,914] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:180)
[2021-12-29 12:10:42,915] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:166)
[2021-12-29 12:10:42,916] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
[2021-12-29 12:10:42,917] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
[2021-12-29 12:10:42,918] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
[2021-12-29 12:10:42,918] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
[2021-12-29 12:10:42,919] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
[2021-12-29 12:10:42,920] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
[2021-12-29 12:10:42,920] {spark_submit.py:514} INFO - at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
[2021-12-29 12:10:42,921] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:1008)
[2021-12-29 12:10:42,922] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:516)
[2021-12-29 12:10:42,922] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
[2021-12-29 12:10:42,923] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
[2021-12-29 12:10:42,924] {spark_submit.py:514} INFO - at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[2021-12-29 12:10:42,924] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
[2021-12-29 12:10:42,925] {spark_submit.py:514} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[2021-12-29 12:10:42,925] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[2021-12-29 12:10:42,926] {spark_submit.py:514} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2021-12-29 12:10:42,927] {spark_submit.py:514} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2021-12-29 12:10:42,927] {spark_submit.py:514} INFO - ... 1 more
[2021-12-29 12:11:02,865] {spark_submit.py:514} INFO - 21/12/29 12:11:02 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2021-12-29 12:11:02,881] {spark_submit.py:514} INFO - 21/12/29 12:11:02 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master spark:7077
[2021-12-29 12:11:02,882] {spark_submit.py:514} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2021-12-29 12:11:02,882] {spark_submit.py:514} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:301)
[2021-12-29 12:11:02,883] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2021-12-29 12:11:02,884] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:101)
[2021-12-29 12:11:02,885] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:109)
[2021-12-29 12:11:02,885] {spark_submit.py:514} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:107)
[2021-12-29 12:11:02,886] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2021-12-29 12:11:02,887] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2021-12-29 12:11:02,888] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2021-12-29 12:11:02,889] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2021-12-29 12:11:02,889] {spark_submit.py:514} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-29 12:11:02,890] {spark_submit.py:514} INFO - Caused by: java.io.IOException: Failed to connect to spark:7077
[2021-12-29 12:11:02,891] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:288)
[2021-12-29 12:11:02,893] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:218)
[2021-12-29 12:11:02,894] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:230)
[2021-12-29 12:11:02,895] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2021-12-29 12:11:02,896] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2021-12-29 12:11:02,897] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2021-12-29 12:11:02,898] {spark_submit.py:514} INFO - ... 4 more
[2021-12-29 12:11:02,899] {spark_submit.py:514} INFO - Caused by: java.net.UnknownHostException: spark
[2021-12-29 12:11:02,900] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
[2021-12-29 12:11:02,901] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509)
[2021-12-29 12:11:02,902] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1368)
[2021-12-29 12:11:02,903] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1302)
[2021-12-29 12:11:02,903] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getByName(InetAddress.java:1252)
[2021-12-29 12:11:02,904] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156)
[2021-12-29 12:11:02,905] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153)
[2021-12-29 12:11:02,906] {spark_submit.py:514} INFO - at java.base/java.security.AccessController.doPrivileged(Native Method)
[2021-12-29 12:11:02,907] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153)
[2021-12-29 12:11:02,908] {spark_submit.py:514} INFO - at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41)
[2021-12-29 12:11:02,909] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
[2021-12-29 12:11:02,909] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53)
[2021-12-29 12:11:02,910] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
[2021-12-29 12:11:02,911] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
[2021-12-29 12:11:02,912] {spark_submit.py:514} INFO - at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
[2021-12-29 12:11:02,913] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:206)
[2021-12-29 12:11:02,914] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46)
[2021-12-29 12:11:02,915] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:180)
[2021-12-29 12:11:02,916] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:166)
[2021-12-29 12:11:02,917] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
[2021-12-29 12:11:02,917] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
[2021-12-29 12:11:02,919] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
[2021-12-29 12:11:02,919] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
[2021-12-29 12:11:02,920] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
[2021-12-29 12:11:02,922] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
[2021-12-29 12:11:02,923] {spark_submit.py:514} INFO - at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
[2021-12-29 12:11:02,924] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:1008)
[2021-12-29 12:11:02,925] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:516)
[2021-12-29 12:11:02,926] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
[2021-12-29 12:11:02,927] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
[2021-12-29 12:11:02,928] {spark_submit.py:514} INFO - at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[2021-12-29 12:11:02,929] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
[2021-12-29 12:11:02,930] {spark_submit.py:514} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[2021-12-29 12:11:02,931] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[2021-12-29 12:11:02,932] {spark_submit.py:514} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2021-12-29 12:11:02,933] {spark_submit.py:514} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2021-12-29 12:11:02,934] {spark_submit.py:514} INFO - ... 1 more
[2021-12-29 12:11:22,840] {spark_submit.py:514} INFO - 21/12/29 12:11:22 ERROR StandaloneSchedulerBackend: Application has been killed. Reason: All masters are unresponsive! Giving up.
[2021-12-29 12:11:22,842] {spark_submit.py:514} INFO - 21/12/29 12:11:22 WARN StandaloneSchedulerBackend: Application ID is not initialized yet.
[2021-12-29 12:11:22,854] {spark_submit.py:514} INFO - 21/12/29 12:11:22 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 35329.
[2021-12-29 12:11:22,855] {spark_submit.py:514} INFO - 21/12/29 12:11:22 INFO NettyBlockTransferService: Server created on 6bdda4c19a85:35329
[2021-12-29 12:11:22,857] {spark_submit.py:514} INFO - 21/12/29 12:11:22 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2021-12-29 12:11:22,874] {spark_submit.py:514} INFO - 21/12/29 12:11:22 INFO SparkUI: Stopped Spark web UI at http://6bdda4c19a85:4040
[2021-12-29 12:11:22,875] {spark_submit.py:514} INFO - 21/12/29 12:11:22 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 6bdda4c19a85, 35329, None)
[2021-12-29 12:11:22,880] {spark_submit.py:514} INFO - 21/12/29 12:11:22 INFO BlockManagerMasterEndpoint: Registering block manager 6bdda4c19a85:35329 with 434.4 MiB RAM, BlockManagerId(driver, 6bdda4c19a85, 35329, None)
[2021-12-29 12:11:22,884] {spark_submit.py:514} INFO - 21/12/29 12:11:22 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 6bdda4c19a85, 35329, None)
[2021-12-29 12:11:22,889] {spark_submit.py:514} INFO - 21/12/29 12:11:22 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 6bdda4c19a85, 35329, None)
[2021-12-29 12:11:22,890] {spark_submit.py:514} INFO - 21/12/29 12:11:22 INFO StandaloneSchedulerBackend: Shutting down all executors
[2021-12-29 12:11:22,896] {spark_submit.py:514} INFO - 21/12/29 12:11:22 INFO CoarseGrainedSchedulerBackend$DriverEndpoint: Asking each executor to shut down
[2021-12-29 12:11:22,905] {spark_submit.py:514} INFO - 21/12/29 12:11:22 WARN StandaloneAppClient$ClientEndpoint: Drop UnregisterApplication(null) because has not yet connected to master
[2021-12-29 12:11:22,924] {spark_submit.py:514} INFO - 21/12/29 12:11:22 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2021-12-29 12:11:22,946] {spark_submit.py:514} INFO - 21/12/29 12:11:22 INFO MemoryStore: MemoryStore cleared
[2021-12-29 12:11:22,947] {spark_submit.py:514} INFO - 21/12/29 12:11:22 INFO BlockManager: BlockManager stopped
[2021-12-29 12:11:22,959] {spark_submit.py:514} INFO - 21/12/29 12:11:22 INFO BlockManagerMaster: BlockManagerMaster stopped
[2021-12-29 12:11:22,963] {spark_submit.py:514} INFO - 21/12/29 12:11:22 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2021-12-29 12:11:22,978] {spark_submit.py:514} INFO - 21/12/29 12:11:22 INFO SparkContext: Successfully stopped SparkContext
[2021-12-29 12:11:23,109] {spark_submit.py:514} INFO - 21/12/29 12:11:23 ERROR SparkContext: Error initializing SparkContext.
[2021-12-29 12:11:23,110] {spark_submit.py:514} INFO - java.lang.IllegalArgumentException: requirement failed: Can only call getServletHandlers on a running MetricsSystem
[2021-12-29 12:11:23,112] {spark_submit.py:514} INFO - at scala.Predef$.require(Predef.scala:281)
[2021-12-29 12:11:23,112] {spark_submit.py:514} INFO - at org.apache.spark.metrics.MetricsSystem.getServletHandlers(MetricsSystem.scala:89)
[2021-12-29 12:11:23,113] {spark_submit.py:514} INFO - at org.apache.spark.SparkContext.<init>(SparkContext.scala:603)
[2021-12-29 12:11:23,114] {spark_submit.py:514} INFO - at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2021-12-29 12:11:23,115] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2021-12-29 12:11:23,116] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2021-12-29 12:11:23,117] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2021-12-29 12:11:23,118] {spark_submit.py:514} INFO - at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[2021-12-29 12:11:23,119] {spark_submit.py:514} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2021-12-29 12:11:23,120] {spark_submit.py:514} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2021-12-29 12:11:23,121] {spark_submit.py:514} INFO - at py4j.Gateway.invoke(Gateway.java:238)
[2021-12-29 12:11:23,122] {spark_submit.py:514} INFO - at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2021-12-29 12:11:23,123] {spark_submit.py:514} INFO - at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2021-12-29 12:11:23,124] {spark_submit.py:514} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2021-12-29 12:11:23,125] {spark_submit.py:514} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2021-12-29 12:11:23,126] {spark_submit.py:514} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-29 12:11:23,127] {spark_submit.py:514} INFO - 21/12/29 12:11:23 INFO SparkContext: SparkContext already stopped.
[2021-12-29 12:11:23,128] {spark_submit.py:514} INFO - Traceback (most recent call last):
[2021-12-29 12:11:23,128] {spark_submit.py:514} INFO - File "/opt/***/jobs/persist_db.py", line 52, in <module>
[2021-12-29 12:11:23,129] {spark_submit.py:514} INFO - .config("spark.driver.bindAddress", "localhost") \
[2021-12-29 12:11:23,130] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/session.py", line 228, in getOrCreate
[2021-12-29 12:11:23,131] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 392, in getOrCreate
[2021-12-29 12:11:23,132] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 147, in __init__
[2021-12-29 12:11:23,133] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 209, in _do_init
[2021-12-29 12:11:23,135] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 329, in _initialize_context
[2021-12-29 12:11:23,136] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/py4j-0.10.9.2-src.zip/py4j/java_gateway.py", line 1574, in __call__
[2021-12-29 12:11:23,136] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/py4j-0.10.9.2-src.zip/py4j/protocol.py", line 328, in get_return_value
[2021-12-29 12:11:23,137] {spark_submit.py:514} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling None.org.apache.spark.api.java.JavaSparkContext.
[2021-12-29 12:11:23,138] {spark_submit.py:514} INFO - : java.lang.IllegalArgumentException: requirement failed: Can only call getServletHandlers on a running MetricsSystem
[2021-12-29 12:11:23,139] {spark_submit.py:514} INFO - at scala.Predef$.require(Predef.scala:281)
[2021-12-29 12:11:23,139] {spark_submit.py:514} INFO - at org.apache.spark.metrics.MetricsSystem.getServletHandlers(MetricsSystem.scala:89)
[2021-12-29 12:11:23,140] {spark_submit.py:514} INFO - at org.apache.spark.SparkContext.<init>(SparkContext.scala:603)
[2021-12-29 12:11:23,141] {spark_submit.py:514} INFO - at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2021-12-29 12:11:23,142] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2021-12-29 12:11:23,143] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2021-12-29 12:11:23,143] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2021-12-29 12:11:23,144] {spark_submit.py:514} INFO - at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[2021-12-29 12:11:23,145] {spark_submit.py:514} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2021-12-29 12:11:23,145] {spark_submit.py:514} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2021-12-29 12:11:23,146] {spark_submit.py:514} INFO - at py4j.Gateway.invoke(Gateway.java:238)
[2021-12-29 12:11:23,147] {spark_submit.py:514} INFO - at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2021-12-29 12:11:23,148] {spark_submit.py:514} INFO - at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2021-12-29 12:11:23,149] {spark_submit.py:514} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2021-12-29 12:11:23,150] {spark_submit.py:514} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2021-12-29 12:11:23,150] {spark_submit.py:514} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-29 12:11:23,151] {spark_submit.py:514} INFO - 
[2021-12-29 12:11:23,251] {spark_submit.py:514} INFO - 21/12/29 12:11:23 INFO ShutdownHookManager: Shutdown hook called
[2021-12-29 12:11:23,252] {spark_submit.py:514} INFO - 21/12/29 12:11:23 INFO ShutdownHookManager: Deleting directory /tmp/spark-ff4dac16-3db5-40b7-9316-20ea125e628d
[2021-12-29 12:11:23,258] {spark_submit.py:514} INFO - 21/12/29 12:11:23 INFO ShutdownHookManager: Deleting directory /tmp/spark-1549d767-9b02-46cf-81f1-e0168da30902
[2021-12-29 12:11:23,696] {taskinstance.py:1703} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 179, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 446, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark:7077 --conf spark.master=spark://spark:7077 --name persist data --verbose /opt/***/jobs/persist_db.py clare. Error code is: 1.
[2021-12-29 12:11:23,706] {taskinstance.py:1280} INFO - Marking task as UP_FOR_RETRY. dag_id=scraping_daft_clare, task_id=persist_data, execution_date=20211228T091500, start_date=20211229T121001, end_date=20211229T121123
[2021-12-29 12:11:23,733] {standard_task_runner.py:91} ERROR - Failed to execute job 5370 for task persist_data
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 179, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 446, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark:7077 --conf spark.master=spark://spark:7077 --name persist data --verbose /opt/***/jobs/persist_db.py clare. Error code is: 1.
[2021-12-29 12:11:23,771] {local_task_job.py:154} INFO - Task exited with return code 1
[2021-12-29 12:11:23,880] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
