[2021-12-20 10:40:58,765] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: scraping_daft_kilkenny.scrap_data scheduled__2021-12-19T09:50:00+00:00 [queued]>
[2021-12-20 10:40:59,937] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: scraping_daft_kilkenny.scrap_data scheduled__2021-12-19T09:50:00+00:00 [queued]>
[2021-12-20 10:40:59,970] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-20 10:40:59,982] {taskinstance.py:1242} INFO - Starting attempt 4 of 4
[2021-12-20 10:41:00,001] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-20 10:41:00,867] {taskinstance.py:1262} INFO - Executing <Task(SparkSubmitOperator): scrap_data> on 2021-12-19 09:50:00+00:00
[2021-12-20 10:41:02,054] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'scraping_daft_kilkenny', 'scrap_data', 'scheduled__2021-12-19T09:50:00+00:00', '--job-id', '3422', '--raw', '--subdir', 'DAGS_FOLDER/scraping_daft_kilkenny.py', '--cfg-path', '/tmp/tmpf61ks4g2', '--error-file', '/tmp/tmpf20d8grc']
[2021-12-20 10:41:02,096] {standard_task_runner.py:77} INFO - Job 3422: Subtask scrap_data
[2021-12-20 10:41:01,936] {standard_task_runner.py:52} INFO - Started process 4545 to run task
[2021-12-20 10:41:06,089] {logging_mixin.py:109} INFO - Running <TaskInstance: scraping_daft_kilkenny.scrap_data scheduled__2021-12-19T09:50:00+00:00 [running]> on host a35fe600e898
[2021-12-20 10:41:15,871] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=clement.liscoet@gmail.com
AIRFLOW_CTX_DAG_OWNER=clemoni
AIRFLOW_CTX_DAG_ID=scraping_daft_kilkenny
AIRFLOW_CTX_TASK_ID=scrap_data
AIRFLOW_CTX_EXECUTION_DATE=2021-12-19T09:50:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-19T09:50:00+00:00
[2021-12-20 10:41:16,229] {base.py:79} INFO - Using connection to: id: spark_default. Host: spark://spark:7077, Port: None, Schema: , Login: ***, Password: ***, extra: {}
[2021-12-20 10:41:16,240] {spark_submit.py:360} INFO - Spark-Submit cmd: spark-submit --master spark://spark:7077 --conf spark.master=spark://spark:7077 --name scrap data --verbose /opt/***/jobs/get_ads_per_county.py kilkenny
[2021-12-20 11:09:07,225] {local_task_job.py:142} ERROR - Heartbeat time limit exceeded!
[2021-12-20 11:09:07,892] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 4545
[2021-12-20 11:09:07,920] {taskinstance.py:1411} ERROR - Received SIGTERM. Terminating subprocesses.
[2021-12-20 11:09:07,930] {spark_submit.py:644} INFO - Sending kill signal to spark-submit
[2021-12-20 11:09:13,495] {taskinstance.py:1703} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 179, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 433, in submit
    self._process_spark_submit_log(iter(self._submit_sp.stdout))  # type: ignore
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 482, in _process_spark_submit_log
    for line in itr:
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1413, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2021-12-20 11:09:14,145] {taskinstance.py:1280} INFO - Marking task as FAILED. dag_id=scraping_daft_kilkenny, task_id=scrap_data, execution_date=20211219T095000, start_date=20211220T104058, end_date=20211220T110914
[2021-12-20 11:09:15,842] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/email.py:102: PendingDeprecationWarning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=smtp_mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2021-12-20 11:09:15,950] {email.py:208} INFO - Email alerting: attempt 1
[2021-12-20 11:09:17,102] {email.py:220} INFO - Sent an alert email to ['clement.liscoet@gmail.com']
[2021-12-20 11:09:20,560] {standard_task_runner.py:91} ERROR - Failed to execute job 3422 for task scrap_data
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 179, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 433, in submit
    self._process_spark_submit_log(iter(self._submit_sp.stdout))  # type: ignore
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 482, in _process_spark_submit_log
    for line in itr:
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1413, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2021-12-20 11:09:22,632] {process_utils.py:66} INFO - Process psutil.Process(pid=4580, status='terminated', started='10:41:15') (4580) terminated with exit code None
[2021-12-20 11:09:22,654] {process_utils.py:66} INFO - Process psutil.Process(pid=4545, status='terminated', exitcode=1, started='10:41:01') (4545) terminated with exit code 1
