[2021-12-28 13:33:30,378] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: scraping_daft_tipperary.scrap_data scheduled__2021-12-27T10:50:00+00:00 [queued]>
[2021-12-28 13:33:30,455] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: scraping_daft_tipperary.scrap_data scheduled__2021-12-27T10:50:00+00:00 [queued]>
[2021-12-28 13:33:30,456] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-28 13:33:30,457] {taskinstance.py:1242} INFO - Starting attempt 2 of 4
[2021-12-28 13:33:30,458] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-28 13:33:30,627] {taskinstance.py:1262} INFO - Executing <Task(SparkSubmitOperator): scrap_data> on 2021-12-27 10:50:00+00:00
[2021-12-28 13:33:30,660] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'scraping_daft_tipperary', 'scrap_data', 'scheduled__2021-12-27T10:50:00+00:00', '--job-id', '5080', '--raw', '--subdir', 'DAGS_FOLDER/scraping_daft_tipperary.py', '--cfg-path', '/tmp/tmpvu_so_n8', '--error-file', '/tmp/tmp0c0g4vo9']
[2021-12-28 13:33:30,670] {standard_task_runner.py:77} INFO - Job 5080: Subtask scrap_data
[2021-12-28 13:33:30,641] {standard_task_runner.py:52} INFO - Started process 49173 to run task
[2021-12-28 13:33:30,918] {logging_mixin.py:109} INFO - Running <TaskInstance: scraping_daft_tipperary.scrap_data scheduled__2021-12-27T10:50:00+00:00 [running]> on host 0c125a5bba95
[2021-12-28 13:33:31,621] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=clement.liscoet@gmail.com
AIRFLOW_CTX_DAG_OWNER=clemoni
AIRFLOW_CTX_DAG_ID=scraping_daft_tipperary
AIRFLOW_CTX_TASK_ID=scrap_data
AIRFLOW_CTX_EXECUTION_DATE=2021-12-27T10:50:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-27T10:50:00+00:00
[2021-12-28 13:33:31,774] {base.py:79} INFO - Using connection to: id: spark_default. Host: spark://spark:7077, Port: None, Schema: , Login: ***, Password: ***, extra: {}
[2021-12-28 13:33:31,795] {spark_submit.py:360} INFO - Spark-Submit cmd: spark-submit --master spark://spark:7077 --conf spark.master=spark://spark:7077 --name scrap data --verbose /opt/***/jobs/get_ads_per_county.py tipperary
[2021-12-28 13:33:43,357] {spark_submit.py:514} INFO - Using properties file: null
[2021-12-28 13:33:44,471] {spark_submit.py:514} INFO - WARNING: An illegal reflective access operation has occurred
[2021-12-28 13:33:44,473] {spark_submit.py:514} INFO - WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/home/***/.local/lib/python3.6/site-packages/pyspark/jars/spark-unsafe_2.12-3.2.0.jar) to constructor java.nio.DirectByteBuffer(long,int)
[2021-12-28 13:33:44,478] {spark_submit.py:514} INFO - WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
[2021-12-28 13:33:44,485] {spark_submit.py:514} INFO - WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[2021-12-28 13:33:44,488] {spark_submit.py:514} INFO - WARNING: All illegal access operations will be denied in a future release
[2021-12-28 13:33:45,155] {spark_submit.py:514} INFO - Parsed arguments:
[2021-12-28 13:33:45,157] {spark_submit.py:514} INFO - master                  spark://spark:7077
[2021-12-28 13:33:45,158] {spark_submit.py:514} INFO - deployMode              null
[2021-12-28 13:33:45,159] {spark_submit.py:514} INFO - executorMemory          null
[2021-12-28 13:33:45,160] {spark_submit.py:514} INFO - executorCores           null
[2021-12-28 13:33:45,161] {spark_submit.py:514} INFO - totalExecutorCores      null
[2021-12-28 13:33:45,162] {spark_submit.py:514} INFO - propertiesFile          null
[2021-12-28 13:33:45,163] {spark_submit.py:514} INFO - driverMemory            null
[2021-12-28 13:33:45,164] {spark_submit.py:514} INFO - driverCores             null
[2021-12-28 13:33:45,165] {spark_submit.py:514} INFO - driverExtraClassPath    null
[2021-12-28 13:33:45,166] {spark_submit.py:514} INFO - driverExtraLibraryPath  null
[2021-12-28 13:33:45,168] {spark_submit.py:514} INFO - driverExtraJavaOptions  null
[2021-12-28 13:33:45,169] {spark_submit.py:514} INFO - supervise               false
[2021-12-28 13:33:45,170] {spark_submit.py:514} INFO - queue                   null
[2021-12-28 13:33:45,171] {spark_submit.py:514} INFO - numExecutors            null
[2021-12-28 13:33:45,172] {spark_submit.py:514} INFO - files                   null
[2021-12-28 13:33:45,173] {spark_submit.py:514} INFO - pyFiles                 null
[2021-12-28 13:33:45,175] {spark_submit.py:514} INFO - archives                null
[2021-12-28 13:33:45,177] {spark_submit.py:514} INFO - mainClass               null
[2021-12-28 13:33:45,178] {spark_submit.py:514} INFO - primaryResource         file:/opt/***/jobs/get_ads_per_county.py
[2021-12-28 13:33:45,179] {spark_submit.py:514} INFO - name                    scrap data
[2021-12-28 13:33:45,180] {spark_submit.py:514} INFO - childArgs               [tipperary]
[2021-12-28 13:33:45,183] {spark_submit.py:514} INFO - jars                    null
[2021-12-28 13:33:45,184] {spark_submit.py:514} INFO - packages                null
[2021-12-28 13:33:45,185] {spark_submit.py:514} INFO - packagesExclusions      null
[2021-12-28 13:33:45,186] {spark_submit.py:514} INFO - repositories            null
[2021-12-28 13:33:45,187] {spark_submit.py:514} INFO - verbose                 true
[2021-12-28 13:33:45,189] {spark_submit.py:514} INFO - 
[2021-12-28 13:33:45,190] {spark_submit.py:514} INFO - Spark properties used, including those specified through
[2021-12-28 13:33:45,191] {spark_submit.py:514} INFO - --conf and those from the properties file null:
[2021-12-28 13:33:45,192] {spark_submit.py:514} INFO - (spark.master,spark://spark:7077)
[2021-12-28 13:33:45,193] {spark_submit.py:514} INFO - 
[2021-12-28 13:33:45,194] {spark_submit.py:514} INFO - 
[2021-12-28 13:33:48,327] {spark_submit.py:514} INFO - Main class:
[2021-12-28 13:33:48,330] {spark_submit.py:514} INFO - org.apache.spark.deploy.PythonRunner
[2021-12-28 13:33:48,333] {spark_submit.py:514} INFO - Arguments:
[2021-12-28 13:33:48,336] {spark_submit.py:514} INFO - file:/opt/***/jobs/get_ads_per_county.py
[2021-12-28 13:33:48,338] {spark_submit.py:514} INFO - null
[2021-12-28 13:33:48,339] {spark_submit.py:514} INFO - tipperary
[2021-12-28 13:33:48,340] {spark_submit.py:514} INFO - --verbose
[2021-12-28 13:33:48,348] {spark_submit.py:514} INFO - Spark config:
[2021-12-28 13:33:48,350] {spark_submit.py:514} INFO - (spark.app.name,scrap data)
[2021-12-28 13:33:48,350] {spark_submit.py:514} INFO - (spark.master,spark://spark:7077)
[2021-12-28 13:33:48,351] {spark_submit.py:514} INFO - (spark.submit.pyFiles,)
[2021-12-28 13:33:48,352] {spark_submit.py:514} INFO - (spark.submit.deployMode,client)
[2021-12-28 13:33:48,353] {spark_submit.py:514} INFO - Classpath elements:
[2021-12-28 13:33:48,354] {spark_submit.py:514} INFO - 
[2021-12-28 13:33:48,355] {spark_submit.py:514} INFO - 
[2021-12-28 13:33:48,356] {spark_submit.py:514} INFO - 
[2021-12-28 13:34:08,801] {spark_submit.py:514} INFO - Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
[2021-12-28 13:34:11,618] {spark_submit.py:514} INFO - 21/12/28 13:34:11 INFO SparkContext: Running Spark version 3.2.0
[2021-12-28 13:34:15,964] {spark_submit.py:514} INFO - 21/12/28 13:34:15 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2021-12-28 13:34:37,788] {spark_submit.py:514} INFO - 21/12/28 13:34:37 INFO ResourceUtils: ==============================================================
[2021-12-28 13:34:37,800] {spark_submit.py:514} INFO - 21/12/28 13:34:37 INFO ResourceUtils: No custom resources configured for spark.driver.
[2021-12-28 13:34:37,803] {spark_submit.py:514} INFO - 21/12/28 13:34:37 INFO ResourceUtils: ==============================================================
[2021-12-28 13:34:37,808] {spark_submit.py:514} INFO - 21/12/28 13:34:37 INFO SparkContext: Submitted application: Get Ads per county
[2021-12-28 13:34:38,187] {spark_submit.py:514} INFO - 21/12/28 13:34:38 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2021-12-28 13:34:38,706] {spark_submit.py:514} INFO - 21/12/28 13:34:38 INFO ResourceProfile: Limiting resource is cpu
[2021-12-28 13:34:38,708] {spark_submit.py:514} INFO - 21/12/28 13:34:38 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2021-12-28 13:34:45,079] {spark_submit.py:514} INFO - 21/12/28 13:34:45 INFO SecurityManager: Changing view acls to: ***
[2021-12-28 13:34:45,262] {spark_submit.py:514} INFO - 21/12/28 13:34:45 INFO SecurityManager: Changing modify acls to: ***
[2021-12-28 13:34:45,412] {spark_submit.py:514} INFO - 21/12/28 13:34:45 INFO SecurityManager: Changing view acls groups to:
[2021-12-28 13:34:45,684] {spark_submit.py:514} INFO - 21/12/28 13:34:45 INFO SecurityManager: Changing modify acls groups to:
[2021-12-28 13:34:45,701] {spark_submit.py:514} INFO - 21/12/28 13:34:45 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(***); groups with view permissions: Set(); users  with modify permissions: Set(***); groups with modify permissions: Set()
[2021-12-28 13:35:03,343] {spark_submit.py:514} INFO - 21/12/28 13:35:03 INFO Utils: Successfully started service 'sparkDriver' on port 34723.
[2021-12-28 13:35:04,798] {spark_submit.py:514} INFO - 21/12/28 13:35:04 INFO SparkEnv: Registering MapOutputTracker
[2021-12-28 13:35:06,154] {spark_submit.py:514} INFO - 21/12/28 13:35:06 INFO SparkEnv: Registering BlockManagerMaster
[2021-12-28 13:35:06,706] {spark_submit.py:514} INFO - 21/12/28 13:35:06 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2021-12-28 13:35:06,709] {spark_submit.py:514} INFO - 21/12/28 13:35:06 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2021-12-28 13:35:06,876] {spark_submit.py:514} INFO - 21/12/28 13:35:06 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2021-12-28 13:35:07,787] {spark_submit.py:514} INFO - 21/12/28 13:35:07 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-e16f0f17-c1f2-4a00-ac1e-4636de95c9e4
[2021-12-28 13:35:16,105] {spark_submit.py:514} INFO - 21/12/28 13:35:16 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2021-12-28 13:35:16,559] {spark_submit.py:514} INFO - 21/12/28 13:35:16 INFO SparkEnv: Registering OutputCommitCoordinator
[2021-12-28 13:35:22,292] {spark_submit.py:514} INFO - 21/12/28 13:35:22 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2021-12-28 13:35:22,295] {spark_submit.py:514} INFO - 21/12/28 13:35:22 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.
[2021-12-28 13:35:22,321] {spark_submit.py:514} INFO - 21/12/28 13:35:22 WARN Utils: Service 'SparkUI' could not bind on port 4042. Attempting port 4043.
[2021-12-28 13:35:22,343] {spark_submit.py:514} INFO - 21/12/28 13:35:22 WARN Utils: Service 'SparkUI' could not bind on port 4043. Attempting port 4044.
[2021-12-28 13:35:22,353] {spark_submit.py:514} INFO - 21/12/28 13:35:22 WARN Utils: Service 'SparkUI' could not bind on port 4044. Attempting port 4045.
[2021-12-28 13:35:22,361] {spark_submit.py:514} INFO - 21/12/28 13:35:22 WARN Utils: Service 'SparkUI' could not bind on port 4045. Attempting port 4046.
[2021-12-28 13:35:22,368] {spark_submit.py:514} INFO - 21/12/28 13:35:22 WARN Utils: Service 'SparkUI' could not bind on port 4046. Attempting port 4047.
[2021-12-28 13:35:22,370] {spark_submit.py:514} INFO - 21/12/28 13:35:22 WARN Utils: Service 'SparkUI' could not bind on port 4047. Attempting port 4048.
[2021-12-28 13:35:22,371] {spark_submit.py:514} INFO - 21/12/28 13:35:22 WARN Utils: Service 'SparkUI' could not bind on port 4048. Attempting port 4049.
[2021-12-28 13:35:22,373] {spark_submit.py:514} INFO - 21/12/28 13:35:22 WARN Utils: Service 'SparkUI' could not bind on port 4049. Attempting port 4050.
[2021-12-28 13:35:22,376] {spark_submit.py:514} INFO - 21/12/28 13:35:22 WARN Utils: Service 'SparkUI' could not bind on port 4050. Attempting port 4051.
[2021-12-28 13:35:22,377] {spark_submit.py:514} INFO - 21/12/28 13:35:22 WARN Utils: Service 'SparkUI' could not bind on port 4051. Attempting port 4052.
[2021-12-28 13:35:22,519] {spark_submit.py:514} INFO - 21/12/28 13:35:22 INFO Utils: Successfully started service 'SparkUI' on port 4052.
[2021-12-28 13:35:24,952] {spark_submit.py:514} INFO - 21/12/28 13:35:24 INFO SparkUI: Bound SparkUI to 0.0.0.0, and started at http://0c125a5bba95:4052
[2021-12-28 13:35:54,252] {spark_submit.py:514} INFO - 21/12/28 13:35:54 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2021-12-28 13:35:58,315] {spark_submit.py:514} INFO - 21/12/28 13:35:57 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master spark:7077
[2021-12-28 13:35:58,325] {spark_submit.py:514} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2021-12-28 13:35:58,327] {spark_submit.py:514} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:301)
[2021-12-28 13:35:58,328] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2021-12-28 13:35:58,329] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:101)
[2021-12-28 13:35:58,336] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:109)
[2021-12-28 13:35:58,338] {spark_submit.py:514} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:107)
[2021-12-28 13:35:58,340] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2021-12-28 13:35:58,341] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2021-12-28 13:35:58,343] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2021-12-28 13:35:58,344] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2021-12-28 13:35:58,348] {spark_submit.py:514} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-28 13:35:58,349] {spark_submit.py:514} INFO - Caused by: java.io.IOException: Failed to connect to spark:7077
[2021-12-28 13:35:58,350] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:288)
[2021-12-28 13:35:58,351] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:218)
[2021-12-28 13:35:58,352] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:230)
[2021-12-28 13:35:58,353] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2021-12-28 13:35:58,354] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2021-12-28 13:35:58,356] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2021-12-28 13:35:58,357] {spark_submit.py:514} INFO - ... 4 more
[2021-12-28 13:35:58,359] {spark_submit.py:514} INFO - Caused by: java.net.UnknownHostException: spark
[2021-12-28 13:35:58,360] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
[2021-12-28 13:35:58,361] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509)
[2021-12-28 13:35:58,362] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1368)
[2021-12-28 13:35:58,364] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1302)
[2021-12-28 13:35:58,366] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getByName(InetAddress.java:1252)
[2021-12-28 13:35:58,368] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156)
[2021-12-28 13:35:58,370] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153)
[2021-12-28 13:35:58,372] {spark_submit.py:514} INFO - at java.base/java.security.AccessController.doPrivileged(Native Method)
[2021-12-28 13:35:58,373] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153)
[2021-12-28 13:35:58,375] {spark_submit.py:514} INFO - at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41)
[2021-12-28 13:35:58,376] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
[2021-12-28 13:35:58,377] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53)
[2021-12-28 13:35:58,379] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
[2021-12-28 13:35:58,380] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
[2021-12-28 13:35:58,381] {spark_submit.py:514} INFO - at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
[2021-12-28 13:35:58,382] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:206)
[2021-12-28 13:35:58,383] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46)
[2021-12-28 13:35:58,384] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:180)
[2021-12-28 13:35:58,385] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:166)
[2021-12-28 13:35:58,387] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
[2021-12-28 13:35:58,388] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
[2021-12-28 13:35:58,389] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
[2021-12-28 13:35:58,390] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
[2021-12-28 13:35:58,391] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
[2021-12-28 13:35:58,392] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
[2021-12-28 13:35:58,393] {spark_submit.py:514} INFO - at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
[2021-12-28 13:35:58,394] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:1008)
[2021-12-28 13:35:58,395] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:516)
[2021-12-28 13:35:58,397] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
[2021-12-28 13:35:58,398] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
[2021-12-28 13:35:58,399] {spark_submit.py:514} INFO - at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[2021-12-28 13:35:58,401] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
[2021-12-28 13:35:58,402] {spark_submit.py:514} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[2021-12-28 13:35:58,403] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[2021-12-28 13:35:58,405] {spark_submit.py:514} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2021-12-28 13:35:58,406] {spark_submit.py:514} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2021-12-28 13:35:58,407] {spark_submit.py:514} INFO - ... 1 more
[2021-12-28 13:36:13,996] {spark_submit.py:514} INFO - 21/12/28 13:36:13 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2021-12-28 13:36:14,256] {spark_submit.py:514} INFO - 21/12/28 13:36:14 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master spark:7077
[2021-12-28 13:36:14,258] {spark_submit.py:514} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2021-12-28 13:36:14,259] {spark_submit.py:514} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:301)
[2021-12-28 13:36:14,263] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2021-12-28 13:36:14,267] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:101)
[2021-12-28 13:36:14,269] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:109)
[2021-12-28 13:36:14,270] {spark_submit.py:514} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:107)
[2021-12-28 13:36:14,273] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2021-12-28 13:36:14,274] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2021-12-28 13:36:14,276] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2021-12-28 13:36:14,280] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2021-12-28 13:36:14,281] {spark_submit.py:514} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-28 13:36:14,284] {spark_submit.py:514} INFO - Caused by: java.io.IOException: Failed to connect to spark:7077
[2021-12-28 13:36:14,287] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:288)
[2021-12-28 13:36:14,290] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:218)
[2021-12-28 13:36:14,293] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:230)
[2021-12-28 13:36:14,296] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2021-12-28 13:36:14,298] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2021-12-28 13:36:14,299] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2021-12-28 13:36:14,301] {spark_submit.py:514} INFO - ... 4 more
[2021-12-28 13:36:14,303] {spark_submit.py:514} INFO - Caused by: java.net.UnknownHostException: spark
[2021-12-28 13:36:14,307] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
[2021-12-28 13:36:14,309] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509)
[2021-12-28 13:36:14,311] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1368)
[2021-12-28 13:36:14,312] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1302)
[2021-12-28 13:36:14,313] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getByName(InetAddress.java:1252)
[2021-12-28 13:36:14,315] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156)
[2021-12-28 13:36:14,317] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153)
[2021-12-28 13:36:14,321] {spark_submit.py:514} INFO - at java.base/java.security.AccessController.doPrivileged(Native Method)
[2021-12-28 13:36:14,324] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153)
[2021-12-28 13:36:14,326] {spark_submit.py:514} INFO - at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41)
[2021-12-28 13:36:14,327] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
[2021-12-28 13:36:14,333] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53)
[2021-12-28 13:36:14,343] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
[2021-12-28 13:36:14,352] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
[2021-12-28 13:36:14,354] {spark_submit.py:514} INFO - at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
[2021-12-28 13:36:14,357] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:206)
[2021-12-28 13:36:14,365] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46)
[2021-12-28 13:36:14,369] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:180)
[2021-12-28 13:36:14,377] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:166)
[2021-12-28 13:36:14,382] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
[2021-12-28 13:36:14,388] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
[2021-12-28 13:36:14,390] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
[2021-12-28 13:36:14,395] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
[2021-12-28 13:36:14,398] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
[2021-12-28 13:36:14,402] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
[2021-12-28 13:36:14,404] {spark_submit.py:514} INFO - at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
[2021-12-28 13:36:14,406] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:1008)
[2021-12-28 13:36:14,408] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:516)
[2021-12-28 13:36:14,410] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
[2021-12-28 13:36:14,411] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
[2021-12-28 13:36:14,412] {spark_submit.py:514} INFO - at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[2021-12-28 13:36:14,413] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
[2021-12-28 13:36:14,415] {spark_submit.py:514} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[2021-12-28 13:36:14,416] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[2021-12-28 13:36:14,417] {spark_submit.py:514} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2021-12-28 13:36:14,418] {spark_submit.py:514} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2021-12-28 13:36:14,419] {spark_submit.py:514} INFO - ... 1 more
[2021-12-28 13:36:34,006] {spark_submit.py:514} INFO - 21/12/28 13:36:33 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2021-12-28 13:36:38,480] {spark_submit.py:514} INFO - 21/12/28 13:36:38 WARN TransportClientFactory: DNS resolution failed for spark:7077 took 3729 ms
[2021-12-28 13:36:38,410] {spark_submit.py:514} INFO - 21/12/28 13:36:38 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master spark:7077
[2021-12-28 13:36:38,508] {spark_submit.py:514} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2021-12-28 13:36:38,514] {spark_submit.py:514} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:301)
[2021-12-28 13:36:38,518] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2021-12-28 13:36:38,525] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:101)
[2021-12-28 13:36:38,532] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:109)
[2021-12-28 13:36:38,541] {spark_submit.py:514} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:107)
[2021-12-28 13:36:38,546] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2021-12-28 13:36:38,550] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2021-12-28 13:36:38,570] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2021-12-28 13:36:38,592] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2021-12-28 13:36:38,605] {spark_submit.py:514} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-28 13:36:38,621] {spark_submit.py:514} INFO - Caused by: java.io.IOException: Failed to connect to spark:7077
[2021-12-28 13:36:38,639] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:288)
[2021-12-28 13:36:38,661] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:218)
[2021-12-28 13:36:38,675] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:230)
[2021-12-28 13:36:38,690] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2021-12-28 13:36:38,696] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2021-12-28 13:36:38,721] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2021-12-28 13:36:38,751] {spark_submit.py:514} INFO - ... 4 more
[2021-12-28 13:36:38,779] {spark_submit.py:514} INFO - Caused by: java.net.UnknownHostException: spark
[2021-12-28 13:36:38,782] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
[2021-12-28 13:36:38,789] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509)
[2021-12-28 13:36:38,792] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1368)
[2021-12-28 13:36:38,801] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1302)
[2021-12-28 13:36:38,816] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getByName(InetAddress.java:1252)
[2021-12-28 13:36:38,822] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156)
[2021-12-28 13:36:38,831] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153)
[2021-12-28 13:36:38,838] {spark_submit.py:514} INFO - at java.base/java.security.AccessController.doPrivileged(Native Method)
[2021-12-28 13:36:38,844] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153)
[2021-12-28 13:36:38,854] {spark_submit.py:514} INFO - at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41)
[2021-12-28 13:36:38,856] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
[2021-12-28 13:36:38,862] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53)
[2021-12-28 13:36:38,878] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
[2021-12-28 13:36:38,890] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
[2021-12-28 13:36:38,894] {spark_submit.py:514} INFO - at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
[2021-12-28 13:36:38,897] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:206)
[2021-12-28 13:36:38,899] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46)
[2021-12-28 13:36:38,901] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:180)
[2021-12-28 13:36:38,905] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:166)
[2021-12-28 13:36:38,907] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
[2021-12-28 13:36:38,909] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
[2021-12-28 13:36:38,912] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
[2021-12-28 13:36:38,916] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
[2021-12-28 13:36:38,919] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
[2021-12-28 13:36:38,925] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
[2021-12-28 13:36:38,929] {spark_submit.py:514} INFO - at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
[2021-12-28 13:36:38,932] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:1008)
[2021-12-28 13:36:38,936] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:516)
[2021-12-28 13:36:38,938] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
[2021-12-28 13:36:38,940] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
[2021-12-28 13:36:38,942] {spark_submit.py:514} INFO - at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[2021-12-28 13:36:38,944] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
[2021-12-28 13:36:38,949] {spark_submit.py:514} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[2021-12-28 13:36:38,952] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[2021-12-28 13:36:38,956] {spark_submit.py:514} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2021-12-28 13:36:38,958] {spark_submit.py:514} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2021-12-28 13:36:38,961] {spark_submit.py:514} INFO - ... 1 more
[2021-12-28 13:36:53,485] {spark_submit.py:514} INFO - 21/12/28 13:36:53 ERROR StandaloneSchedulerBackend: Application has been killed. Reason: All masters are unresponsive! Giving up.
[2021-12-28 13:36:53,487] {spark_submit.py:514} INFO - 21/12/28 13:36:53 WARN StandaloneSchedulerBackend: Application ID is not initialized yet.
[2021-12-28 13:36:53,533] {spark_submit.py:514} INFO - 21/12/28 13:36:53 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 38549.
[2021-12-28 13:36:53,542] {spark_submit.py:514} INFO - 21/12/28 13:36:53 INFO NettyBlockTransferService: Server created on 0c125a5bba95:38549
[2021-12-28 13:36:53,549] {spark_submit.py:514} INFO - 21/12/28 13:36:53 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2021-12-28 13:36:53,637] {spark_submit.py:514} INFO - 21/12/28 13:36:53 INFO SparkUI: Stopped Spark web UI at http://0c125a5bba95:4052
[2021-12-28 13:36:53,649] {spark_submit.py:514} INFO - 21/12/28 13:36:53 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 0c125a5bba95, 38549, None)
[2021-12-28 13:36:53,689] {spark_submit.py:514} INFO - 21/12/28 13:36:53 INFO BlockManagerMasterEndpoint: Registering block manager 0c125a5bba95:38549 with 434.4 MiB RAM, BlockManagerId(driver, 0c125a5bba95, 38549, None)
[2021-12-28 13:36:53,690] {spark_submit.py:514} INFO - 21/12/28 13:36:53 INFO StandaloneSchedulerBackend: Shutting down all executors
[2021-12-28 13:36:53,703] {spark_submit.py:514} INFO - 21/12/28 13:36:53 INFO CoarseGrainedSchedulerBackend$DriverEndpoint: Asking each executor to shut down
[2021-12-28 13:36:53,780] {spark_submit.py:514} INFO - 21/12/28 13:36:53 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 0c125a5bba95, 38549, None)
[2021-12-28 13:36:53,806] {spark_submit.py:514} INFO - 21/12/28 13:36:53 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 0c125a5bba95, 38549, None)
[2021-12-28 13:36:53,815] {spark_submit.py:514} INFO - 21/12/28 13:36:53 WARN StandaloneAppClient$ClientEndpoint: Drop UnregisterApplication(null) because has not yet connected to master
[2021-12-28 13:36:54,087] {spark_submit.py:514} INFO - 21/12/28 13:36:54 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2021-12-28 13:36:55,046] {spark_submit.py:514} INFO - 21/12/28 13:36:55 INFO MemoryStore: MemoryStore cleared
[2021-12-28 13:36:55,073] {spark_submit.py:514} INFO - 21/12/28 13:36:55 INFO BlockManager: BlockManager stopped
[2021-12-28 13:36:55,168] {spark_submit.py:514} INFO - 21/12/28 13:36:55 INFO BlockManagerMaster: BlockManagerMaster stopped
[2021-12-28 13:36:55,208] {spark_submit.py:514} INFO - 21/12/28 13:36:55 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2021-12-28 13:36:55,836] {spark_submit.py:514} INFO - 21/12/28 13:36:55 INFO SparkContext: Successfully stopped SparkContext
[2021-12-28 13:36:56,495] {spark_submit.py:514} INFO - 21/12/28 13:36:56 ERROR SparkContext: Error initializing SparkContext.
[2021-12-28 13:36:56,509] {spark_submit.py:514} INFO - java.lang.IllegalArgumentException: requirement failed: Can only call getServletHandlers on a running MetricsSystem
[2021-12-28 13:36:56,512] {spark_submit.py:514} INFO - at scala.Predef$.require(Predef.scala:281)
[2021-12-28 13:36:56,513] {spark_submit.py:514} INFO - at org.apache.spark.metrics.MetricsSystem.getServletHandlers(MetricsSystem.scala:89)
[2021-12-28 13:36:56,514] {spark_submit.py:514} INFO - at org.apache.spark.SparkContext.<init>(SparkContext.scala:603)
[2021-12-28 13:36:56,514] {spark_submit.py:514} INFO - at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2021-12-28 13:36:56,515] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2021-12-28 13:36:56,516] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2021-12-28 13:36:56,517] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2021-12-28 13:36:56,519] {spark_submit.py:514} INFO - at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[2021-12-28 13:36:56,520] {spark_submit.py:514} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2021-12-28 13:36:56,523] {spark_submit.py:514} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2021-12-28 13:36:56,525] {spark_submit.py:514} INFO - at py4j.Gateway.invoke(Gateway.java:238)
[2021-12-28 13:36:56,525] {spark_submit.py:514} INFO - at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2021-12-28 13:36:56,526] {spark_submit.py:514} INFO - at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2021-12-28 13:36:56,527] {spark_submit.py:514} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2021-12-28 13:36:56,528] {spark_submit.py:514} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2021-12-28 13:36:56,530] {spark_submit.py:514} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-28 13:36:56,531] {spark_submit.py:514} INFO - 21/12/28 13:36:56 INFO SparkContext: SparkContext already stopped.
[2021-12-28 13:36:56,574] {spark_submit.py:514} INFO - Traceback (most recent call last):
[2021-12-28 13:36:56,575] {spark_submit.py:514} INFO - File "/opt/***/jobs/get_ads_per_county.py", line 13, in <module>
[2021-12-28 13:36:56,588] {spark_submit.py:514} INFO - .appName("Get Ads per county") \
[2021-12-28 13:36:56,590] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/session.py", line 228, in getOrCreate
[2021-12-28 13:36:56,591] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 392, in getOrCreate
[2021-12-28 13:36:56,593] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 147, in __init__
[2021-12-28 13:36:56,607] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 209, in _do_init
[2021-12-28 13:36:56,615] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 329, in _initialize_context
[2021-12-28 13:36:56,623] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/py4j-0.10.9.2-src.zip/py4j/java_gateway.py", line 1574, in __call__
[2021-12-28 13:36:56,626] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/py4j-0.10.9.2-src.zip/py4j/protocol.py", line 328, in get_return_value
[2021-12-28 13:36:56,633] {spark_submit.py:514} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling None.org.apache.spark.api.java.JavaSparkContext.
[2021-12-28 13:36:56,636] {spark_submit.py:514} INFO - : java.lang.IllegalArgumentException: requirement failed: Can only call getServletHandlers on a running MetricsSystem
[2021-12-28 13:36:56,637] {spark_submit.py:514} INFO - at scala.Predef$.require(Predef.scala:281)
[2021-12-28 13:36:56,638] {spark_submit.py:514} INFO - at org.apache.spark.metrics.MetricsSystem.getServletHandlers(MetricsSystem.scala:89)
[2021-12-28 13:36:56,639] {spark_submit.py:514} INFO - at org.apache.spark.SparkContext.<init>(SparkContext.scala:603)
[2021-12-28 13:36:56,640] {spark_submit.py:514} INFO - at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2021-12-28 13:36:56,641] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2021-12-28 13:36:56,642] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2021-12-28 13:36:56,643] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2021-12-28 13:36:56,647] {spark_submit.py:514} INFO - at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[2021-12-28 13:36:56,648] {spark_submit.py:514} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2021-12-28 13:36:56,649] {spark_submit.py:514} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2021-12-28 13:36:56,651] {spark_submit.py:514} INFO - at py4j.Gateway.invoke(Gateway.java:238)
[2021-12-28 13:36:56,652] {spark_submit.py:514} INFO - at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2021-12-28 13:36:56,653] {spark_submit.py:514} INFO - at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2021-12-28 13:36:56,654] {spark_submit.py:514} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2021-12-28 13:36:56,655] {spark_submit.py:514} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2021-12-28 13:36:56,656] {spark_submit.py:514} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-28 13:36:56,657] {spark_submit.py:514} INFO - 
[2021-12-28 13:36:58,421] {spark_submit.py:514} INFO - 21/12/28 13:36:58 INFO ShutdownHookManager: Shutdown hook called
[2021-12-28 13:36:58,442] {spark_submit.py:514} INFO - 21/12/28 13:36:58 INFO ShutdownHookManager: Deleting directory /tmp/spark-56ddb79b-7996-433b-beed-83b9f30a9158
[2021-12-28 13:36:58,499] {spark_submit.py:514} INFO - 21/12/28 13:36:58 INFO ShutdownHookManager: Deleting directory /tmp/spark-6df225ac-3100-42e8-866d-551e36825c0a
[2021-12-28 13:37:01,049] {taskinstance.py:1703} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 179, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 446, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark:7077 --conf spark.master=spark://spark:7077 --name scrap data --verbose /opt/***/jobs/get_ads_per_county.py tipperary. Error code is: 1.
[2021-12-28 13:37:01,122] {taskinstance.py:1280} INFO - Marking task as UP_FOR_RETRY. dag_id=scraping_daft_tipperary, task_id=scrap_data, execution_date=20211227T105000, start_date=20211228T133330, end_date=20211228T133701
[2021-12-28 13:37:01,324] {standard_task_runner.py:91} ERROR - Failed to execute job 5080 for task scrap_data
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 179, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 446, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark:7077 --conf spark.master=spark://spark:7077 --name scrap data --verbose /opt/***/jobs/get_ads_per_county.py tipperary. Error code is: 1.
[2021-12-28 13:37:01,489] {local_task_job.py:154} INFO - Task exited with return code 1
[2021-12-28 13:37:02,779] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
