[2021-12-28 13:43:43,769] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: scraping_daft_kildare.persist_data scheduled__2021-12-27T09:45:00+00:00 [queued]>
[2021-12-28 13:43:43,824] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: scraping_daft_kildare.persist_data scheduled__2021-12-27T09:45:00+00:00 [queued]>
[2021-12-28 13:43:43,825] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-28 13:43:43,826] {taskinstance.py:1242} INFO - Starting attempt 2 of 4
[2021-12-28 13:43:43,827] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-28 13:43:43,853] {taskinstance.py:1262} INFO - Executing <Task(SparkSubmitOperator): persist_data> on 2021-12-27 09:45:00+00:00
[2021-12-28 13:43:43,869] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'scraping_daft_kildare', 'persist_data', 'scheduled__2021-12-27T09:45:00+00:00', '--job-id', '5110', '--raw', '--subdir', 'DAGS_FOLDER/scraping_daft_kildare.py', '--cfg-path', '/tmp/tmpsq95_so8', '--error-file', '/tmp/tmpwkr1damo']
[2021-12-28 13:43:43,862] {standard_task_runner.py:52} INFO - Started process 54941 to run task
[2021-12-28 13:43:43,871] {standard_task_runner.py:77} INFO - Job 5110: Subtask persist_data
[2021-12-28 13:43:44,008] {logging_mixin.py:109} INFO - Running <TaskInstance: scraping_daft_kildare.persist_data scheduled__2021-12-27T09:45:00+00:00 [running]> on host 0c125a5bba95
[2021-12-28 13:43:44,192] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=clement.liscoet@gmail.com
AIRFLOW_CTX_DAG_OWNER=clemoni
AIRFLOW_CTX_DAG_ID=scraping_daft_kildare
AIRFLOW_CTX_TASK_ID=persist_data
AIRFLOW_CTX_EXECUTION_DATE=2021-12-27T09:45:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-27T09:45:00+00:00
[2021-12-28 13:43:44,244] {base.py:79} INFO - Using connection to: id: spark_default. Host: spark://spark:7077, Port: None, Schema: , Login: ***, Password: ***, extra: {}
[2021-12-28 13:43:44,251] {spark_submit.py:360} INFO - Spark-Submit cmd: spark-submit --master spark://spark:7077 --conf spark.master=spark://spark:7077 --name persist data --verbose /opt/***/jobs/persist_db.py kildare
[2021-12-28 13:43:46,419] {spark_submit.py:514} INFO - Using properties file: null
[2021-12-28 13:43:46,538] {spark_submit.py:514} INFO - WARNING: An illegal reflective access operation has occurred
[2021-12-28 13:43:46,539] {spark_submit.py:514} INFO - WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/home/***/.local/lib/python3.6/site-packages/pyspark/jars/spark-unsafe_2.12-3.2.0.jar) to constructor java.nio.DirectByteBuffer(long,int)
[2021-12-28 13:43:46,540] {spark_submit.py:514} INFO - WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
[2021-12-28 13:43:46,541] {spark_submit.py:514} INFO - WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[2021-12-28 13:43:46,542] {spark_submit.py:514} INFO - WARNING: All illegal access operations will be denied in a future release
[2021-12-28 13:43:46,601] {spark_submit.py:514} INFO - Parsed arguments:
[2021-12-28 13:43:46,602] {spark_submit.py:514} INFO - master                  spark://spark:7077
[2021-12-28 13:43:46,604] {spark_submit.py:514} INFO - deployMode              null
[2021-12-28 13:43:46,605] {spark_submit.py:514} INFO - executorMemory          null
[2021-12-28 13:43:46,606] {spark_submit.py:514} INFO - executorCores           null
[2021-12-28 13:43:46,606] {spark_submit.py:514} INFO - totalExecutorCores      null
[2021-12-28 13:43:46,607] {spark_submit.py:514} INFO - propertiesFile          null
[2021-12-28 13:43:46,608] {spark_submit.py:514} INFO - driverMemory            null
[2021-12-28 13:43:46,609] {spark_submit.py:514} INFO - driverCores             null
[2021-12-28 13:43:46,610] {spark_submit.py:514} INFO - driverExtraClassPath    null
[2021-12-28 13:43:46,611] {spark_submit.py:514} INFO - driverExtraLibraryPath  null
[2021-12-28 13:43:46,613] {spark_submit.py:514} INFO - driverExtraJavaOptions  null
[2021-12-28 13:43:46,613] {spark_submit.py:514} INFO - supervise               false
[2021-12-28 13:43:46,614] {spark_submit.py:514} INFO - queue                   null
[2021-12-28 13:43:46,615] {spark_submit.py:514} INFO - numExecutors            null
[2021-12-28 13:43:46,616] {spark_submit.py:514} INFO - files                   null
[2021-12-28 13:43:46,617] {spark_submit.py:514} INFO - pyFiles                 null
[2021-12-28 13:43:46,618] {spark_submit.py:514} INFO - archives                null
[2021-12-28 13:43:46,619] {spark_submit.py:514} INFO - mainClass               null
[2021-12-28 13:43:46,620] {spark_submit.py:514} INFO - primaryResource         file:/opt/***/jobs/persist_db.py
[2021-12-28 13:43:46,621] {spark_submit.py:514} INFO - name                    persist data
[2021-12-28 13:43:46,622] {spark_submit.py:514} INFO - childArgs               [kildare]
[2021-12-28 13:43:46,622] {spark_submit.py:514} INFO - jars                    null
[2021-12-28 13:43:46,623] {spark_submit.py:514} INFO - packages                null
[2021-12-28 13:43:46,624] {spark_submit.py:514} INFO - packagesExclusions      null
[2021-12-28 13:43:46,625] {spark_submit.py:514} INFO - repositories            null
[2021-12-28 13:43:46,627] {spark_submit.py:514} INFO - verbose                 true
[2021-12-28 13:43:46,628] {spark_submit.py:514} INFO - 
[2021-12-28 13:43:46,629] {spark_submit.py:514} INFO - Spark properties used, including those specified through
[2021-12-28 13:43:46,631] {spark_submit.py:514} INFO - --conf and those from the properties file null:
[2021-12-28 13:43:46,633] {spark_submit.py:514} INFO - (spark.master,spark://spark:7077)
[2021-12-28 13:43:46,634] {spark_submit.py:514} INFO - 
[2021-12-28 13:43:46,636] {spark_submit.py:514} INFO - 
[2021-12-28 13:43:47,004] {spark_submit.py:514} INFO - Main class:
[2021-12-28 13:43:47,005] {spark_submit.py:514} INFO - org.apache.spark.deploy.PythonRunner
[2021-12-28 13:43:47,007] {spark_submit.py:514} INFO - Arguments:
[2021-12-28 13:43:47,008] {spark_submit.py:514} INFO - file:/opt/***/jobs/persist_db.py
[2021-12-28 13:43:47,009] {spark_submit.py:514} INFO - null
[2021-12-28 13:43:47,010] {spark_submit.py:514} INFO - kildare
[2021-12-28 13:43:47,012] {spark_submit.py:514} INFO - --verbose
[2021-12-28 13:43:47,013] {spark_submit.py:514} INFO - Spark config:
[2021-12-28 13:43:47,014] {spark_submit.py:514} INFO - (spark.master,spark://spark:7077)
[2021-12-28 13:43:47,015] {spark_submit.py:514} INFO - (spark.app.name,persist data)
[2021-12-28 13:43:47,016] {spark_submit.py:514} INFO - (spark.submit.pyFiles,)
[2021-12-28 13:43:47,018] {spark_submit.py:514} INFO - (spark.submit.deployMode,client)
[2021-12-28 13:43:47,019] {spark_submit.py:514} INFO - Classpath elements:
[2021-12-28 13:43:47,020] {spark_submit.py:514} INFO - 
[2021-12-28 13:43:47,021] {spark_submit.py:514} INFO - 
[2021-12-28 13:43:47,022] {spark_submit.py:514} INFO - 
[2021-12-28 13:43:48,263] {spark_submit.py:514} INFO - Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
[2021-12-28 13:43:48,280] {spark_submit.py:514} INFO - 21/12/28 13:43:48 INFO SparkContext: Running Spark version 3.2.0
[2021-12-28 13:43:48,411] {spark_submit.py:514} INFO - 21/12/28 13:43:48 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2021-12-28 13:43:48,653] {spark_submit.py:514} INFO - 21/12/28 13:43:48 INFO ResourceUtils: ==============================================================
[2021-12-28 13:43:48,655] {spark_submit.py:514} INFO - 21/12/28 13:43:48 INFO ResourceUtils: No custom resources configured for spark.driver.
[2021-12-28 13:43:48,657] {spark_submit.py:514} INFO - 21/12/28 13:43:48 INFO ResourceUtils: ==============================================================
[2021-12-28 13:43:48,658] {spark_submit.py:514} INFO - 21/12/28 13:43:48 INFO SparkContext: Submitted application: Persist DB
[2021-12-28 13:43:48,701] {spark_submit.py:514} INFO - 21/12/28 13:43:48 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2021-12-28 13:43:48,718] {spark_submit.py:514} INFO - 21/12/28 13:43:48 INFO ResourceProfile: Limiting resource is cpu
[2021-12-28 13:43:48,720] {spark_submit.py:514} INFO - 21/12/28 13:43:48 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2021-12-28 13:43:48,827] {spark_submit.py:514} INFO - 21/12/28 13:43:48 INFO SecurityManager: Changing view acls to: ***
[2021-12-28 13:43:48,832] {spark_submit.py:514} INFO - 21/12/28 13:43:48 INFO SecurityManager: Changing modify acls to: ***
[2021-12-28 13:43:48,834] {spark_submit.py:514} INFO - 21/12/28 13:43:48 INFO SecurityManager: Changing view acls groups to:
[2021-12-28 13:43:48,835] {spark_submit.py:514} INFO - 21/12/28 13:43:48 INFO SecurityManager: Changing modify acls groups to:
[2021-12-28 13:43:48,836] {spark_submit.py:514} INFO - 21/12/28 13:43:48 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(***); groups with view permissions: Set(); users  with modify permissions: Set(***); groups with modify permissions: Set()
[2021-12-28 13:43:49,242] {spark_submit.py:514} INFO - 21/12/28 13:43:49 INFO Utils: Successfully started service 'sparkDriver' on port 41553.
[2021-12-28 13:43:49,289] {spark_submit.py:514} INFO - 21/12/28 13:43:49 INFO SparkEnv: Registering MapOutputTracker
[2021-12-28 13:43:49,345] {spark_submit.py:514} INFO - 21/12/28 13:43:49 INFO SparkEnv: Registering BlockManagerMaster
[2021-12-28 13:43:49,389] {spark_submit.py:514} INFO - 21/12/28 13:43:49 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2021-12-28 13:43:49,391] {spark_submit.py:514} INFO - 21/12/28 13:43:49 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2021-12-28 13:43:49,400] {spark_submit.py:514} INFO - 21/12/28 13:43:49 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2021-12-28 13:43:49,446] {spark_submit.py:514} INFO - 21/12/28 13:43:49 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-50cb58ba-77e4-45e6-84b0-aae46bb12242
[2021-12-28 13:43:49,477] {spark_submit.py:514} INFO - 21/12/28 13:43:49 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2021-12-28 13:43:49,501] {spark_submit.py:514} INFO - 21/12/28 13:43:49 INFO SparkEnv: Registering OutputCommitCoordinator
[2021-12-28 13:43:49,868] {spark_submit.py:514} INFO - 21/12/28 13:43:49 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2021-12-28 13:43:49,870] {spark_submit.py:514} INFO - 21/12/28 13:43:49 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.
[2021-12-28 13:43:49,872] {spark_submit.py:514} INFO - 21/12/28 13:43:49 WARN Utils: Service 'SparkUI' could not bind on port 4042. Attempting port 4043.
[2021-12-28 13:43:49,874] {spark_submit.py:514} INFO - 21/12/28 13:43:49 WARN Utils: Service 'SparkUI' could not bind on port 4043. Attempting port 4044.
[2021-12-28 13:43:49,876] {spark_submit.py:514} INFO - 21/12/28 13:43:49 WARN Utils: Service 'SparkUI' could not bind on port 4044. Attempting port 4045.
[2021-12-28 13:43:49,877] {spark_submit.py:514} INFO - 21/12/28 13:43:49 WARN Utils: Service 'SparkUI' could not bind on port 4045. Attempting port 4046.
[2021-12-28 13:43:49,903] {spark_submit.py:514} INFO - 21/12/28 13:43:49 INFO Utils: Successfully started service 'SparkUI' on port 4046.
[2021-12-28 13:43:50,027] {spark_submit.py:514} INFO - 21/12/28 13:43:50 INFO SparkUI: Bound SparkUI to 0.0.0.0, and started at http://0c125a5bba95:4046
[2021-12-28 13:43:50,400] {spark_submit.py:514} INFO - 21/12/28 13:43:50 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2021-12-28 13:43:50,525] {spark_submit.py:514} INFO - 21/12/28 13:43:50 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master spark:7077
[2021-12-28 13:43:50,526] {spark_submit.py:514} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2021-12-28 13:43:50,527] {spark_submit.py:514} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:301)
[2021-12-28 13:43:50,529] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2021-12-28 13:43:50,530] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:101)
[2021-12-28 13:43:50,531] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:109)
[2021-12-28 13:43:50,532] {spark_submit.py:514} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:107)
[2021-12-28 13:43:50,535] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2021-12-28 13:43:50,536] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2021-12-28 13:43:50,537] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2021-12-28 13:43:50,538] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2021-12-28 13:43:50,539] {spark_submit.py:514} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-28 13:43:50,540] {spark_submit.py:514} INFO - Caused by: java.io.IOException: Failed to connect to spark:7077
[2021-12-28 13:43:50,542] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:288)
[2021-12-28 13:43:50,543] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:218)
[2021-12-28 13:43:50,544] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:230)
[2021-12-28 13:43:50,545] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2021-12-28 13:43:50,546] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2021-12-28 13:43:50,547] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2021-12-28 13:43:50,548] {spark_submit.py:514} INFO - ... 4 more
[2021-12-28 13:43:50,549] {spark_submit.py:514} INFO - Caused by: java.net.UnknownHostException: spark
[2021-12-28 13:43:50,550] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
[2021-12-28 13:43:50,550] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509)
[2021-12-28 13:43:50,551] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1368)
[2021-12-28 13:43:50,552] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1302)
[2021-12-28 13:43:50,553] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getByName(InetAddress.java:1252)
[2021-12-28 13:43:50,553] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156)
[2021-12-28 13:43:50,554] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153)
[2021-12-28 13:43:50,555] {spark_submit.py:514} INFO - at java.base/java.security.AccessController.doPrivileged(Native Method)
[2021-12-28 13:43:50,555] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153)
[2021-12-28 13:43:50,556] {spark_submit.py:514} INFO - at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41)
[2021-12-28 13:43:50,557] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
[2021-12-28 13:43:50,558] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53)
[2021-12-28 13:43:50,559] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
[2021-12-28 13:43:50,560] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
[2021-12-28 13:43:50,560] {spark_submit.py:514} INFO - at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
[2021-12-28 13:43:50,561] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:206)
[2021-12-28 13:43:50,562] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46)
[2021-12-28 13:43:50,562] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:180)
[2021-12-28 13:43:50,563] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:166)
[2021-12-28 13:43:50,563] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
[2021-12-28 13:43:50,564] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
[2021-12-28 13:43:50,565] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
[2021-12-28 13:43:50,565] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
[2021-12-28 13:43:50,566] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
[2021-12-28 13:43:50,566] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
[2021-12-28 13:43:50,567] {spark_submit.py:514} INFO - at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
[2021-12-28 13:43:50,568] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:1008)
[2021-12-28 13:43:50,568] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:516)
[2021-12-28 13:43:50,569] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
[2021-12-28 13:43:50,570] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
[2021-12-28 13:43:50,571] {spark_submit.py:514} INFO - at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[2021-12-28 13:43:50,571] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
[2021-12-28 13:43:50,572] {spark_submit.py:514} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[2021-12-28 13:43:50,573] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[2021-12-28 13:43:50,574] {spark_submit.py:514} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2021-12-28 13:43:50,574] {spark_submit.py:514} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2021-12-28 13:43:50,575] {spark_submit.py:514} INFO - ... 1 more
[2021-12-28 13:44:10,364] {spark_submit.py:514} INFO - 21/12/28 13:44:10 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2021-12-28 13:44:10,397] {spark_submit.py:514} INFO - 21/12/28 13:44:10 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master spark:7077
[2021-12-28 13:44:10,399] {spark_submit.py:514} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2021-12-28 13:44:10,400] {spark_submit.py:514} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:301)
[2021-12-28 13:44:10,401] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2021-12-28 13:44:10,404] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:101)
[2021-12-28 13:44:10,405] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:109)
[2021-12-28 13:44:10,406] {spark_submit.py:514} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:107)
[2021-12-28 13:44:10,407] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2021-12-28 13:44:10,410] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2021-12-28 13:44:10,411] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2021-12-28 13:44:10,412] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2021-12-28 13:44:10,413] {spark_submit.py:514} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-28 13:44:10,415] {spark_submit.py:514} INFO - Caused by: java.io.IOException: Failed to connect to spark:7077
[2021-12-28 13:44:10,416] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:288)
[2021-12-28 13:44:10,417] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:218)
[2021-12-28 13:44:10,418] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:230)
[2021-12-28 13:44:10,419] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2021-12-28 13:44:10,420] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2021-12-28 13:44:10,422] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2021-12-28 13:44:10,423] {spark_submit.py:514} INFO - ... 4 more
[2021-12-28 13:44:10,424] {spark_submit.py:514} INFO - Caused by: java.net.UnknownHostException: spark
[2021-12-28 13:44:10,425] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
[2021-12-28 13:44:10,427] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509)
[2021-12-28 13:44:10,427] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1368)
[2021-12-28 13:44:10,429] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1302)
[2021-12-28 13:44:10,430] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getByName(InetAddress.java:1252)
[2021-12-28 13:44:10,431] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156)
[2021-12-28 13:44:10,432] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153)
[2021-12-28 13:44:10,434] {spark_submit.py:514} INFO - at java.base/java.security.AccessController.doPrivileged(Native Method)
[2021-12-28 13:44:10,434] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153)
[2021-12-28 13:44:10,435] {spark_submit.py:514} INFO - at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41)
[2021-12-28 13:44:10,437] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
[2021-12-28 13:44:10,438] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53)
[2021-12-28 13:44:10,439] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
[2021-12-28 13:44:10,440] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
[2021-12-28 13:44:10,442] {spark_submit.py:514} INFO - at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
[2021-12-28 13:44:10,443] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:206)
[2021-12-28 13:44:10,443] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46)
[2021-12-28 13:44:10,445] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:180)
[2021-12-28 13:44:10,449] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:166)
[2021-12-28 13:44:10,451] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
[2021-12-28 13:44:10,452] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
[2021-12-28 13:44:10,453] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
[2021-12-28 13:44:10,454] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
[2021-12-28 13:44:10,455] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
[2021-12-28 13:44:10,457] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
[2021-12-28 13:44:10,457] {spark_submit.py:514} INFO - at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
[2021-12-28 13:44:10,459] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:1008)
[2021-12-28 13:44:10,460] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:516)
[2021-12-28 13:44:10,461] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
[2021-12-28 13:44:10,462] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
[2021-12-28 13:44:10,463] {spark_submit.py:514} INFO - at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[2021-12-28 13:44:10,464] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
[2021-12-28 13:44:10,465] {spark_submit.py:514} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[2021-12-28 13:44:10,466] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[2021-12-28 13:44:10,467] {spark_submit.py:514} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2021-12-28 13:44:10,468] {spark_submit.py:514} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2021-12-28 13:44:10,469] {spark_submit.py:514} INFO - ... 1 more
[2021-12-28 13:44:30,365] {spark_submit.py:514} INFO - 21/12/28 13:44:30 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2021-12-28 13:44:30,382] {spark_submit.py:514} INFO - 21/12/28 13:44:30 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master spark:7077
[2021-12-28 13:44:30,383] {spark_submit.py:514} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2021-12-28 13:44:30,383] {spark_submit.py:514} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:301)
[2021-12-28 13:44:30,384] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2021-12-28 13:44:30,385] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:101)
[2021-12-28 13:44:30,385] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:109)
[2021-12-28 13:44:30,386] {spark_submit.py:514} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:107)
[2021-12-28 13:44:30,387] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2021-12-28 13:44:30,388] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2021-12-28 13:44:30,388] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2021-12-28 13:44:30,389] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2021-12-28 13:44:30,389] {spark_submit.py:514} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-28 13:44:30,390] {spark_submit.py:514} INFO - Caused by: java.io.IOException: Failed to connect to spark:7077
[2021-12-28 13:44:30,391] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:288)
[2021-12-28 13:44:30,391] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:218)
[2021-12-28 13:44:30,392] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:230)
[2021-12-28 13:44:30,393] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2021-12-28 13:44:30,393] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2021-12-28 13:44:30,394] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2021-12-28 13:44:30,394] {spark_submit.py:514} INFO - ... 4 more
[2021-12-28 13:44:30,395] {spark_submit.py:514} INFO - Caused by: java.net.UnknownHostException: spark
[2021-12-28 13:44:30,396] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
[2021-12-28 13:44:30,396] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509)
[2021-12-28 13:44:30,397] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1368)
[2021-12-28 13:44:30,397] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1302)
[2021-12-28 13:44:30,398] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getByName(InetAddress.java:1252)
[2021-12-28 13:44:30,398] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156)
[2021-12-28 13:44:30,399] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153)
[2021-12-28 13:44:30,400] {spark_submit.py:514} INFO - at java.base/java.security.AccessController.doPrivileged(Native Method)
[2021-12-28 13:44:30,400] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153)
[2021-12-28 13:44:30,401] {spark_submit.py:514} INFO - at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41)
[2021-12-28 13:44:30,402] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
[2021-12-28 13:44:30,402] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53)
[2021-12-28 13:44:30,403] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
[2021-12-28 13:44:30,404] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
[2021-12-28 13:44:30,404] {spark_submit.py:514} INFO - at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
[2021-12-28 13:44:30,405] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:206)
[2021-12-28 13:44:30,405] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46)
[2021-12-28 13:44:30,407] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:180)
[2021-12-28 13:44:30,407] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:166)
[2021-12-28 13:44:30,408] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
[2021-12-28 13:44:30,408] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
[2021-12-28 13:44:30,409] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
[2021-12-28 13:44:30,410] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
[2021-12-28 13:44:30,410] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
[2021-12-28 13:44:30,411] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
[2021-12-28 13:44:30,412] {spark_submit.py:514} INFO - at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
[2021-12-28 13:44:30,412] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:1008)
[2021-12-28 13:44:30,413] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:516)
[2021-12-28 13:44:30,414] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
[2021-12-28 13:44:30,414] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
[2021-12-28 13:44:30,415] {spark_submit.py:514} INFO - at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[2021-12-28 13:44:30,415] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
[2021-12-28 13:44:30,416] {spark_submit.py:514} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[2021-12-28 13:44:30,417] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[2021-12-28 13:44:30,417] {spark_submit.py:514} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2021-12-28 13:44:30,418] {spark_submit.py:514} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2021-12-28 13:44:30,419] {spark_submit.py:514} INFO - ... 1 more
[2021-12-28 13:44:50,331] {spark_submit.py:514} INFO - 21/12/28 13:44:50 ERROR StandaloneSchedulerBackend: Application has been killed. Reason: All masters are unresponsive! Giving up.
[2021-12-28 13:44:50,332] {spark_submit.py:514} INFO - 21/12/28 13:44:50 WARN StandaloneSchedulerBackend: Application ID is not initialized yet.
[2021-12-28 13:44:50,345] {spark_submit.py:514} INFO - 21/12/28 13:44:50 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 33623.
[2021-12-28 13:44:50,346] {spark_submit.py:514} INFO - 21/12/28 13:44:50 INFO NettyBlockTransferService: Server created on 0c125a5bba95:33623
[2021-12-28 13:44:50,349] {spark_submit.py:514} INFO - 21/12/28 13:44:50 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2021-12-28 13:44:50,366] {spark_submit.py:514} INFO - 21/12/28 13:44:50 INFO SparkUI: Stopped Spark web UI at http://0c125a5bba95:4046
[2021-12-28 13:44:50,370] {spark_submit.py:514} INFO - 21/12/28 13:44:50 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 0c125a5bba95, 33623, None)
[2021-12-28 13:44:50,376] {spark_submit.py:514} INFO - 21/12/28 13:44:50 INFO BlockManagerMasterEndpoint: Registering block manager 0c125a5bba95:33623 with 434.4 MiB RAM, BlockManagerId(driver, 0c125a5bba95, 33623, None)
[2021-12-28 13:44:50,379] {spark_submit.py:514} INFO - 21/12/28 13:44:50 INFO StandaloneSchedulerBackend: Shutting down all executors
[2021-12-28 13:44:50,380] {spark_submit.py:514} INFO - 21/12/28 13:44:50 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 0c125a5bba95, 33623, None)
[2021-12-28 13:44:50,382] {spark_submit.py:514} INFO - 21/12/28 13:44:50 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 0c125a5bba95, 33623, None)
[2021-12-28 13:44:50,385] {spark_submit.py:514} INFO - 21/12/28 13:44:50 INFO CoarseGrainedSchedulerBackend$DriverEndpoint: Asking each executor to shut down
[2021-12-28 13:44:50,393] {spark_submit.py:514} INFO - 21/12/28 13:44:50 WARN StandaloneAppClient$ClientEndpoint: Drop UnregisterApplication(null) because has not yet connected to master
[2021-12-28 13:44:50,408] {spark_submit.py:514} INFO - 21/12/28 13:44:50 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2021-12-28 13:44:50,430] {spark_submit.py:514} INFO - 21/12/28 13:44:50 INFO MemoryStore: MemoryStore cleared
[2021-12-28 13:44:50,432] {spark_submit.py:514} INFO - 21/12/28 13:44:50 INFO BlockManager: BlockManager stopped
[2021-12-28 13:44:50,441] {spark_submit.py:514} INFO - 21/12/28 13:44:50 INFO BlockManagerMaster: BlockManagerMaster stopped
[2021-12-28 13:44:50,445] {spark_submit.py:514} INFO - 21/12/28 13:44:50 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2021-12-28 13:44:50,465] {spark_submit.py:514} INFO - 21/12/28 13:44:50 INFO SparkContext: Successfully stopped SparkContext
[2021-12-28 13:44:50,600] {spark_submit.py:514} INFO - 21/12/28 13:44:50 ERROR SparkContext: Error initializing SparkContext.
[2021-12-28 13:44:50,602] {spark_submit.py:514} INFO - java.lang.IllegalArgumentException: requirement failed: Can only call getServletHandlers on a running MetricsSystem
[2021-12-28 13:44:50,603] {spark_submit.py:514} INFO - at scala.Predef$.require(Predef.scala:281)
[2021-12-28 13:44:50,604] {spark_submit.py:514} INFO - at org.apache.spark.metrics.MetricsSystem.getServletHandlers(MetricsSystem.scala:89)
[2021-12-28 13:44:50,605] {spark_submit.py:514} INFO - at org.apache.spark.SparkContext.<init>(SparkContext.scala:603)
[2021-12-28 13:44:50,606] {spark_submit.py:514} INFO - at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2021-12-28 13:44:50,607] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2021-12-28 13:44:50,608] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2021-12-28 13:44:50,609] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2021-12-28 13:44:50,609] {spark_submit.py:514} INFO - at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[2021-12-28 13:44:50,611] {spark_submit.py:514} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2021-12-28 13:44:50,612] {spark_submit.py:514} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2021-12-28 13:44:50,613] {spark_submit.py:514} INFO - at py4j.Gateway.invoke(Gateway.java:238)
[2021-12-28 13:44:50,614] {spark_submit.py:514} INFO - at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2021-12-28 13:44:50,615] {spark_submit.py:514} INFO - at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2021-12-28 13:44:50,616] {spark_submit.py:514} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2021-12-28 13:44:50,617] {spark_submit.py:514} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2021-12-28 13:44:50,618] {spark_submit.py:514} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-28 13:44:50,619] {spark_submit.py:514} INFO - 21/12/28 13:44:50 INFO SparkContext: SparkContext already stopped.
[2021-12-28 13:44:50,621] {spark_submit.py:514} INFO - Traceback (most recent call last):
[2021-12-28 13:44:50,622] {spark_submit.py:514} INFO - File "/opt/***/jobs/persist_db.py", line 52, in <module>
[2021-12-28 13:44:50,623] {spark_submit.py:514} INFO - .config("spark.driver.bindAddress", "localhost") \
[2021-12-28 13:44:50,624] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/session.py", line 228, in getOrCreate
[2021-12-28 13:44:50,625] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 392, in getOrCreate
[2021-12-28 13:44:50,626] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 147, in __init__
[2021-12-28 13:44:50,627] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 209, in _do_init
[2021-12-28 13:44:50,628] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 329, in _initialize_context
[2021-12-28 13:44:50,629] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/py4j-0.10.9.2-src.zip/py4j/java_gateway.py", line 1574, in __call__
[2021-12-28 13:44:50,630] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/py4j-0.10.9.2-src.zip/py4j/protocol.py", line 328, in get_return_value
[2021-12-28 13:44:50,631] {spark_submit.py:514} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling None.org.apache.spark.api.java.JavaSparkContext.
[2021-12-28 13:44:50,632] {spark_submit.py:514} INFO - : java.lang.IllegalArgumentException: requirement failed: Can only call getServletHandlers on a running MetricsSystem
[2021-12-28 13:44:50,633] {spark_submit.py:514} INFO - at scala.Predef$.require(Predef.scala:281)
[2021-12-28 13:44:50,634] {spark_submit.py:514} INFO - at org.apache.spark.metrics.MetricsSystem.getServletHandlers(MetricsSystem.scala:89)
[2021-12-28 13:44:50,635] {spark_submit.py:514} INFO - at org.apache.spark.SparkContext.<init>(SparkContext.scala:603)
[2021-12-28 13:44:50,636] {spark_submit.py:514} INFO - at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2021-12-28 13:44:50,637] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2021-12-28 13:44:50,638] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2021-12-28 13:44:50,639] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2021-12-28 13:44:50,639] {spark_submit.py:514} INFO - at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[2021-12-28 13:44:50,640] {spark_submit.py:514} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2021-12-28 13:44:50,641] {spark_submit.py:514} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2021-12-28 13:44:50,642] {spark_submit.py:514} INFO - at py4j.Gateway.invoke(Gateway.java:238)
[2021-12-28 13:44:50,642] {spark_submit.py:514} INFO - at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2021-12-28 13:44:50,643] {spark_submit.py:514} INFO - at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2021-12-28 13:44:50,644] {spark_submit.py:514} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2021-12-28 13:44:50,644] {spark_submit.py:514} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2021-12-28 13:44:50,645] {spark_submit.py:514} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-28 13:44:50,646] {spark_submit.py:514} INFO - 
[2021-12-28 13:44:50,710] {spark_submit.py:514} INFO - 21/12/28 13:44:50 INFO ShutdownHookManager: Shutdown hook called
[2021-12-28 13:44:50,711] {spark_submit.py:514} INFO - 21/12/28 13:44:50 INFO ShutdownHookManager: Deleting directory /tmp/spark-446d6d5b-78f5-4bc8-a116-396d8877a7de
[2021-12-28 13:44:50,715] {spark_submit.py:514} INFO - 21/12/28 13:44:50 INFO ShutdownHookManager: Deleting directory /tmp/spark-2a27d2bb-01e4-4bea-b1e8-df4ee13576e3
[2021-12-28 13:44:50,933] {taskinstance.py:1703} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 179, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 446, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark:7077 --conf spark.master=spark://spark:7077 --name persist data --verbose /opt/***/jobs/persist_db.py kildare. Error code is: 1.
[2021-12-28 13:44:50,939] {taskinstance.py:1280} INFO - Marking task as UP_FOR_RETRY. dag_id=scraping_daft_kildare, task_id=persist_data, execution_date=20211227T094500, start_date=20211228T134343, end_date=20211228T134450
[2021-12-28 13:44:50,957] {standard_task_runner.py:91} ERROR - Failed to execute job 5110 for task persist_data
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 179, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 446, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark:7077 --conf spark.master=spark://spark:7077 --name persist data --verbose /opt/***/jobs/persist_db.py kildare. Error code is: 1.
[2021-12-28 13:44:50,977] {local_task_job.py:154} INFO - Task exited with return code 1
[2021-12-28 13:44:51,058] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
