[2021-12-28 14:38:14,110] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: scraping_daft_carlow.scrap_data manual__2021-12-28T14:38:11.745181+00:00 [queued]>
[2021-12-28 14:38:14,140] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: scraping_daft_carlow.scrap_data manual__2021-12-28T14:38:11.745181+00:00 [queued]>
[2021-12-28 14:38:14,142] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-28 14:38:14,143] {taskinstance.py:1242} INFO - Starting attempt 1 of 4
[2021-12-28 14:38:14,144] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-28 14:38:14,178] {taskinstance.py:1262} INFO - Executing <Task(SparkSubmitOperator): scrap_data> on 2021-12-28 14:38:11.745181+00:00
[2021-12-28 14:38:14,192] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'scraping_daft_carlow', 'scrap_data', 'manual__2021-12-28T14:38:11.745181+00:00', '--job-id', '5131', '--raw', '--subdir', 'DAGS_FOLDER/scraping_daft_carlow.py', '--cfg-path', '/tmp/tmpm6kydmk2', '--error-file', '/tmp/tmphd26zb0k']
[2021-12-28 14:38:14,194] {standard_task_runner.py:77} INFO - Job 5131: Subtask scrap_data
[2021-12-28 14:38:14,188] {standard_task_runner.py:52} INFO - Started process 59623 to run task
[2021-12-28 14:38:14,309] {logging_mixin.py:109} INFO - Running <TaskInstance: scraping_daft_carlow.scrap_data manual__2021-12-28T14:38:11.745181+00:00 [running]> on host 0c125a5bba95
[2021-12-28 14:38:14,510] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=clement.liscoet@gmail.com
AIRFLOW_CTX_DAG_OWNER=clemoni
AIRFLOW_CTX_DAG_ID=scraping_daft_carlow
AIRFLOW_CTX_TASK_ID=scrap_data
AIRFLOW_CTX_EXECUTION_DATE=2021-12-28T14:38:11.745181+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-12-28T14:38:11.745181+00:00
[2021-12-28 14:38:14,537] {base.py:79} INFO - Using connection to: id: spark_default. Host: spark://spark:7077, Port: None, Schema: , Login: ***, Password: ***, extra: {}
[2021-12-28 14:38:14,540] {spark_submit.py:360} INFO - Spark-Submit cmd: spark-submit --master spark://spark:7077 --conf spark.master=spark://spark:7077 --name scrap data --verbose /opt/***/jobs/get_ads_per_county.py carlow
[2021-12-28 14:38:16,252] {spark_submit.py:514} INFO - Using properties file: null
[2021-12-28 14:38:16,373] {spark_submit.py:514} INFO - WARNING: An illegal reflective access operation has occurred
[2021-12-28 14:38:16,375] {spark_submit.py:514} INFO - WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/home/***/.local/lib/python3.6/site-packages/pyspark/jars/spark-unsafe_2.12-3.2.0.jar) to constructor java.nio.DirectByteBuffer(long,int)
[2021-12-28 14:38:16,376] {spark_submit.py:514} INFO - WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
[2021-12-28 14:38:16,377] {spark_submit.py:514} INFO - WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[2021-12-28 14:38:16,378] {spark_submit.py:514} INFO - WARNING: All illegal access operations will be denied in a future release
[2021-12-28 14:38:16,437] {spark_submit.py:514} INFO - Parsed arguments:
[2021-12-28 14:38:16,438] {spark_submit.py:514} INFO - master                  spark://spark:7077
[2021-12-28 14:38:16,439] {spark_submit.py:514} INFO - deployMode              null
[2021-12-28 14:38:16,439] {spark_submit.py:514} INFO - executorMemory          null
[2021-12-28 14:38:16,440] {spark_submit.py:514} INFO - executorCores           null
[2021-12-28 14:38:16,441] {spark_submit.py:514} INFO - totalExecutorCores      null
[2021-12-28 14:38:16,442] {spark_submit.py:514} INFO - propertiesFile          null
[2021-12-28 14:38:16,445] {spark_submit.py:514} INFO - driverMemory            null
[2021-12-28 14:38:16,446] {spark_submit.py:514} INFO - driverCores             null
[2021-12-28 14:38:16,447] {spark_submit.py:514} INFO - driverExtraClassPath    null
[2021-12-28 14:38:16,448] {spark_submit.py:514} INFO - driverExtraLibraryPath  null
[2021-12-28 14:38:16,450] {spark_submit.py:514} INFO - driverExtraJavaOptions  null
[2021-12-28 14:38:16,451] {spark_submit.py:514} INFO - supervise               false
[2021-12-28 14:38:16,452] {spark_submit.py:514} INFO - queue                   null
[2021-12-28 14:38:16,453] {spark_submit.py:514} INFO - numExecutors            null
[2021-12-28 14:38:16,453] {spark_submit.py:514} INFO - files                   null
[2021-12-28 14:38:16,454] {spark_submit.py:514} INFO - pyFiles                 null
[2021-12-28 14:38:16,455] {spark_submit.py:514} INFO - archives                null
[2021-12-28 14:38:16,456] {spark_submit.py:514} INFO - mainClass               null
[2021-12-28 14:38:16,456] {spark_submit.py:514} INFO - primaryResource         file:/opt/***/jobs/get_ads_per_county.py
[2021-12-28 14:38:16,457] {spark_submit.py:514} INFO - name                    scrap data
[2021-12-28 14:38:16,458] {spark_submit.py:514} INFO - childArgs               [carlow]
[2021-12-28 14:38:16,459] {spark_submit.py:514} INFO - jars                    null
[2021-12-28 14:38:16,460] {spark_submit.py:514} INFO - packages                null
[2021-12-28 14:38:16,461] {spark_submit.py:514} INFO - packagesExclusions      null
[2021-12-28 14:38:16,462] {spark_submit.py:514} INFO - repositories            null
[2021-12-28 14:38:16,463] {spark_submit.py:514} INFO - verbose                 true
[2021-12-28 14:38:16,464] {spark_submit.py:514} INFO - 
[2021-12-28 14:38:16,465] {spark_submit.py:514} INFO - Spark properties used, including those specified through
[2021-12-28 14:38:16,465] {spark_submit.py:514} INFO - --conf and those from the properties file null:
[2021-12-28 14:38:16,466] {spark_submit.py:514} INFO - (spark.master,spark://spark:7077)
[2021-12-28 14:38:16,467] {spark_submit.py:514} INFO - 
[2021-12-28 14:38:16,468] {spark_submit.py:514} INFO - 
[2021-12-28 14:38:16,785] {spark_submit.py:514} INFO - Main class:
[2021-12-28 14:38:16,787] {spark_submit.py:514} INFO - org.apache.spark.deploy.PythonRunner
[2021-12-28 14:38:16,788] {spark_submit.py:514} INFO - Arguments:
[2021-12-28 14:38:16,788] {spark_submit.py:514} INFO - file:/opt/***/jobs/get_ads_per_county.py
[2021-12-28 14:38:16,789] {spark_submit.py:514} INFO - null
[2021-12-28 14:38:16,790] {spark_submit.py:514} INFO - carlow
[2021-12-28 14:38:16,791] {spark_submit.py:514} INFO - --verbose
[2021-12-28 14:38:16,792] {spark_submit.py:514} INFO - Spark config:
[2021-12-28 14:38:16,793] {spark_submit.py:514} INFO - (spark.app.name,scrap data)
[2021-12-28 14:38:16,794] {spark_submit.py:514} INFO - (spark.master,spark://spark:7077)
[2021-12-28 14:38:16,795] {spark_submit.py:514} INFO - (spark.submit.pyFiles,)
[2021-12-28 14:38:16,796] {spark_submit.py:514} INFO - (spark.submit.deployMode,client)
[2021-12-28 14:38:16,797] {spark_submit.py:514} INFO - Classpath elements:
[2021-12-28 14:38:16,798] {spark_submit.py:514} INFO - 
[2021-12-28 14:38:16,799] {spark_submit.py:514} INFO - 
[2021-12-28 14:38:16,799] {spark_submit.py:514} INFO - 
[2021-12-28 14:38:17,813] {spark_submit.py:514} INFO - Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
[2021-12-28 14:38:17,827] {spark_submit.py:514} INFO - 21/12/28 14:38:17 INFO SparkContext: Running Spark version 3.2.0
[2021-12-28 14:38:17,929] {spark_submit.py:514} INFO - 21/12/28 14:38:17 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2021-12-28 14:38:18,111] {spark_submit.py:514} INFO - 21/12/28 14:38:18 INFO ResourceUtils: ==============================================================
[2021-12-28 14:38:18,112] {spark_submit.py:514} INFO - 21/12/28 14:38:18 INFO ResourceUtils: No custom resources configured for spark.driver.
[2021-12-28 14:38:18,113] {spark_submit.py:514} INFO - 21/12/28 14:38:18 INFO ResourceUtils: ==============================================================
[2021-12-28 14:38:18,114] {spark_submit.py:514} INFO - 21/12/28 14:38:18 INFO SparkContext: Submitted application: Get Ads per county
[2021-12-28 14:38:18,143] {spark_submit.py:514} INFO - 21/12/28 14:38:18 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2021-12-28 14:38:18,157] {spark_submit.py:514} INFO - 21/12/28 14:38:18 INFO ResourceProfile: Limiting resource is cpu
[2021-12-28 14:38:18,158] {spark_submit.py:514} INFO - 21/12/28 14:38:18 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2021-12-28 14:38:18,235] {spark_submit.py:514} INFO - 21/12/28 14:38:18 INFO SecurityManager: Changing view acls to: ***
[2021-12-28 14:38:18,237] {spark_submit.py:514} INFO - 21/12/28 14:38:18 INFO SecurityManager: Changing modify acls to: ***
[2021-12-28 14:38:18,238] {spark_submit.py:514} INFO - 21/12/28 14:38:18 INFO SecurityManager: Changing view acls groups to:
[2021-12-28 14:38:18,239] {spark_submit.py:514} INFO - 21/12/28 14:38:18 INFO SecurityManager: Changing modify acls groups to:
[2021-12-28 14:38:18,240] {spark_submit.py:514} INFO - 21/12/28 14:38:18 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(***); groups with view permissions: Set(); users  with modify permissions: Set(***); groups with modify permissions: Set()
[2021-12-28 14:38:18,695] {spark_submit.py:514} INFO - 21/12/28 14:38:18 INFO Utils: Successfully started service 'sparkDriver' on port 34829.
[2021-12-28 14:38:18,747] {spark_submit.py:514} INFO - 21/12/28 14:38:18 INFO SparkEnv: Registering MapOutputTracker
[2021-12-28 14:38:18,800] {spark_submit.py:514} INFO - 21/12/28 14:38:18 INFO SparkEnv: Registering BlockManagerMaster
[2021-12-28 14:38:18,831] {spark_submit.py:514} INFO - 21/12/28 14:38:18 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2021-12-28 14:38:18,833] {spark_submit.py:514} INFO - 21/12/28 14:38:18 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2021-12-28 14:38:18,841] {spark_submit.py:514} INFO - 21/12/28 14:38:18 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2021-12-28 14:38:18,875] {spark_submit.py:514} INFO - 21/12/28 14:38:18 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-384ae7de-4c87-4e12-8c2f-8b325963ccb5
[2021-12-28 14:38:18,900] {spark_submit.py:514} INFO - 21/12/28 14:38:18 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2021-12-28 14:38:18,921] {spark_submit.py:514} INFO - 21/12/28 14:38:18 INFO SparkEnv: Registering OutputCommitCoordinator
[2021-12-28 14:38:19,293] {spark_submit.py:514} INFO - 21/12/28 14:38:19 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2021-12-28 14:38:19,430] {spark_submit.py:514} INFO - 21/12/28 14:38:19 INFO SparkUI: Bound SparkUI to 0.0.0.0, and started at http://0c125a5bba95:4040
[2021-12-28 14:38:19,781] {spark_submit.py:514} INFO - 21/12/28 14:38:19 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2021-12-28 14:38:19,924] {spark_submit.py:514} INFO - 21/12/28 14:38:19 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master spark:7077
[2021-12-28 14:38:19,925] {spark_submit.py:514} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2021-12-28 14:38:19,926] {spark_submit.py:514} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:301)
[2021-12-28 14:38:19,927] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2021-12-28 14:38:19,928] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:101)
[2021-12-28 14:38:19,929] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:109)
[2021-12-28 14:38:19,930] {spark_submit.py:514} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:107)
[2021-12-28 14:38:19,932] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2021-12-28 14:38:19,932] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2021-12-28 14:38:19,933] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2021-12-28 14:38:19,934] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2021-12-28 14:38:19,934] {spark_submit.py:514} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-28 14:38:19,935] {spark_submit.py:514} INFO - Caused by: java.io.IOException: Failed to connect to spark:7077
[2021-12-28 14:38:19,936] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:288)
[2021-12-28 14:38:19,937] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:218)
[2021-12-28 14:38:19,938] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:230)
[2021-12-28 14:38:19,938] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2021-12-28 14:38:19,939] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2021-12-28 14:38:19,940] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2021-12-28 14:38:19,941] {spark_submit.py:514} INFO - ... 4 more
[2021-12-28 14:38:19,941] {spark_submit.py:514} INFO - Caused by: java.net.UnknownHostException: spark
[2021-12-28 14:38:19,942] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
[2021-12-28 14:38:19,943] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509)
[2021-12-28 14:38:19,944] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1368)
[2021-12-28 14:38:19,945] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1302)
[2021-12-28 14:38:19,946] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getByName(InetAddress.java:1252)
[2021-12-28 14:38:19,946] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156)
[2021-12-28 14:38:19,947] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153)
[2021-12-28 14:38:19,948] {spark_submit.py:514} INFO - at java.base/java.security.AccessController.doPrivileged(Native Method)
[2021-12-28 14:38:19,949] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153)
[2021-12-28 14:38:19,949] {spark_submit.py:514} INFO - at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41)
[2021-12-28 14:38:19,950] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
[2021-12-28 14:38:19,951] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53)
[2021-12-28 14:38:19,951] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
[2021-12-28 14:38:19,952] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
[2021-12-28 14:38:19,953] {spark_submit.py:514} INFO - at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
[2021-12-28 14:38:19,954] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:206)
[2021-12-28 14:38:19,954] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46)
[2021-12-28 14:38:19,955] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:180)
[2021-12-28 14:38:19,956] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:166)
[2021-12-28 14:38:19,957] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
[2021-12-28 14:38:19,958] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
[2021-12-28 14:38:19,958] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
[2021-12-28 14:38:19,959] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
[2021-12-28 14:38:19,960] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
[2021-12-28 14:38:19,960] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
[2021-12-28 14:38:19,961] {spark_submit.py:514} INFO - at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
[2021-12-28 14:38:19,962] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:1008)
[2021-12-28 14:38:19,962] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:516)
[2021-12-28 14:38:19,963] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
[2021-12-28 14:38:19,963] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
[2021-12-28 14:38:19,964] {spark_submit.py:514} INFO - at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[2021-12-28 14:38:19,965] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
[2021-12-28 14:38:19,965] {spark_submit.py:514} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[2021-12-28 14:38:19,966] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[2021-12-28 14:38:19,967] {spark_submit.py:514} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2021-12-28 14:38:19,967] {spark_submit.py:514} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2021-12-28 14:38:19,968] {spark_submit.py:514} INFO - ... 1 more
[2021-12-28 14:38:39,751] {spark_submit.py:514} INFO - 21/12/28 14:38:39 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2021-12-28 14:38:39,774] {spark_submit.py:514} INFO - 21/12/28 14:38:39 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master spark:7077
[2021-12-28 14:38:39,775] {spark_submit.py:514} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2021-12-28 14:38:39,776] {spark_submit.py:514} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:301)
[2021-12-28 14:38:39,777] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2021-12-28 14:38:39,778] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:101)
[2021-12-28 14:38:39,779] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:109)
[2021-12-28 14:38:39,780] {spark_submit.py:514} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:107)
[2021-12-28 14:38:39,781] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2021-12-28 14:38:39,782] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2021-12-28 14:38:39,783] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2021-12-28 14:38:39,785] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2021-12-28 14:38:39,786] {spark_submit.py:514} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-28 14:38:39,787] {spark_submit.py:514} INFO - Caused by: java.io.IOException: Failed to connect to spark:7077
[2021-12-28 14:38:39,788] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:288)
[2021-12-28 14:38:39,788] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:218)
[2021-12-28 14:38:39,789] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:230)
[2021-12-28 14:38:39,790] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2021-12-28 14:38:39,791] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2021-12-28 14:38:39,791] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2021-12-28 14:38:39,792] {spark_submit.py:514} INFO - ... 4 more
[2021-12-28 14:38:39,793] {spark_submit.py:514} INFO - Caused by: java.net.UnknownHostException: spark
[2021-12-28 14:38:39,794] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
[2021-12-28 14:38:39,795] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509)
[2021-12-28 14:38:39,795] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1368)
[2021-12-28 14:38:39,796] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1302)
[2021-12-28 14:38:39,797] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getByName(InetAddress.java:1252)
[2021-12-28 14:38:39,798] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156)
[2021-12-28 14:38:39,799] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153)
[2021-12-28 14:38:39,799] {spark_submit.py:514} INFO - at java.base/java.security.AccessController.doPrivileged(Native Method)
[2021-12-28 14:38:39,800] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153)
[2021-12-28 14:38:39,801] {spark_submit.py:514} INFO - at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41)
[2021-12-28 14:38:39,801] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
[2021-12-28 14:38:39,802] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53)
[2021-12-28 14:38:39,803] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
[2021-12-28 14:38:39,803] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
[2021-12-28 14:38:39,804] {spark_submit.py:514} INFO - at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
[2021-12-28 14:38:39,805] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:206)
[2021-12-28 14:38:39,806] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46)
[2021-12-28 14:38:39,806] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:180)
[2021-12-28 14:38:39,807] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:166)
[2021-12-28 14:38:39,808] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
[2021-12-28 14:38:39,809] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
[2021-12-28 14:38:39,810] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
[2021-12-28 14:38:39,811] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
[2021-12-28 14:38:39,812] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
[2021-12-28 14:38:39,813] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
[2021-12-28 14:38:39,814] {spark_submit.py:514} INFO - at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
[2021-12-28 14:38:39,818] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:1008)
[2021-12-28 14:38:39,819] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:516)
[2021-12-28 14:38:39,820] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
[2021-12-28 14:38:39,821] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
[2021-12-28 14:38:39,822] {spark_submit.py:514} INFO - at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[2021-12-28 14:38:39,823] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
[2021-12-28 14:38:39,824] {spark_submit.py:514} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[2021-12-28 14:38:39,825] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[2021-12-28 14:38:39,826] {spark_submit.py:514} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2021-12-28 14:38:39,826] {spark_submit.py:514} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2021-12-28 14:38:39,827] {spark_submit.py:514} INFO - ... 1 more
[2021-12-28 14:38:59,752] {spark_submit.py:514} INFO - 21/12/28 14:38:59 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2021-12-28 14:38:59,770] {spark_submit.py:514} INFO - 21/12/28 14:38:59 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master spark:7077
[2021-12-28 14:38:59,771] {spark_submit.py:514} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2021-12-28 14:38:59,771] {spark_submit.py:514} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:301)
[2021-12-28 14:38:59,772] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2021-12-28 14:38:59,773] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:101)
[2021-12-28 14:38:59,773] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:109)
[2021-12-28 14:38:59,774] {spark_submit.py:514} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:107)
[2021-12-28 14:38:59,775] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2021-12-28 14:38:59,776] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2021-12-28 14:38:59,777] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2021-12-28 14:38:59,777] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2021-12-28 14:38:59,778] {spark_submit.py:514} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-28 14:38:59,778] {spark_submit.py:514} INFO - Caused by: java.io.IOException: Failed to connect to spark:7077
[2021-12-28 14:38:59,780] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:288)
[2021-12-28 14:38:59,780] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:218)
[2021-12-28 14:38:59,781] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:230)
[2021-12-28 14:38:59,781] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2021-12-28 14:38:59,782] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2021-12-28 14:38:59,782] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2021-12-28 14:38:59,783] {spark_submit.py:514} INFO - ... 4 more
[2021-12-28 14:38:59,783] {spark_submit.py:514} INFO - Caused by: java.net.UnknownHostException: spark
[2021-12-28 14:38:59,784] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
[2021-12-28 14:38:59,785] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509)
[2021-12-28 14:38:59,785] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1368)
[2021-12-28 14:38:59,786] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1302)
[2021-12-28 14:38:59,786] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getByName(InetAddress.java:1252)
[2021-12-28 14:38:59,787] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156)
[2021-12-28 14:38:59,788] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153)
[2021-12-28 14:38:59,788] {spark_submit.py:514} INFO - at java.base/java.security.AccessController.doPrivileged(Native Method)
[2021-12-28 14:38:59,789] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153)
[2021-12-28 14:38:59,789] {spark_submit.py:514} INFO - at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41)
[2021-12-28 14:38:59,790] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
[2021-12-28 14:38:59,790] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53)
[2021-12-28 14:38:59,791] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
[2021-12-28 14:38:59,792] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
[2021-12-28 14:38:59,793] {spark_submit.py:514} INFO - at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
[2021-12-28 14:38:59,793] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:206)
[2021-12-28 14:38:59,794] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46)
[2021-12-28 14:38:59,794] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:180)
[2021-12-28 14:38:59,795] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:166)
[2021-12-28 14:38:59,795] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
[2021-12-28 14:38:59,796] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
[2021-12-28 14:38:59,796] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
[2021-12-28 14:38:59,797] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
[2021-12-28 14:38:59,797] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
[2021-12-28 14:38:59,799] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
[2021-12-28 14:38:59,799] {spark_submit.py:514} INFO - at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
[2021-12-28 14:38:59,800] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:1008)
[2021-12-28 14:38:59,800] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:516)
[2021-12-28 14:38:59,801] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
[2021-12-28 14:38:59,801] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
[2021-12-28 14:38:59,802] {spark_submit.py:514} INFO - at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[2021-12-28 14:38:59,802] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
[2021-12-28 14:38:59,803] {spark_submit.py:514} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[2021-12-28 14:38:59,803] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[2021-12-28 14:38:59,804] {spark_submit.py:514} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2021-12-28 14:38:59,804] {spark_submit.py:514} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2021-12-28 14:38:59,805] {spark_submit.py:514} INFO - ... 1 more
[2021-12-28 14:39:19,718] {spark_submit.py:514} INFO - 21/12/28 14:39:19 ERROR StandaloneSchedulerBackend: Application has been killed. Reason: All masters are unresponsive! Giving up.
[2021-12-28 14:39:19,720] {spark_submit.py:514} INFO - 21/12/28 14:39:19 WARN StandaloneSchedulerBackend: Application ID is not initialized yet.
[2021-12-28 14:39:19,731] {spark_submit.py:514} INFO - 21/12/28 14:39:19 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 42075.
[2021-12-28 14:39:19,732] {spark_submit.py:514} INFO - 21/12/28 14:39:19 INFO NettyBlockTransferService: Server created on 0c125a5bba95:42075
[2021-12-28 14:39:19,734] {spark_submit.py:514} INFO - 21/12/28 14:39:19 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2021-12-28 14:39:19,739] {spark_submit.py:514} INFO - 21/12/28 14:39:19 INFO SparkUI: Stopped Spark web UI at http://0c125a5bba95:4040
[2021-12-28 14:39:19,744] {spark_submit.py:514} INFO - 21/12/28 14:39:19 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 0c125a5bba95, 42075, None)
[2021-12-28 14:39:19,749] {spark_submit.py:514} INFO - 21/12/28 14:39:19 INFO StandaloneSchedulerBackend: Shutting down all executors
[2021-12-28 14:39:19,750] {spark_submit.py:514} INFO - 21/12/28 14:39:19 INFO BlockManagerMasterEndpoint: Registering block manager 0c125a5bba95:42075 with 434.4 MiB RAM, BlockManagerId(driver, 0c125a5bba95, 42075, None)
[2021-12-28 14:39:19,753] {spark_submit.py:514} INFO - 21/12/28 14:39:19 INFO CoarseGrainedSchedulerBackend$DriverEndpoint: Asking each executor to shut down
[2021-12-28 14:39:19,754] {spark_submit.py:514} INFO - 21/12/28 14:39:19 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 0c125a5bba95, 42075, None)
[2021-12-28 14:39:19,755] {spark_submit.py:514} INFO - 21/12/28 14:39:19 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 0c125a5bba95, 42075, None)
[2021-12-28 14:39:19,759] {spark_submit.py:514} INFO - 21/12/28 14:39:19 WARN StandaloneAppClient$ClientEndpoint: Drop UnregisterApplication(null) because has not yet connected to master
[2021-12-28 14:39:19,775] {spark_submit.py:514} INFO - 21/12/28 14:39:19 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2021-12-28 14:39:19,793] {spark_submit.py:514} INFO - 21/12/28 14:39:19 INFO MemoryStore: MemoryStore cleared
[2021-12-28 14:39:19,794] {spark_submit.py:514} INFO - 21/12/28 14:39:19 INFO BlockManager: BlockManager stopped
[2021-12-28 14:39:19,805] {spark_submit.py:514} INFO - 21/12/28 14:39:19 INFO BlockManagerMaster: BlockManagerMaster stopped
[2021-12-28 14:39:19,808] {spark_submit.py:514} INFO - 21/12/28 14:39:19 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2021-12-28 14:39:19,824] {spark_submit.py:514} INFO - 21/12/28 14:39:19 INFO SparkContext: Successfully stopped SparkContext
[2021-12-28 14:39:19,947] {spark_submit.py:514} INFO - 21/12/28 14:39:19 ERROR SparkContext: Error initializing SparkContext.
[2021-12-28 14:39:19,948] {spark_submit.py:514} INFO - java.lang.IllegalArgumentException: requirement failed: Can only call getServletHandlers on a running MetricsSystem
[2021-12-28 14:39:19,949] {spark_submit.py:514} INFO - at scala.Predef$.require(Predef.scala:281)
[2021-12-28 14:39:19,950] {spark_submit.py:514} INFO - at org.apache.spark.metrics.MetricsSystem.getServletHandlers(MetricsSystem.scala:89)
[2021-12-28 14:39:19,950] {spark_submit.py:514} INFO - at org.apache.spark.SparkContext.<init>(SparkContext.scala:603)
[2021-12-28 14:39:19,951] {spark_submit.py:514} INFO - at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2021-12-28 14:39:19,952] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2021-12-28 14:39:19,953] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2021-12-28 14:39:19,953] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2021-12-28 14:39:19,954] {spark_submit.py:514} INFO - at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[2021-12-28 14:39:19,955] {spark_submit.py:514} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2021-12-28 14:39:19,955] {spark_submit.py:514} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2021-12-28 14:39:19,956] {spark_submit.py:514} INFO - at py4j.Gateway.invoke(Gateway.java:238)
[2021-12-28 14:39:19,957] {spark_submit.py:514} INFO - at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2021-12-28 14:39:19,958] {spark_submit.py:514} INFO - at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2021-12-28 14:39:19,959] {spark_submit.py:514} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2021-12-28 14:39:19,960] {spark_submit.py:514} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2021-12-28 14:39:19,960] {spark_submit.py:514} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-28 14:39:19,961] {spark_submit.py:514} INFO - 21/12/28 14:39:19 INFO SparkContext: SparkContext already stopped.
[2021-12-28 14:39:19,962] {spark_submit.py:514} INFO - Traceback (most recent call last):
[2021-12-28 14:39:19,962] {spark_submit.py:514} INFO - File "/opt/***/jobs/get_ads_per_county.py", line 13, in <module>
[2021-12-28 14:39:19,963] {spark_submit.py:514} INFO - .appName("Get Ads per county") \
[2021-12-28 14:39:19,964] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/session.py", line 228, in getOrCreate
[2021-12-28 14:39:19,964] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 392, in getOrCreate
[2021-12-28 14:39:19,965] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 147, in __init__
[2021-12-28 14:39:19,966] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 209, in _do_init
[2021-12-28 14:39:19,967] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 329, in _initialize_context
[2021-12-28 14:39:19,968] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/py4j-0.10.9.2-src.zip/py4j/java_gateway.py", line 1574, in __call__
[2021-12-28 14:39:19,968] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/py4j-0.10.9.2-src.zip/py4j/protocol.py", line 328, in get_return_value
[2021-12-28 14:39:19,969] {spark_submit.py:514} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling None.org.apache.spark.api.java.JavaSparkContext.
[2021-12-28 14:39:19,970] {spark_submit.py:514} INFO - : java.lang.IllegalArgumentException: requirement failed: Can only call getServletHandlers on a running MetricsSystem
[2021-12-28 14:39:19,970] {spark_submit.py:514} INFO - at scala.Predef$.require(Predef.scala:281)
[2021-12-28 14:39:19,971] {spark_submit.py:514} INFO - at org.apache.spark.metrics.MetricsSystem.getServletHandlers(MetricsSystem.scala:89)
[2021-12-28 14:39:19,972] {spark_submit.py:514} INFO - at org.apache.spark.SparkContext.<init>(SparkContext.scala:603)
[2021-12-28 14:39:19,972] {spark_submit.py:514} INFO - at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2021-12-28 14:39:19,973] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2021-12-28 14:39:19,974] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2021-12-28 14:39:19,975] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2021-12-28 14:39:19,975] {spark_submit.py:514} INFO - at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[2021-12-28 14:39:19,976] {spark_submit.py:514} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2021-12-28 14:39:19,977] {spark_submit.py:514} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2021-12-28 14:39:19,978] {spark_submit.py:514} INFO - at py4j.Gateway.invoke(Gateway.java:238)
[2021-12-28 14:39:19,979] {spark_submit.py:514} INFO - at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2021-12-28 14:39:19,979] {spark_submit.py:514} INFO - at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2021-12-28 14:39:19,980] {spark_submit.py:514} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2021-12-28 14:39:19,981] {spark_submit.py:514} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2021-12-28 14:39:19,982] {spark_submit.py:514} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-28 14:39:19,982] {spark_submit.py:514} INFO - 
[2021-12-28 14:39:20,042] {spark_submit.py:514} INFO - 21/12/28 14:39:20 INFO ShutdownHookManager: Shutdown hook called
[2021-12-28 14:39:20,044] {spark_submit.py:514} INFO - 21/12/28 14:39:20 INFO ShutdownHookManager: Deleting directory /tmp/spark-ea5dfcc6-d80c-4d47-99ba-2530db26fe67
[2021-12-28 14:39:20,049] {spark_submit.py:514} INFO - 21/12/28 14:39:20 INFO ShutdownHookManager: Deleting directory /tmp/spark-e9c234a0-32a0-4c1c-a906-27cc5ec4f5ce
[2021-12-28 14:39:20,160] {taskinstance.py:1703} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 179, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 446, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark:7077 --conf spark.master=spark://spark:7077 --name scrap data --verbose /opt/***/jobs/get_ads_per_county.py carlow. Error code is: 1.
[2021-12-28 14:39:20,167] {taskinstance.py:1280} INFO - Marking task as UP_FOR_RETRY. dag_id=scraping_daft_carlow, task_id=scrap_data, execution_date=20211228T143811, start_date=20211228T143814, end_date=20211228T143920
[2021-12-28 14:39:20,189] {standard_task_runner.py:91} ERROR - Failed to execute job 5131 for task scrap_data
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 179, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 446, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark:7077 --conf spark.master=spark://spark:7077 --name scrap data --verbose /opt/***/jobs/get_ads_per_county.py carlow. Error code is: 1.
[2021-12-28 14:39:20,220] {local_task_job.py:154} INFO - Task exited with return code 1
[2021-12-28 14:39:20,317] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
