[2021-12-28 14:44:21,655] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: scraping_daft_carlow.scrap_data manual__2021-12-28T14:38:11.745181+00:00 [queued]>
[2021-12-28 14:44:21,680] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: scraping_daft_carlow.scrap_data manual__2021-12-28T14:38:11.745181+00:00 [queued]>
[2021-12-28 14:44:21,681] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-28 14:44:21,682] {taskinstance.py:1242} INFO - Starting attempt 2 of 4
[2021-12-28 14:44:21,683] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-28 14:44:21,710] {taskinstance.py:1262} INFO - Executing <Task(SparkSubmitOperator): scrap_data> on 2021-12-28 14:38:11.745181+00:00
[2021-12-28 14:44:21,722] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'scraping_daft_carlow', 'scrap_data', 'manual__2021-12-28T14:38:11.745181+00:00', '--job-id', '5134', '--raw', '--subdir', 'DAGS_FOLDER/scraping_daft_carlow.py', '--cfg-path', '/tmp/tmp7e5ttf_m', '--error-file', '/tmp/tmp9y2_mytg']
[2021-12-28 14:44:21,724] {standard_task_runner.py:77} INFO - Job 5134: Subtask scrap_data
[2021-12-28 14:44:21,718] {standard_task_runner.py:52} INFO - Started process 60258 to run task
[2021-12-28 14:44:21,844] {logging_mixin.py:109} INFO - Running <TaskInstance: scraping_daft_carlow.scrap_data manual__2021-12-28T14:38:11.745181+00:00 [running]> on host 0c125a5bba95
[2021-12-28 14:44:21,999] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=clement.liscoet@gmail.com
AIRFLOW_CTX_DAG_OWNER=clemoni
AIRFLOW_CTX_DAG_ID=scraping_daft_carlow
AIRFLOW_CTX_TASK_ID=scrap_data
AIRFLOW_CTX_EXECUTION_DATE=2021-12-28T14:38:11.745181+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-12-28T14:38:11.745181+00:00
[2021-12-28 14:44:22,033] {base.py:79} INFO - Using connection to: id: spark_default. Host: spark://spark:7077, Port: None, Schema: , Login: ***, Password: ***, extra: {}
[2021-12-28 14:44:22,036] {spark_submit.py:360} INFO - Spark-Submit cmd: spark-submit --master spark://spark:7077 --conf spark.master=spark://spark:7077 --name scrap data --verbose /opt/***/jobs/get_ads_per_county.py carlow
[2021-12-28 14:44:23,807] {spark_submit.py:514} INFO - Using properties file: null
[2021-12-28 14:44:23,915] {spark_submit.py:514} INFO - WARNING: An illegal reflective access operation has occurred
[2021-12-28 14:44:23,916] {spark_submit.py:514} INFO - WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/home/***/.local/lib/python3.6/site-packages/pyspark/jars/spark-unsafe_2.12-3.2.0.jar) to constructor java.nio.DirectByteBuffer(long,int)
[2021-12-28 14:44:23,917] {spark_submit.py:514} INFO - WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
[2021-12-28 14:44:23,918] {spark_submit.py:514} INFO - WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[2021-12-28 14:44:23,919] {spark_submit.py:514} INFO - WARNING: All illegal access operations will be denied in a future release
[2021-12-28 14:44:23,973] {spark_submit.py:514} INFO - Parsed arguments:
[2021-12-28 14:44:23,974] {spark_submit.py:514} INFO - master                  spark://spark:7077
[2021-12-28 14:44:23,976] {spark_submit.py:514} INFO - deployMode              null
[2021-12-28 14:44:23,976] {spark_submit.py:514} INFO - executorMemory          null
[2021-12-28 14:44:23,977] {spark_submit.py:514} INFO - executorCores           null
[2021-12-28 14:44:23,978] {spark_submit.py:514} INFO - totalExecutorCores      null
[2021-12-28 14:44:23,978] {spark_submit.py:514} INFO - propertiesFile          null
[2021-12-28 14:44:23,979] {spark_submit.py:514} INFO - driverMemory            null
[2021-12-28 14:44:23,980] {spark_submit.py:514} INFO - driverCores             null
[2021-12-28 14:44:23,980] {spark_submit.py:514} INFO - driverExtraClassPath    null
[2021-12-28 14:44:23,981] {spark_submit.py:514} INFO - driverExtraLibraryPath  null
[2021-12-28 14:44:23,983] {spark_submit.py:514} INFO - driverExtraJavaOptions  null
[2021-12-28 14:44:23,983] {spark_submit.py:514} INFO - supervise               false
[2021-12-28 14:44:23,984] {spark_submit.py:514} INFO - queue                   null
[2021-12-28 14:44:23,985] {spark_submit.py:514} INFO - numExecutors            null
[2021-12-28 14:44:23,985] {spark_submit.py:514} INFO - files                   null
[2021-12-28 14:44:23,986] {spark_submit.py:514} INFO - pyFiles                 null
[2021-12-28 14:44:23,987] {spark_submit.py:514} INFO - archives                null
[2021-12-28 14:44:23,987] {spark_submit.py:514} INFO - mainClass               null
[2021-12-28 14:44:23,988] {spark_submit.py:514} INFO - primaryResource         file:/opt/***/jobs/get_ads_per_county.py
[2021-12-28 14:44:23,988] {spark_submit.py:514} INFO - name                    scrap data
[2021-12-28 14:44:23,989] {spark_submit.py:514} INFO - childArgs               [carlow]
[2021-12-28 14:44:23,990] {spark_submit.py:514} INFO - jars                    null
[2021-12-28 14:44:23,990] {spark_submit.py:514} INFO - packages                null
[2021-12-28 14:44:23,991] {spark_submit.py:514} INFO - packagesExclusions      null
[2021-12-28 14:44:23,991] {spark_submit.py:514} INFO - repositories            null
[2021-12-28 14:44:23,992] {spark_submit.py:514} INFO - verbose                 true
[2021-12-28 14:44:23,993] {spark_submit.py:514} INFO - 
[2021-12-28 14:44:23,993] {spark_submit.py:514} INFO - Spark properties used, including those specified through
[2021-12-28 14:44:23,994] {spark_submit.py:514} INFO - --conf and those from the properties file null:
[2021-12-28 14:44:23,994] {spark_submit.py:514} INFO - (spark.master,spark://spark:7077)
[2021-12-28 14:44:23,995] {spark_submit.py:514} INFO - 
[2021-12-28 14:44:23,995] {spark_submit.py:514} INFO - 
[2021-12-28 14:44:24,294] {spark_submit.py:514} INFO - Main class:
[2021-12-28 14:44:24,295] {spark_submit.py:514} INFO - org.apache.spark.deploy.PythonRunner
[2021-12-28 14:44:24,296] {spark_submit.py:514} INFO - Arguments:
[2021-12-28 14:44:24,296] {spark_submit.py:514} INFO - file:/opt/***/jobs/get_ads_per_county.py
[2021-12-28 14:44:24,297] {spark_submit.py:514} INFO - null
[2021-12-28 14:44:24,298] {spark_submit.py:514} INFO - carlow
[2021-12-28 14:44:24,299] {spark_submit.py:514} INFO - --verbose
[2021-12-28 14:44:24,299] {spark_submit.py:514} INFO - Spark config:
[2021-12-28 14:44:24,300] {spark_submit.py:514} INFO - (spark.app.name,scrap data)
[2021-12-28 14:44:24,301] {spark_submit.py:514} INFO - (spark.master,spark://spark:7077)
[2021-12-28 14:44:24,301] {spark_submit.py:514} INFO - (spark.submit.pyFiles,)
[2021-12-28 14:44:24,302] {spark_submit.py:514} INFO - (spark.submit.deployMode,client)
[2021-12-28 14:44:24,303] {spark_submit.py:514} INFO - Classpath elements:
[2021-12-28 14:44:24,303] {spark_submit.py:514} INFO - 
[2021-12-28 14:44:24,304] {spark_submit.py:514} INFO - 
[2021-12-28 14:44:24,305] {spark_submit.py:514} INFO - 
[2021-12-28 14:44:25,277] {spark_submit.py:514} INFO - Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
[2021-12-28 14:44:25,290] {spark_submit.py:514} INFO - 21/12/28 14:44:25 INFO SparkContext: Running Spark version 3.2.0
[2021-12-28 14:44:25,391] {spark_submit.py:514} INFO - 21/12/28 14:44:25 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2021-12-28 14:44:25,567] {spark_submit.py:514} INFO - 21/12/28 14:44:25 INFO ResourceUtils: ==============================================================
[2021-12-28 14:44:25,568] {spark_submit.py:514} INFO - 21/12/28 14:44:25 INFO ResourceUtils: No custom resources configured for spark.driver.
[2021-12-28 14:44:25,569] {spark_submit.py:514} INFO - 21/12/28 14:44:25 INFO ResourceUtils: ==============================================================
[2021-12-28 14:44:25,570] {spark_submit.py:514} INFO - 21/12/28 14:44:25 INFO SparkContext: Submitted application: Get Ads per county
[2021-12-28 14:44:25,598] {spark_submit.py:514} INFO - 21/12/28 14:44:25 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2021-12-28 14:44:25,611] {spark_submit.py:514} INFO - 21/12/28 14:44:25 INFO ResourceProfile: Limiting resource is cpu
[2021-12-28 14:44:25,612] {spark_submit.py:514} INFO - 21/12/28 14:44:25 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2021-12-28 14:44:25,675] {spark_submit.py:514} INFO - 21/12/28 14:44:25 INFO SecurityManager: Changing view acls to: ***
[2021-12-28 14:44:25,677] {spark_submit.py:514} INFO - 21/12/28 14:44:25 INFO SecurityManager: Changing modify acls to: ***
[2021-12-28 14:44:25,677] {spark_submit.py:514} INFO - 21/12/28 14:44:25 INFO SecurityManager: Changing view acls groups to:
[2021-12-28 14:44:25,678] {spark_submit.py:514} INFO - 21/12/28 14:44:25 INFO SecurityManager: Changing modify acls groups to:
[2021-12-28 14:44:25,679] {spark_submit.py:514} INFO - 21/12/28 14:44:25 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(***); groups with view permissions: Set(); users  with modify permissions: Set(***); groups with modify permissions: Set()
[2021-12-28 14:44:26,048] {spark_submit.py:514} INFO - 21/12/28 14:44:26 INFO Utils: Successfully started service 'sparkDriver' on port 44767.
[2021-12-28 14:44:26,099] {spark_submit.py:514} INFO - 21/12/28 14:44:26 INFO SparkEnv: Registering MapOutputTracker
[2021-12-28 14:44:26,158] {spark_submit.py:514} INFO - 21/12/28 14:44:26 INFO SparkEnv: Registering BlockManagerMaster
[2021-12-28 14:44:26,199] {spark_submit.py:514} INFO - 21/12/28 14:44:26 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2021-12-28 14:44:26,201] {spark_submit.py:514} INFO - 21/12/28 14:44:26 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2021-12-28 14:44:26,208] {spark_submit.py:514} INFO - 21/12/28 14:44:26 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2021-12-28 14:44:26,246] {spark_submit.py:514} INFO - 21/12/28 14:44:26 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-583254c5-fcca-4e45-9f4d-52bd44dad27f
[2021-12-28 14:44:26,275] {spark_submit.py:514} INFO - 21/12/28 14:44:26 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2021-12-28 14:44:26,301] {spark_submit.py:514} INFO - 21/12/28 14:44:26 INFO SparkEnv: Registering OutputCommitCoordinator
[2021-12-28 14:44:26,662] {spark_submit.py:514} INFO - 21/12/28 14:44:26 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2021-12-28 14:44:26,752] {spark_submit.py:514} INFO - 21/12/28 14:44:26 INFO SparkUI: Bound SparkUI to 0.0.0.0, and started at http://0c125a5bba95:4040
[2021-12-28 14:44:27,069] {spark_submit.py:514} INFO - 21/12/28 14:44:27 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2021-12-28 14:44:27,188] {spark_submit.py:514} INFO - 21/12/28 14:44:27 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master spark:7077
[2021-12-28 14:44:27,189] {spark_submit.py:514} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2021-12-28 14:44:27,191] {spark_submit.py:514} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:301)
[2021-12-28 14:44:27,191] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2021-12-28 14:44:27,193] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:101)
[2021-12-28 14:44:27,194] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:109)
[2021-12-28 14:44:27,196] {spark_submit.py:514} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:107)
[2021-12-28 14:44:27,197] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2021-12-28 14:44:27,199] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2021-12-28 14:44:27,203] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2021-12-28 14:44:27,209] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2021-12-28 14:44:27,211] {spark_submit.py:514} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-28 14:44:27,213] {spark_submit.py:514} INFO - Caused by: java.io.IOException: Failed to connect to spark:7077
[2021-12-28 14:44:27,214] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:288)
[2021-12-28 14:44:27,215] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:218)
[2021-12-28 14:44:27,216] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:230)
[2021-12-28 14:44:27,217] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2021-12-28 14:44:27,217] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2021-12-28 14:44:27,218] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2021-12-28 14:44:27,219] {spark_submit.py:514} INFO - ... 4 more
[2021-12-28 14:44:27,221] {spark_submit.py:514} INFO - Caused by: java.net.UnknownHostException: spark
[2021-12-28 14:44:27,221] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
[2021-12-28 14:44:27,222] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509)
[2021-12-28 14:44:27,223] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1368)
[2021-12-28 14:44:27,224] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1302)
[2021-12-28 14:44:27,225] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getByName(InetAddress.java:1252)
[2021-12-28 14:44:27,226] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156)
[2021-12-28 14:44:27,227] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153)
[2021-12-28 14:44:27,228] {spark_submit.py:514} INFO - at java.base/java.security.AccessController.doPrivileged(Native Method)
[2021-12-28 14:44:27,229] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153)
[2021-12-28 14:44:27,230] {spark_submit.py:514} INFO - at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41)
[2021-12-28 14:44:27,231] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
[2021-12-28 14:44:27,232] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53)
[2021-12-28 14:44:27,232] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
[2021-12-28 14:44:27,233] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
[2021-12-28 14:44:27,234] {spark_submit.py:514} INFO - at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
[2021-12-28 14:44:27,234] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:206)
[2021-12-28 14:44:27,235] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46)
[2021-12-28 14:44:27,236] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:180)
[2021-12-28 14:44:27,238] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:166)
[2021-12-28 14:44:27,239] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
[2021-12-28 14:44:27,240] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
[2021-12-28 14:44:27,241] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
[2021-12-28 14:44:27,242] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
[2021-12-28 14:44:27,242] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
[2021-12-28 14:44:27,244] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
[2021-12-28 14:44:27,245] {spark_submit.py:514} INFO - at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
[2021-12-28 14:44:27,246] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:1008)
[2021-12-28 14:44:27,247] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:516)
[2021-12-28 14:44:27,248] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
[2021-12-28 14:44:27,249] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
[2021-12-28 14:44:27,250] {spark_submit.py:514} INFO - at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[2021-12-28 14:44:27,251] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
[2021-12-28 14:44:27,253] {spark_submit.py:514} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[2021-12-28 14:44:27,253] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[2021-12-28 14:44:27,254] {spark_submit.py:514} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2021-12-28 14:44:27,255] {spark_submit.py:514} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2021-12-28 14:44:27,255] {spark_submit.py:514} INFO - ... 1 more
[2021-12-28 14:44:47,034] {spark_submit.py:514} INFO - 21/12/28 14:44:47 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2021-12-28 14:44:47,049] {spark_submit.py:514} INFO - 21/12/28 14:44:47 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master spark:7077
[2021-12-28 14:44:47,054] {spark_submit.py:514} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2021-12-28 14:44:47,055] {spark_submit.py:514} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:301)
[2021-12-28 14:44:47,057] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2021-12-28 14:44:47,059] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:101)
[2021-12-28 14:44:47,064] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:109)
[2021-12-28 14:44:47,064] {spark_submit.py:514} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:107)
[2021-12-28 14:44:47,065] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2021-12-28 14:44:47,066] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2021-12-28 14:44:47,067] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2021-12-28 14:44:47,068] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2021-12-28 14:44:47,070] {spark_submit.py:514} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-28 14:44:47,074] {spark_submit.py:514} INFO - Caused by: java.io.IOException: Failed to connect to spark:7077
[2021-12-28 14:44:47,075] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:288)
[2021-12-28 14:44:47,076] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:218)
[2021-12-28 14:44:47,077] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:230)
[2021-12-28 14:44:47,079] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2021-12-28 14:44:47,079] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2021-12-28 14:44:47,080] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2021-12-28 14:44:47,081] {spark_submit.py:514} INFO - ... 4 more
[2021-12-28 14:44:47,082] {spark_submit.py:514} INFO - Caused by: java.net.UnknownHostException: spark
[2021-12-28 14:44:47,083] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
[2021-12-28 14:44:47,084] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509)
[2021-12-28 14:44:47,085] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1368)
[2021-12-28 14:44:47,086] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1302)
[2021-12-28 14:44:47,087] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getByName(InetAddress.java:1252)
[2021-12-28 14:44:47,087] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156)
[2021-12-28 14:44:47,088] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153)
[2021-12-28 14:44:47,090] {spark_submit.py:514} INFO - at java.base/java.security.AccessController.doPrivileged(Native Method)
[2021-12-28 14:44:47,090] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153)
[2021-12-28 14:44:47,091] {spark_submit.py:514} INFO - at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41)
[2021-12-28 14:44:47,092] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
[2021-12-28 14:44:47,093] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53)
[2021-12-28 14:44:47,093] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
[2021-12-28 14:44:47,096] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
[2021-12-28 14:44:47,097] {spark_submit.py:514} INFO - at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
[2021-12-28 14:44:47,097] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:206)
[2021-12-28 14:44:47,098] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46)
[2021-12-28 14:44:47,099] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:180)
[2021-12-28 14:44:47,100] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:166)
[2021-12-28 14:44:47,100] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
[2021-12-28 14:44:47,101] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
[2021-12-28 14:44:47,104] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
[2021-12-28 14:44:47,105] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
[2021-12-28 14:44:47,106] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
[2021-12-28 14:44:47,107] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
[2021-12-28 14:44:47,108] {spark_submit.py:514} INFO - at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
[2021-12-28 14:44:47,109] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:1008)
[2021-12-28 14:44:47,112] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:516)
[2021-12-28 14:44:47,113] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
[2021-12-28 14:44:47,114] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
[2021-12-28 14:44:47,115] {spark_submit.py:514} INFO - at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[2021-12-28 14:44:47,117] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
[2021-12-28 14:44:47,118] {spark_submit.py:514} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[2021-12-28 14:44:47,119] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[2021-12-28 14:44:47,120] {spark_submit.py:514} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2021-12-28 14:44:47,121] {spark_submit.py:514} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2021-12-28 14:44:47,123] {spark_submit.py:514} INFO - ... 1 more
[2021-12-28 14:45:07,002] {spark_submit.py:514} INFO - 21/12/28 14:45:07 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2021-12-28 14:45:07,022] {spark_submit.py:514} INFO - 21/12/28 14:45:07 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master spark:7077
[2021-12-28 14:45:07,023] {spark_submit.py:514} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2021-12-28 14:45:07,024] {spark_submit.py:514} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:301)
[2021-12-28 14:45:07,025] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2021-12-28 14:45:07,026] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:101)
[2021-12-28 14:45:07,027] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:109)
[2021-12-28 14:45:07,028] {spark_submit.py:514} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:107)
[2021-12-28 14:45:07,029] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2021-12-28 14:45:07,030] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2021-12-28 14:45:07,030] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2021-12-28 14:45:07,031] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2021-12-28 14:45:07,032] {spark_submit.py:514} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-28 14:45:07,033] {spark_submit.py:514} INFO - Caused by: java.io.IOException: Failed to connect to spark:7077
[2021-12-28 14:45:07,035] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:288)
[2021-12-28 14:45:07,036] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:218)
[2021-12-28 14:45:07,037] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:230)
[2021-12-28 14:45:07,037] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2021-12-28 14:45:07,038] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2021-12-28 14:45:07,039] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2021-12-28 14:45:07,040] {spark_submit.py:514} INFO - ... 4 more
[2021-12-28 14:45:07,041] {spark_submit.py:514} INFO - Caused by: java.net.UnknownHostException: spark
[2021-12-28 14:45:07,041] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
[2021-12-28 14:45:07,042] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509)
[2021-12-28 14:45:07,043] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1368)
[2021-12-28 14:45:07,044] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1302)
[2021-12-28 14:45:07,044] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getByName(InetAddress.java:1252)
[2021-12-28 14:45:07,045] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156)
[2021-12-28 14:45:07,046] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153)
[2021-12-28 14:45:07,046] {spark_submit.py:514} INFO - at java.base/java.security.AccessController.doPrivileged(Native Method)
[2021-12-28 14:45:07,047] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153)
[2021-12-28 14:45:07,048] {spark_submit.py:514} INFO - at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41)
[2021-12-28 14:45:07,049] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
[2021-12-28 14:45:07,049] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53)
[2021-12-28 14:45:07,050] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
[2021-12-28 14:45:07,051] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
[2021-12-28 14:45:07,052] {spark_submit.py:514} INFO - at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
[2021-12-28 14:45:07,052] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:206)
[2021-12-28 14:45:07,053] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46)
[2021-12-28 14:45:07,054] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:180)
[2021-12-28 14:45:07,055] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:166)
[2021-12-28 14:45:07,055] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
[2021-12-28 14:45:07,056] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
[2021-12-28 14:45:07,060] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
[2021-12-28 14:45:07,061] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
[2021-12-28 14:45:07,061] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
[2021-12-28 14:45:07,063] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
[2021-12-28 14:45:07,063] {spark_submit.py:514} INFO - at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
[2021-12-28 14:45:07,064] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:1008)
[2021-12-28 14:45:07,065] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:516)
[2021-12-28 14:45:07,065] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
[2021-12-28 14:45:07,066] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
[2021-12-28 14:45:07,067] {spark_submit.py:514} INFO - at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[2021-12-28 14:45:07,067] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
[2021-12-28 14:45:07,068] {spark_submit.py:514} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[2021-12-28 14:45:07,069] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[2021-12-28 14:45:07,069] {spark_submit.py:514} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2021-12-28 14:45:07,070] {spark_submit.py:514} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2021-12-28 14:45:07,070] {spark_submit.py:514} INFO - ... 1 more
[2021-12-28 14:45:27,002] {spark_submit.py:514} INFO - 21/12/28 14:45:27 ERROR StandaloneSchedulerBackend: Application has been killed. Reason: All masters are unresponsive! Giving up.
[2021-12-28 14:45:27,005] {spark_submit.py:514} INFO - 21/12/28 14:45:27 WARN StandaloneSchedulerBackend: Application ID is not initialized yet.
[2021-12-28 14:45:27,035] {spark_submit.py:514} INFO - 21/12/28 14:45:27 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 37717.
[2021-12-28 14:45:27,036] {spark_submit.py:514} INFO - 21/12/28 14:45:27 INFO NettyBlockTransferService: Server created on 0c125a5bba95:37717
[2021-12-28 14:45:27,039] {spark_submit.py:514} INFO - 21/12/28 14:45:27 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2021-12-28 14:45:27,045] {spark_submit.py:514} INFO - 21/12/28 14:45:27 INFO SparkUI: Stopped Spark web UI at http://0c125a5bba95:4040
[2021-12-28 14:45:27,068] {spark_submit.py:514} INFO - 21/12/28 14:45:27 INFO StandaloneSchedulerBackend: Shutting down all executors
[2021-12-28 14:45:27,081] {spark_submit.py:514} INFO - 21/12/28 14:45:27 INFO CoarseGrainedSchedulerBackend$DriverEndpoint: Asking each executor to shut down
[2021-12-28 14:45:27,087] {spark_submit.py:514} INFO - 21/12/28 14:45:27 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 0c125a5bba95, 37717, None)
[2021-12-28 14:45:27,095] {spark_submit.py:514} INFO - 21/12/28 14:45:27 WARN StandaloneAppClient$ClientEndpoint: Drop UnregisterApplication(null) because has not yet connected to master
[2021-12-28 14:45:27,099] {spark_submit.py:514} INFO - 21/12/28 14:45:27 INFO BlockManagerMasterEndpoint: Registering block manager 0c125a5bba95:37717 with 434.4 MiB RAM, BlockManagerId(driver, 0c125a5bba95, 37717, None)
[2021-12-28 14:45:27,108] {spark_submit.py:514} INFO - 21/12/28 14:45:27 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 0c125a5bba95, 37717, None)
[2021-12-28 14:45:27,120] {spark_submit.py:514} INFO - 21/12/28 14:45:27 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 0c125a5bba95, 37717, None)
[2021-12-28 14:45:27,133] {spark_submit.py:514} INFO - 21/12/28 14:45:27 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2021-12-28 14:45:27,160] {spark_submit.py:514} INFO - 21/12/28 14:45:27 INFO MemoryStore: MemoryStore cleared
[2021-12-28 14:45:27,162] {spark_submit.py:514} INFO - 21/12/28 14:45:27 INFO BlockManager: BlockManager stopped
[2021-12-28 14:45:27,178] {spark_submit.py:514} INFO - 21/12/28 14:45:27 INFO BlockManagerMaster: BlockManagerMaster stopped
[2021-12-28 14:45:27,184] {spark_submit.py:514} INFO - 21/12/28 14:45:27 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2021-12-28 14:45:27,217] {spark_submit.py:514} INFO - 21/12/28 14:45:27 INFO SparkContext: Successfully stopped SparkContext
[2021-12-28 14:45:27,406] {spark_submit.py:514} INFO - 21/12/28 14:45:27 ERROR SparkContext: Error initializing SparkContext.
[2021-12-28 14:45:27,407] {spark_submit.py:514} INFO - java.lang.IllegalArgumentException: requirement failed: Can only call getServletHandlers on a running MetricsSystem
[2021-12-28 14:45:27,408] {spark_submit.py:514} INFO - at scala.Predef$.require(Predef.scala:281)
[2021-12-28 14:45:27,408] {spark_submit.py:514} INFO - at org.apache.spark.metrics.MetricsSystem.getServletHandlers(MetricsSystem.scala:89)
[2021-12-28 14:45:27,409] {spark_submit.py:514} INFO - at org.apache.spark.SparkContext.<init>(SparkContext.scala:603)
[2021-12-28 14:45:27,410] {spark_submit.py:514} INFO - at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2021-12-28 14:45:27,411] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2021-12-28 14:45:27,412] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2021-12-28 14:45:27,413] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2021-12-28 14:45:27,413] {spark_submit.py:514} INFO - at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[2021-12-28 14:45:27,414] {spark_submit.py:514} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2021-12-28 14:45:27,415] {spark_submit.py:514} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2021-12-28 14:45:27,416] {spark_submit.py:514} INFO - at py4j.Gateway.invoke(Gateway.java:238)
[2021-12-28 14:45:27,416] {spark_submit.py:514} INFO - at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2021-12-28 14:45:27,417] {spark_submit.py:514} INFO - at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2021-12-28 14:45:27,418] {spark_submit.py:514} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2021-12-28 14:45:27,419] {spark_submit.py:514} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2021-12-28 14:45:27,420] {spark_submit.py:514} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-28 14:45:27,421] {spark_submit.py:514} INFO - 21/12/28 14:45:27 INFO SparkContext: SparkContext already stopped.
[2021-12-28 14:45:27,423] {spark_submit.py:514} INFO - Traceback (most recent call last):
[2021-12-28 14:45:27,424] {spark_submit.py:514} INFO - File "/opt/***/jobs/get_ads_per_county.py", line 13, in <module>
[2021-12-28 14:45:27,425] {spark_submit.py:514} INFO - .appName("Get Ads per county") \
[2021-12-28 14:45:27,426] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/session.py", line 228, in getOrCreate
[2021-12-28 14:45:27,427] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 392, in getOrCreate
[2021-12-28 14:45:27,428] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 147, in __init__
[2021-12-28 14:45:27,429] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 209, in _do_init
[2021-12-28 14:45:27,430] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 329, in _initialize_context
[2021-12-28 14:45:27,431] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/py4j-0.10.9.2-src.zip/py4j/java_gateway.py", line 1574, in __call__
[2021-12-28 14:45:27,432] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/py4j-0.10.9.2-src.zip/py4j/protocol.py", line 328, in get_return_value
[2021-12-28 14:45:27,433] {spark_submit.py:514} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling None.org.apache.spark.api.java.JavaSparkContext.
[2021-12-28 14:45:27,434] {spark_submit.py:514} INFO - : java.lang.IllegalArgumentException: requirement failed: Can only call getServletHandlers on a running MetricsSystem
[2021-12-28 14:45:27,435] {spark_submit.py:514} INFO - at scala.Predef$.require(Predef.scala:281)
[2021-12-28 14:45:27,436] {spark_submit.py:514} INFO - at org.apache.spark.metrics.MetricsSystem.getServletHandlers(MetricsSystem.scala:89)
[2021-12-28 14:45:27,437] {spark_submit.py:514} INFO - at org.apache.spark.SparkContext.<init>(SparkContext.scala:603)
[2021-12-28 14:45:27,438] {spark_submit.py:514} INFO - at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2021-12-28 14:45:27,439] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2021-12-28 14:45:27,440] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2021-12-28 14:45:27,441] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2021-12-28 14:45:27,442] {spark_submit.py:514} INFO - at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[2021-12-28 14:45:27,443] {spark_submit.py:514} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2021-12-28 14:45:27,444] {spark_submit.py:514} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2021-12-28 14:45:27,446] {spark_submit.py:514} INFO - at py4j.Gateway.invoke(Gateway.java:238)
[2021-12-28 14:45:27,447] {spark_submit.py:514} INFO - at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2021-12-28 14:45:27,449] {spark_submit.py:514} INFO - at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2021-12-28 14:45:27,450] {spark_submit.py:514} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2021-12-28 14:45:27,452] {spark_submit.py:514} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2021-12-28 14:45:27,454] {spark_submit.py:514} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-28 14:45:27,455] {spark_submit.py:514} INFO - 
[2021-12-28 14:45:27,533] {spark_submit.py:514} INFO - 21/12/28 14:45:27 INFO ShutdownHookManager: Shutdown hook called
[2021-12-28 14:45:27,535] {spark_submit.py:514} INFO - 21/12/28 14:45:27 INFO ShutdownHookManager: Deleting directory /tmp/spark-3d2938ac-87d6-47e6-89aa-e7d4054ffc13
[2021-12-28 14:45:27,540] {spark_submit.py:514} INFO - 21/12/28 14:45:27 INFO ShutdownHookManager: Deleting directory /tmp/spark-23bf8d03-3371-494a-9e06-156f37d56fa2
[2021-12-28 14:45:27,665] {taskinstance.py:1703} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 179, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 446, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark:7077 --conf spark.master=spark://spark:7077 --name scrap data --verbose /opt/***/jobs/get_ads_per_county.py carlow. Error code is: 1.
[2021-12-28 14:45:27,673] {taskinstance.py:1280} INFO - Marking task as UP_FOR_RETRY. dag_id=scraping_daft_carlow, task_id=scrap_data, execution_date=20211228T143811, start_date=20211228T144421, end_date=20211228T144527
[2021-12-28 14:45:27,693] {standard_task_runner.py:91} ERROR - Failed to execute job 5134 for task scrap_data
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 179, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 446, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark:7077 --conf spark.master=spark://spark:7077 --name scrap data --verbose /opt/***/jobs/get_ads_per_county.py carlow. Error code is: 1.
[2021-12-28 14:45:27,728] {local_task_job.py:154} INFO - Task exited with return code 1
[2021-12-28 14:45:27,827] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
