[2021-12-28 13:33:26,396] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: scraping_daft_laois.scrap_data scheduled__2021-12-27T09:55:00+00:00 [queued]>
[2021-12-28 13:33:26,554] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: scraping_daft_laois.scrap_data scheduled__2021-12-27T09:55:00+00:00 [queued]>
[2021-12-28 13:33:26,557] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-28 13:33:26,560] {taskinstance.py:1242} INFO - Starting attempt 2 of 4
[2021-12-28 13:33:26,561] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-28 13:33:26,763] {taskinstance.py:1262} INFO - Executing <Task(SparkSubmitOperator): scrap_data> on 2021-12-27 09:55:00+00:00
[2021-12-28 13:33:26,836] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'scraping_daft_laois', 'scrap_data', 'scheduled__2021-12-27T09:55:00+00:00', '--job-id', '5077', '--raw', '--subdir', 'DAGS_FOLDER/scraping_daft_laois.py', '--cfg-path', '/tmp/tmphg6fhkm1', '--error-file', '/tmp/tmplh_ixa7q']
[2021-12-28 13:33:26,839] {standard_task_runner.py:77} INFO - Job 5077: Subtask scrap_data
[2021-12-28 13:33:26,835] {standard_task_runner.py:52} INFO - Started process 49067 to run task
[2021-12-28 13:33:27,490] {logging_mixin.py:109} INFO - Running <TaskInstance: scraping_daft_laois.scrap_data scheduled__2021-12-27T09:55:00+00:00 [running]> on host 0c125a5bba95
[2021-12-28 13:33:28,534] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=clement.liscoet@gmail.com
AIRFLOW_CTX_DAG_OWNER=clemoni
AIRFLOW_CTX_DAG_ID=scraping_daft_laois
AIRFLOW_CTX_TASK_ID=scrap_data
AIRFLOW_CTX_EXECUTION_DATE=2021-12-27T09:55:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-27T09:55:00+00:00
[2021-12-28 13:33:28,633] {base.py:79} INFO - Using connection to: id: spark_default. Host: spark://spark:7077, Port: None, Schema: , Login: ***, Password: ***, extra: {}
[2021-12-28 13:33:28,643] {spark_submit.py:360} INFO - Spark-Submit cmd: spark-submit --master spark://spark:7077 --conf spark.master=spark://spark:7077 --name scrap data --verbose /opt/***/jobs/get_ads_per_county.py laois
[2021-12-28 13:33:42,000] {spark_submit.py:514} INFO - Using properties file: null
[2021-12-28 13:33:42,602] {spark_submit.py:514} INFO - WARNING: An illegal reflective access operation has occurred
[2021-12-28 13:33:42,608] {spark_submit.py:514} INFO - WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/home/***/.local/lib/python3.6/site-packages/pyspark/jars/spark-unsafe_2.12-3.2.0.jar) to constructor java.nio.DirectByteBuffer(long,int)
[2021-12-28 13:33:42,616] {spark_submit.py:514} INFO - WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
[2021-12-28 13:33:42,621] {spark_submit.py:514} INFO - WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[2021-12-28 13:33:42,623] {spark_submit.py:514} INFO - WARNING: All illegal access operations will be denied in a future release
[2021-12-28 13:33:42,756] {spark_submit.py:514} INFO - Parsed arguments:
[2021-12-28 13:33:42,761] {spark_submit.py:514} INFO - master                  spark://spark:7077
[2021-12-28 13:33:42,763] {spark_submit.py:514} INFO - deployMode              null
[2021-12-28 13:33:42,768] {spark_submit.py:514} INFO - executorMemory          null
[2021-12-28 13:33:42,772] {spark_submit.py:514} INFO - executorCores           null
[2021-12-28 13:33:42,774] {spark_submit.py:514} INFO - totalExecutorCores      null
[2021-12-28 13:33:42,779] {spark_submit.py:514} INFO - propertiesFile          null
[2021-12-28 13:33:42,783] {spark_submit.py:514} INFO - driverMemory            null
[2021-12-28 13:33:42,786] {spark_submit.py:514} INFO - driverCores             null
[2021-12-28 13:33:42,791] {spark_submit.py:514} INFO - driverExtraClassPath    null
[2021-12-28 13:33:42,796] {spark_submit.py:514} INFO - driverExtraLibraryPath  null
[2021-12-28 13:33:42,800] {spark_submit.py:514} INFO - driverExtraJavaOptions  null
[2021-12-28 13:33:42,803] {spark_submit.py:514} INFO - supervise               false
[2021-12-28 13:33:42,809] {spark_submit.py:514} INFO - queue                   null
[2021-12-28 13:33:42,813] {spark_submit.py:514} INFO - numExecutors            null
[2021-12-28 13:33:42,815] {spark_submit.py:514} INFO - files                   null
[2021-12-28 13:33:42,818] {spark_submit.py:514} INFO - pyFiles                 null
[2021-12-28 13:33:42,820] {spark_submit.py:514} INFO - archives                null
[2021-12-28 13:33:42,822] {spark_submit.py:514} INFO - mainClass               null
[2021-12-28 13:33:42,824] {spark_submit.py:514} INFO - primaryResource         file:/opt/***/jobs/get_ads_per_county.py
[2021-12-28 13:33:42,826] {spark_submit.py:514} INFO - name                    scrap data
[2021-12-28 13:33:42,830] {spark_submit.py:514} INFO - childArgs               [laois]
[2021-12-28 13:33:42,832] {spark_submit.py:514} INFO - jars                    null
[2021-12-28 13:33:42,834] {spark_submit.py:514} INFO - packages                null
[2021-12-28 13:33:42,836] {spark_submit.py:514} INFO - packagesExclusions      null
[2021-12-28 13:33:42,839] {spark_submit.py:514} INFO - repositories            null
[2021-12-28 13:33:42,846] {spark_submit.py:514} INFO - verbose                 true
[2021-12-28 13:33:42,849] {spark_submit.py:514} INFO - 
[2021-12-28 13:33:42,853] {spark_submit.py:514} INFO - Spark properties used, including those specified through
[2021-12-28 13:33:42,858] {spark_submit.py:514} INFO - --conf and those from the properties file null:
[2021-12-28 13:33:42,863] {spark_submit.py:514} INFO - (spark.master,spark://spark:7077)
[2021-12-28 13:33:42,865] {spark_submit.py:514} INFO - 
[2021-12-28 13:33:42,866] {spark_submit.py:514} INFO - 
[2021-12-28 13:33:45,814] {spark_submit.py:514} INFO - Main class:
[2021-12-28 13:33:45,815] {spark_submit.py:514} INFO - org.apache.spark.deploy.PythonRunner
[2021-12-28 13:33:45,874] {spark_submit.py:514} INFO - Arguments:
[2021-12-28 13:33:45,876] {spark_submit.py:514} INFO - file:/opt/***/jobs/get_ads_per_county.py
[2021-12-28 13:33:45,877] {spark_submit.py:514} INFO - null
[2021-12-28 13:33:45,878] {spark_submit.py:514} INFO - laois
[2021-12-28 13:33:45,880] {spark_submit.py:514} INFO - --verbose
[2021-12-28 13:33:45,923] {spark_submit.py:514} INFO - Spark config:
[2021-12-28 13:33:45,924] {spark_submit.py:514} INFO - (spark.app.name,scrap data)
[2021-12-28 13:33:45,925] {spark_submit.py:514} INFO - (spark.master,spark://spark:7077)
[2021-12-28 13:33:45,927] {spark_submit.py:514} INFO - (spark.submit.pyFiles,)
[2021-12-28 13:33:45,928] {spark_submit.py:514} INFO - (spark.submit.deployMode,client)
[2021-12-28 13:33:45,930] {spark_submit.py:514} INFO - Classpath elements:
[2021-12-28 13:33:45,931] {spark_submit.py:514} INFO - 
[2021-12-28 13:33:45,932] {spark_submit.py:514} INFO - 
[2021-12-28 13:33:45,957] {spark_submit.py:514} INFO - 
[2021-12-28 13:33:51,849] {spark_submit.py:514} INFO - Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
[2021-12-28 13:33:52,301] {spark_submit.py:514} INFO - 21/12/28 13:33:52 INFO SparkContext: Running Spark version 3.2.0
[2021-12-28 13:33:54,949] {spark_submit.py:514} INFO - 21/12/28 13:33:54 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2021-12-28 13:33:57,835] {spark_submit.py:514} INFO - 21/12/28 13:33:57 INFO ResourceUtils: ==============================================================
[2021-12-28 13:33:57,855] {spark_submit.py:514} INFO - 21/12/28 13:33:57 INFO ResourceUtils: No custom resources configured for spark.driver.
[2021-12-28 13:33:57,892] {spark_submit.py:514} INFO - 21/12/28 13:33:57 INFO ResourceUtils: ==============================================================
[2021-12-28 13:33:57,919] {spark_submit.py:514} INFO - 21/12/28 13:33:57 INFO SparkContext: Submitted application: Get Ads per county
[2021-12-28 13:34:03,644] {spark_submit.py:514} INFO - 21/12/28 13:34:03 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2021-12-28 13:34:05,867] {spark_submit.py:514} INFO - 21/12/28 13:34:05 INFO ResourceProfile: Limiting resource is cpu
[2021-12-28 13:34:06,064] {spark_submit.py:514} INFO - 21/12/28 13:34:06 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2021-12-28 13:34:13,154] {spark_submit.py:514} INFO - 21/12/28 13:34:13 INFO SecurityManager: Changing view acls to: ***
[2021-12-28 13:34:13,162] {spark_submit.py:514} INFO - 21/12/28 13:34:13 INFO SecurityManager: Changing modify acls to: ***
[2021-12-28 13:34:13,171] {spark_submit.py:514} INFO - 21/12/28 13:34:13 INFO SecurityManager: Changing view acls groups to:
[2021-12-28 13:34:13,182] {spark_submit.py:514} INFO - 21/12/28 13:34:13 INFO SecurityManager: Changing modify acls groups to:
[2021-12-28 13:34:13,197] {spark_submit.py:514} INFO - 21/12/28 13:34:13 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(***); groups with view permissions: Set(); users  with modify permissions: Set(***); groups with modify permissions: Set()
[2021-12-28 13:34:39,431] {spark_submit.py:514} INFO - 21/12/28 13:34:39 INFO Utils: Successfully started service 'sparkDriver' on port 34233.
[2021-12-28 13:34:48,058] {spark_submit.py:514} INFO - 21/12/28 13:34:47 INFO SparkEnv: Registering MapOutputTracker
[2021-12-28 13:34:53,487] {spark_submit.py:514} INFO - 21/12/28 13:34:53 INFO SparkEnv: Registering BlockManagerMaster
[2021-12-28 13:34:55,036] {spark_submit.py:514} INFO - 21/12/28 13:34:55 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2021-12-28 13:34:55,066] {spark_submit.py:514} INFO - 21/12/28 13:34:55 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2021-12-28 13:34:55,362] {spark_submit.py:514} INFO - 21/12/28 13:34:55 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2021-12-28 13:34:58,259] {spark_submit.py:514} INFO - 21/12/28 13:34:58 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-813d6c09-04a7-4927-9463-15da17f82ef2
[2021-12-28 13:34:59,869] {spark_submit.py:514} INFO - 21/12/28 13:34:59 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2021-12-28 13:35:01,801] {spark_submit.py:514} INFO - 21/12/28 13:35:01 INFO SparkEnv: Registering OutputCommitCoordinator
[2021-12-28 13:35:18,658] {spark_submit.py:514} INFO - 21/12/28 13:35:18 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2021-12-28 13:35:18,661] {spark_submit.py:514} INFO - 21/12/28 13:35:18 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.
[2021-12-28 13:35:18,663] {spark_submit.py:514} INFO - 21/12/28 13:35:18 WARN Utils: Service 'SparkUI' could not bind on port 4042. Attempting port 4043.
[2021-12-28 13:35:18,666] {spark_submit.py:514} INFO - 21/12/28 13:35:18 WARN Utils: Service 'SparkUI' could not bind on port 4043. Attempting port 4044.
[2021-12-28 13:35:18,670] {spark_submit.py:514} INFO - 21/12/28 13:35:18 WARN Utils: Service 'SparkUI' could not bind on port 4044. Attempting port 4045.
[2021-12-28 13:35:18,673] {spark_submit.py:514} INFO - 21/12/28 13:35:18 WARN Utils: Service 'SparkUI' could not bind on port 4045. Attempting port 4046.
[2021-12-28 13:35:18,676] {spark_submit.py:514} INFO - 21/12/28 13:35:18 WARN Utils: Service 'SparkUI' could not bind on port 4046. Attempting port 4047.
[2021-12-28 13:35:18,678] {spark_submit.py:514} INFO - 21/12/28 13:35:18 WARN Utils: Service 'SparkUI' could not bind on port 4047. Attempting port 4048.
[2021-12-28 13:35:18,681] {spark_submit.py:514} INFO - 21/12/28 13:35:18 WARN Utils: Service 'SparkUI' could not bind on port 4048. Attempting port 4049.
[2021-12-28 13:35:18,686] {spark_submit.py:514} INFO - 21/12/28 13:35:18 WARN Utils: Service 'SparkUI' could not bind on port 4049. Attempting port 4050.
[2021-12-28 13:35:18,839] {spark_submit.py:514} INFO - 21/12/28 13:35:18 INFO Utils: Successfully started service 'SparkUI' on port 4050.
[2021-12-28 13:35:21,742] {spark_submit.py:514} INFO - 21/12/28 13:35:21 INFO SparkUI: Bound SparkUI to 0.0.0.0, and started at http://0c125a5bba95:4050
[2021-12-28 13:35:45,413] {spark_submit.py:514} INFO - 21/12/28 13:35:45 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2021-12-28 13:35:51,857] {spark_submit.py:514} INFO - 21/12/28 13:35:51 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master spark:7077
[2021-12-28 13:35:51,936] {spark_submit.py:514} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2021-12-28 13:35:51,938] {spark_submit.py:514} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:301)
[2021-12-28 13:35:51,939] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2021-12-28 13:35:51,944] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:101)
[2021-12-28 13:35:51,970] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:109)
[2021-12-28 13:35:51,972] {spark_submit.py:514} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:107)
[2021-12-28 13:35:51,986] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2021-12-28 13:35:51,988] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2021-12-28 13:35:51,990] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2021-12-28 13:35:51,994] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2021-12-28 13:35:51,996] {spark_submit.py:514} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-28 13:35:51,997] {spark_submit.py:514} INFO - Caused by: java.io.IOException: Failed to connect to spark:7077
[2021-12-28 13:35:52,002] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:288)
[2021-12-28 13:35:52,006] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:218)
[2021-12-28 13:35:52,007] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:230)
[2021-12-28 13:35:52,009] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2021-12-28 13:35:52,010] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2021-12-28 13:35:52,012] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2021-12-28 13:35:52,014] {spark_submit.py:514} INFO - ... 4 more
[2021-12-28 13:35:52,017] {spark_submit.py:514} INFO - Caused by: java.net.UnknownHostException: spark
[2021-12-28 13:35:52,025] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
[2021-12-28 13:35:52,111] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509)
[2021-12-28 13:35:52,122] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1368)
[2021-12-28 13:35:52,176] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1302)
[2021-12-28 13:35:52,177] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getByName(InetAddress.java:1252)
[2021-12-28 13:35:52,179] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156)
[2021-12-28 13:35:52,181] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153)
[2021-12-28 13:35:52,184] {spark_submit.py:514} INFO - at java.base/java.security.AccessController.doPrivileged(Native Method)
[2021-12-28 13:35:52,187] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153)
[2021-12-28 13:35:52,189] {spark_submit.py:514} INFO - at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41)
[2021-12-28 13:35:52,193] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
[2021-12-28 13:35:52,197] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53)
[2021-12-28 13:35:52,199] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
[2021-12-28 13:35:52,201] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
[2021-12-28 13:35:52,203] {spark_submit.py:514} INFO - at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
[2021-12-28 13:35:52,214] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:206)
[2021-12-28 13:35:52,226] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46)
[2021-12-28 13:35:52,228] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:180)
[2021-12-28 13:35:52,230] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:166)
[2021-12-28 13:35:52,232] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
[2021-12-28 13:35:52,236] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
[2021-12-28 13:35:52,239] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
[2021-12-28 13:35:52,243] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
[2021-12-28 13:35:52,247] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
[2021-12-28 13:35:52,254] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
[2021-12-28 13:35:52,272] {spark_submit.py:514} INFO - at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
[2021-12-28 13:35:52,274] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:1008)
[2021-12-28 13:35:52,285] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:516)
[2021-12-28 13:35:52,291] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
[2021-12-28 13:35:52,293] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
[2021-12-28 13:35:52,295] {spark_submit.py:514} INFO - at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[2021-12-28 13:35:52,297] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
[2021-12-28 13:35:52,300] {spark_submit.py:514} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[2021-12-28 13:35:52,301] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[2021-12-28 13:35:52,303] {spark_submit.py:514} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2021-12-28 13:35:52,306] {spark_submit.py:514} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2021-12-28 13:35:52,313] {spark_submit.py:514} INFO - ... 1 more
[2021-12-28 13:36:08,941] {spark_submit.py:514} INFO - 21/12/28 13:36:08 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2021-12-28 13:36:11,012] {spark_submit.py:514} INFO - 21/12/28 13:36:10 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master spark:7077
[2021-12-28 13:36:11,019] {spark_submit.py:514} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2021-12-28 13:36:11,026] {spark_submit.py:514} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:301)
[2021-12-28 13:36:11,035] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2021-12-28 13:36:11,042] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:101)
[2021-12-28 13:36:11,045] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:109)
[2021-12-28 13:36:11,059] {spark_submit.py:514} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:107)
[2021-12-28 13:36:11,068] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2021-12-28 13:36:11,074] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2021-12-28 13:36:11,077] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2021-12-28 13:36:11,083] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2021-12-28 13:36:11,088] {spark_submit.py:514} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-28 13:36:11,091] {spark_submit.py:514} INFO - Caused by: java.io.IOException: Failed to connect to spark:7077
[2021-12-28 13:36:11,094] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:288)
[2021-12-28 13:36:11,100] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:218)
[2021-12-28 13:36:11,102] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:230)
[2021-12-28 13:36:11,104] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2021-12-28 13:36:11,106] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2021-12-28 13:36:11,116] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2021-12-28 13:36:11,118] {spark_submit.py:514} INFO - ... 4 more
[2021-12-28 13:36:11,123] {spark_submit.py:514} INFO - Caused by: java.net.UnknownHostException: spark
[2021-12-28 13:36:11,126] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
[2021-12-28 13:36:11,129] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509)
[2021-12-28 13:36:11,131] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1368)
[2021-12-28 13:36:11,138] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1302)
[2021-12-28 13:36:11,146] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getByName(InetAddress.java:1252)
[2021-12-28 13:36:11,149] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156)
[2021-12-28 13:36:11,156] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153)
[2021-12-28 13:36:11,159] {spark_submit.py:514} INFO - at java.base/java.security.AccessController.doPrivileged(Native Method)
[2021-12-28 13:36:11,161] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153)
[2021-12-28 13:36:11,165] {spark_submit.py:514} INFO - at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41)
[2021-12-28 13:36:11,173] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
[2021-12-28 13:36:11,185] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53)
[2021-12-28 13:36:11,190] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
[2021-12-28 13:36:11,203] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
[2021-12-28 13:36:11,206] {spark_submit.py:514} INFO - at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
[2021-12-28 13:36:11,209] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:206)
[2021-12-28 13:36:11,227] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46)
[2021-12-28 13:36:11,261] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:180)
[2021-12-28 13:36:11,269] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:166)
[2021-12-28 13:36:11,271] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
[2021-12-28 13:36:11,273] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
[2021-12-28 13:36:11,288] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
[2021-12-28 13:36:11,291] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
[2021-12-28 13:36:11,293] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
[2021-12-28 13:36:11,295] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
[2021-12-28 13:36:11,300] {spark_submit.py:514} INFO - at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
[2021-12-28 13:36:11,306] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:1008)
[2021-12-28 13:36:11,320] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:516)
[2021-12-28 13:36:11,327] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
[2021-12-28 13:36:11,332] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
[2021-12-28 13:36:11,337] {spark_submit.py:514} INFO - at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[2021-12-28 13:36:11,339] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
[2021-12-28 13:36:11,340] {spark_submit.py:514} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[2021-12-28 13:36:11,343] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[2021-12-28 13:36:11,345] {spark_submit.py:514} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2021-12-28 13:36:11,348] {spark_submit.py:514} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2021-12-28 13:36:11,349] {spark_submit.py:514} INFO - ... 1 more
[2021-12-28 13:36:28,907] {spark_submit.py:514} INFO - 21/12/28 13:36:28 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2021-12-28 13:36:29,051] {spark_submit.py:514} INFO - 21/12/28 13:36:29 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master spark:7077
[2021-12-28 13:36:29,052] {spark_submit.py:514} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2021-12-28 13:36:29,060] {spark_submit.py:514} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:301)
[2021-12-28 13:36:29,064] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2021-12-28 13:36:29,066] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:101)
[2021-12-28 13:36:29,068] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:109)
[2021-12-28 13:36:29,075] {spark_submit.py:514} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:107)
[2021-12-28 13:36:29,077] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2021-12-28 13:36:29,078] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2021-12-28 13:36:29,079] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2021-12-28 13:36:29,081] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2021-12-28 13:36:29,082] {spark_submit.py:514} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-28 13:36:29,084] {spark_submit.py:514} INFO - Caused by: java.io.IOException: Failed to connect to spark:7077
[2021-12-28 13:36:29,085] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:288)
[2021-12-28 13:36:29,086] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:218)
[2021-12-28 13:36:29,087] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:230)
[2021-12-28 13:36:29,088] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2021-12-28 13:36:29,090] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2021-12-28 13:36:29,091] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2021-12-28 13:36:29,092] {spark_submit.py:514} INFO - ... 4 more
[2021-12-28 13:36:29,094] {spark_submit.py:514} INFO - Caused by: java.net.UnknownHostException: spark
[2021-12-28 13:36:29,095] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
[2021-12-28 13:36:29,096] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509)
[2021-12-28 13:36:29,097] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1368)
[2021-12-28 13:36:29,099] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1302)
[2021-12-28 13:36:29,100] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getByName(InetAddress.java:1252)
[2021-12-28 13:36:29,101] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156)
[2021-12-28 13:36:29,102] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153)
[2021-12-28 13:36:29,103] {spark_submit.py:514} INFO - at java.base/java.security.AccessController.doPrivileged(Native Method)
[2021-12-28 13:36:29,105] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153)
[2021-12-28 13:36:29,106] {spark_submit.py:514} INFO - at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41)
[2021-12-28 13:36:29,107] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
[2021-12-28 13:36:29,108] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53)
[2021-12-28 13:36:29,109] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
[2021-12-28 13:36:29,111] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
[2021-12-28 13:36:29,112] {spark_submit.py:514} INFO - at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
[2021-12-28 13:36:29,114] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:206)
[2021-12-28 13:36:29,115] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46)
[2021-12-28 13:36:29,116] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:180)
[2021-12-28 13:36:29,118] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:166)
[2021-12-28 13:36:29,120] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
[2021-12-28 13:36:29,120] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
[2021-12-28 13:36:29,121] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
[2021-12-28 13:36:29,122] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
[2021-12-28 13:36:29,124] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
[2021-12-28 13:36:29,125] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
[2021-12-28 13:36:29,126] {spark_submit.py:514} INFO - at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
[2021-12-28 13:36:29,127] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:1008)
[2021-12-28 13:36:29,128] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:516)
[2021-12-28 13:36:29,129] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
[2021-12-28 13:36:29,130] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
[2021-12-28 13:36:29,133] {spark_submit.py:514} INFO - at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[2021-12-28 13:36:29,134] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
[2021-12-28 13:36:29,135] {spark_submit.py:514} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[2021-12-28 13:36:29,136] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[2021-12-28 13:36:29,137] {spark_submit.py:514} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2021-12-28 13:36:29,138] {spark_submit.py:514} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2021-12-28 13:36:29,139] {spark_submit.py:514} INFO - ... 1 more
[2021-12-28 13:36:48,402] {spark_submit.py:514} INFO - 21/12/28 13:36:48 WARN StandaloneSchedulerBackend: Application ID is not initialized yet.
[2021-12-28 13:36:48,415] {spark_submit.py:514} INFO - 21/12/28 13:36:48 ERROR StandaloneSchedulerBackend: Application has been killed. Reason: All masters are unresponsive! Giving up.
[2021-12-28 13:36:48,571] {spark_submit.py:514} INFO - 21/12/28 13:36:48 INFO SparkUI: Stopped Spark web UI at http://0c125a5bba95:4050
[2021-12-28 13:36:48,576] {spark_submit.py:514} INFO - 21/12/28 13:36:48 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 39957.
[2021-12-28 13:36:48,578] {spark_submit.py:514} INFO - 21/12/28 13:36:48 INFO NettyBlockTransferService: Server created on 0c125a5bba95:39957
[2021-12-28 13:36:48,636] {spark_submit.py:514} INFO - 21/12/28 13:36:48 INFO StandaloneSchedulerBackend: Shutting down all executors
[2021-12-28 13:36:48,657] {spark_submit.py:514} INFO - 21/12/28 13:36:48 INFO CoarseGrainedSchedulerBackend$DriverEndpoint: Asking each executor to shut down
[2021-12-28 13:36:48,663] {spark_submit.py:514} INFO - 21/12/28 13:36:48 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2021-12-28 13:36:48,673] {spark_submit.py:514} INFO - 21/12/28 13:36:48 WARN StandaloneAppClient$ClientEndpoint: Drop UnregisterApplication(null) because has not yet connected to master
[2021-12-28 13:36:48,734] {spark_submit.py:514} INFO - 21/12/28 13:36:48 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 0c125a5bba95, 39957, None)
[2021-12-28 13:36:48,798] {spark_submit.py:514} INFO - 21/12/28 13:36:48 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2021-12-28 13:36:48,935] {spark_submit.py:514} INFO - 21/12/28 13:36:48 INFO BlockManagerMasterEndpoint: Registering block manager 0c125a5bba95:39957 with 434.4 MiB RAM, BlockManagerId(driver, 0c125a5bba95, 39957, None)
[2021-12-28 13:36:48,952] {spark_submit.py:514} INFO - 21/12/28 13:36:48 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 0c125a5bba95, 39957, None)
[2021-12-28 13:36:49,024] {spark_submit.py:514} INFO - 21/12/28 13:36:49 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 0c125a5bba95, 39957, None)
[2021-12-28 13:36:49,124] {spark_submit.py:514} INFO - 21/12/28 13:36:49 INFO MemoryStore: MemoryStore cleared
[2021-12-28 13:36:49,128] {spark_submit.py:514} INFO - 21/12/28 13:36:49 INFO BlockManager: BlockManager stopped
[2021-12-28 13:36:49,178] {spark_submit.py:514} INFO - 21/12/28 13:36:49 INFO BlockManagerMaster: BlockManagerMaster stopped
[2021-12-28 13:36:49,252] {spark_submit.py:514} INFO - 21/12/28 13:36:49 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2021-12-28 13:36:49,886] {spark_submit.py:514} INFO - 21/12/28 13:36:49 INFO SparkContext: Successfully stopped SparkContext
[2021-12-28 13:36:51,285] {spark_submit.py:514} INFO - 21/12/28 13:36:51 ERROR SparkContext: Error initializing SparkContext.
[2021-12-28 13:36:51,287] {spark_submit.py:514} INFO - java.lang.IllegalArgumentException: requirement failed: Can only call getServletHandlers on a running MetricsSystem
[2021-12-28 13:36:51,288] {spark_submit.py:514} INFO - at scala.Predef$.require(Predef.scala:281)
[2021-12-28 13:36:51,289] {spark_submit.py:514} INFO - at org.apache.spark.metrics.MetricsSystem.getServletHandlers(MetricsSystem.scala:89)
[2021-12-28 13:36:51,290] {spark_submit.py:514} INFO - at org.apache.spark.SparkContext.<init>(SparkContext.scala:603)
[2021-12-28 13:36:51,291] {spark_submit.py:514} INFO - at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2021-12-28 13:36:51,292] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2021-12-28 13:36:51,293] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2021-12-28 13:36:51,294] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2021-12-28 13:36:51,295] {spark_submit.py:514} INFO - at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[2021-12-28 13:36:51,296] {spark_submit.py:514} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2021-12-28 13:36:51,297] {spark_submit.py:514} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2021-12-28 13:36:51,298] {spark_submit.py:514} INFO - at py4j.Gateway.invoke(Gateway.java:238)
[2021-12-28 13:36:51,299] {spark_submit.py:514} INFO - at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2021-12-28 13:36:51,300] {spark_submit.py:514} INFO - at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2021-12-28 13:36:51,302] {spark_submit.py:514} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2021-12-28 13:36:51,303] {spark_submit.py:514} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2021-12-28 13:36:51,308] {spark_submit.py:514} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-28 13:36:51,310] {spark_submit.py:514} INFO - 21/12/28 13:36:51 INFO SparkContext: SparkContext already stopped.
[2021-12-28 13:36:51,373] {spark_submit.py:514} INFO - Traceback (most recent call last):
[2021-12-28 13:36:51,374] {spark_submit.py:514} INFO - File "/opt/***/jobs/get_ads_per_county.py", line 13, in <module>
[2021-12-28 13:36:51,382] {spark_submit.py:514} INFO - .appName("Get Ads per county") \
[2021-12-28 13:36:51,383] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/session.py", line 228, in getOrCreate
[2021-12-28 13:36:51,384] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 392, in getOrCreate
[2021-12-28 13:36:51,391] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 147, in __init__
[2021-12-28 13:36:51,393] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 209, in _do_init
[2021-12-28 13:36:51,397] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 329, in _initialize_context
[2021-12-28 13:36:51,399] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/py4j-0.10.9.2-src.zip/py4j/java_gateway.py", line 1574, in __call__
[2021-12-28 13:36:51,400] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/py4j-0.10.9.2-src.zip/py4j/protocol.py", line 328, in get_return_value
[2021-12-28 13:36:51,429] {spark_submit.py:514} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling None.org.apache.spark.api.java.JavaSparkContext.
[2021-12-28 13:36:51,430] {spark_submit.py:514} INFO - : java.lang.IllegalArgumentException: requirement failed: Can only call getServletHandlers on a running MetricsSystem
[2021-12-28 13:36:51,432] {spark_submit.py:514} INFO - at scala.Predef$.require(Predef.scala:281)
[2021-12-28 13:36:51,434] {spark_submit.py:514} INFO - at org.apache.spark.metrics.MetricsSystem.getServletHandlers(MetricsSystem.scala:89)
[2021-12-28 13:36:51,435] {spark_submit.py:514} INFO - at org.apache.spark.SparkContext.<init>(SparkContext.scala:603)
[2021-12-28 13:36:51,436] {spark_submit.py:514} INFO - at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2021-12-28 13:36:51,437] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2021-12-28 13:36:51,438] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2021-12-28 13:36:51,440] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2021-12-28 13:36:51,442] {spark_submit.py:514} INFO - at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[2021-12-28 13:36:51,443] {spark_submit.py:514} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2021-12-28 13:36:51,444] {spark_submit.py:514} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2021-12-28 13:36:51,445] {spark_submit.py:514} INFO - at py4j.Gateway.invoke(Gateway.java:238)
[2021-12-28 13:36:51,450] {spark_submit.py:514} INFO - at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2021-12-28 13:36:51,456] {spark_submit.py:514} INFO - at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2021-12-28 13:36:51,457] {spark_submit.py:514} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2021-12-28 13:36:51,458] {spark_submit.py:514} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2021-12-28 13:36:51,459] {spark_submit.py:514} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-28 13:36:51,460] {spark_submit.py:514} INFO - 
[2021-12-28 13:36:53,336] {spark_submit.py:514} INFO - 21/12/28 13:36:53 INFO ShutdownHookManager: Shutdown hook called
[2021-12-28 13:36:53,343] {spark_submit.py:514} INFO - 21/12/28 13:36:53 INFO ShutdownHookManager: Deleting directory /tmp/spark-c9180e84-829a-46fa-97ee-0ebbd89497bc
[2021-12-28 13:36:53,359] {spark_submit.py:514} INFO - 21/12/28 13:36:53 INFO ShutdownHookManager: Deleting directory /tmp/spark-5a9b05f8-44d9-479d-9ffa-ec941af14469
[2021-12-28 13:36:55,360] {taskinstance.py:1703} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 179, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 446, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark:7077 --conf spark.master=spark://spark:7077 --name scrap data --verbose /opt/***/jobs/get_ads_per_county.py laois. Error code is: 1.
[2021-12-28 13:36:55,534] {taskinstance.py:1280} INFO - Marking task as UP_FOR_RETRY. dag_id=scraping_daft_laois, task_id=scrap_data, execution_date=20211227T095500, start_date=20211228T133326, end_date=20211228T133655
[2021-12-28 13:36:55,824] {standard_task_runner.py:91} ERROR - Failed to execute job 5077 for task scrap_data
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 179, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 446, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark:7077 --conf spark.master=spark://spark:7077 --name scrap data --verbose /opt/***/jobs/get_ads_per_county.py laois. Error code is: 1.
[2021-12-28 13:36:56,152] {local_task_job.py:154} INFO - Task exited with return code 1
[2021-12-28 13:36:56,853] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
