[2021-12-28 13:48:22,531] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: scraping_daft_laois.scrap_data scheduled__2021-12-27T09:55:00+00:00 [queued]>
[2021-12-28 13:48:22,618] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: scraping_daft_laois.scrap_data scheduled__2021-12-27T09:55:00+00:00 [queued]>
[2021-12-28 13:48:22,620] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-28 13:48:22,621] {taskinstance.py:1242} INFO - Starting attempt 4 of 4
[2021-12-28 13:48:22,622] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-28 13:48:22,653] {taskinstance.py:1262} INFO - Executing <Task(SparkSubmitOperator): scrap_data> on 2021-12-27 09:55:00+00:00
[2021-12-28 13:48:22,665] {standard_task_runner.py:52} INFO - Started process 56103 to run task
[2021-12-28 13:48:22,704] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'scraping_daft_laois', 'scrap_data', 'scheduled__2021-12-27T09:55:00+00:00', '--job-id', '5117', '--raw', '--subdir', 'DAGS_FOLDER/scraping_daft_laois.py', '--cfg-path', '/tmp/tmps3k3crcy', '--error-file', '/tmp/tmpceg67zq_']
[2021-12-28 13:48:22,709] {standard_task_runner.py:77} INFO - Job 5117: Subtask scrap_data
[2021-12-28 13:48:22,907] {logging_mixin.py:109} INFO - Running <TaskInstance: scraping_daft_laois.scrap_data scheduled__2021-12-27T09:55:00+00:00 [running]> on host 0c125a5bba95
[2021-12-28 13:48:23,185] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=clement.liscoet@gmail.com
AIRFLOW_CTX_DAG_OWNER=clemoni
AIRFLOW_CTX_DAG_ID=scraping_daft_laois
AIRFLOW_CTX_TASK_ID=scrap_data
AIRFLOW_CTX_EXECUTION_DATE=2021-12-27T09:55:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-27T09:55:00+00:00
[2021-12-28 13:48:23,238] {base.py:79} INFO - Using connection to: id: spark_default. Host: spark://spark:7077, Port: None, Schema: , Login: ***, Password: ***, extra: {}
[2021-12-28 13:48:23,247] {spark_submit.py:360} INFO - Spark-Submit cmd: spark-submit --master spark://spark:7077 --conf spark.master=spark://spark:7077 --name scrap data --verbose /opt/***/jobs/get_ads_per_county.py laois
[2021-12-28 13:48:28,406] {spark_submit.py:514} INFO - Using properties file: null
[2021-12-28 13:48:28,702] {spark_submit.py:514} INFO - WARNING: An illegal reflective access operation has occurred
[2021-12-28 13:48:28,705] {spark_submit.py:514} INFO - WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/home/***/.local/lib/python3.6/site-packages/pyspark/jars/spark-unsafe_2.12-3.2.0.jar) to constructor java.nio.DirectByteBuffer(long,int)
[2021-12-28 13:48:28,706] {spark_submit.py:514} INFO - WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
[2021-12-28 13:48:28,709] {spark_submit.py:514} INFO - WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[2021-12-28 13:48:28,714] {spark_submit.py:514} INFO - WARNING: All illegal access operations will be denied in a future release
[2021-12-28 13:48:28,827] {spark_submit.py:514} INFO - Parsed arguments:
[2021-12-28 13:48:28,829] {spark_submit.py:514} INFO - master                  spark://spark:7077
[2021-12-28 13:48:28,831] {spark_submit.py:514} INFO - deployMode              null
[2021-12-28 13:48:28,833] {spark_submit.py:514} INFO - executorMemory          null
[2021-12-28 13:48:28,834] {spark_submit.py:514} INFO - executorCores           null
[2021-12-28 13:48:28,835] {spark_submit.py:514} INFO - totalExecutorCores      null
[2021-12-28 13:48:28,837] {spark_submit.py:514} INFO - propertiesFile          null
[2021-12-28 13:48:28,838] {spark_submit.py:514} INFO - driverMemory            null
[2021-12-28 13:48:28,839] {spark_submit.py:514} INFO - driverCores             null
[2021-12-28 13:48:28,840] {spark_submit.py:514} INFO - driverExtraClassPath    null
[2021-12-28 13:48:28,841] {spark_submit.py:514} INFO - driverExtraLibraryPath  null
[2021-12-28 13:48:28,843] {spark_submit.py:514} INFO - driverExtraJavaOptions  null
[2021-12-28 13:48:28,844] {spark_submit.py:514} INFO - supervise               false
[2021-12-28 13:48:28,845] {spark_submit.py:514} INFO - queue                   null
[2021-12-28 13:48:28,846] {spark_submit.py:514} INFO - numExecutors            null
[2021-12-28 13:48:28,847] {spark_submit.py:514} INFO - files                   null
[2021-12-28 13:48:28,848] {spark_submit.py:514} INFO - pyFiles                 null
[2021-12-28 13:48:28,849] {spark_submit.py:514} INFO - archives                null
[2021-12-28 13:48:28,850] {spark_submit.py:514} INFO - mainClass               null
[2021-12-28 13:48:28,851] {spark_submit.py:514} INFO - primaryResource         file:/opt/***/jobs/get_ads_per_county.py
[2021-12-28 13:48:28,852] {spark_submit.py:514} INFO - name                    scrap data
[2021-12-28 13:48:28,856] {spark_submit.py:514} INFO - childArgs               [laois]
[2021-12-28 13:48:28,857] {spark_submit.py:514} INFO - jars                    null
[2021-12-28 13:48:28,859] {spark_submit.py:514} INFO - packages                null
[2021-12-28 13:48:28,861] {spark_submit.py:514} INFO - packagesExclusions      null
[2021-12-28 13:48:28,862] {spark_submit.py:514} INFO - repositories            null
[2021-12-28 13:48:28,863] {spark_submit.py:514} INFO - verbose                 true
[2021-12-28 13:48:28,864] {spark_submit.py:514} INFO - 
[2021-12-28 13:48:28,865] {spark_submit.py:514} INFO - Spark properties used, including those specified through
[2021-12-28 13:48:28,866] {spark_submit.py:514} INFO - --conf and those from the properties file null:
[2021-12-28 13:48:28,868] {spark_submit.py:514} INFO - (spark.master,spark://spark:7077)
[2021-12-28 13:48:28,870] {spark_submit.py:514} INFO - 
[2021-12-28 13:48:28,872] {spark_submit.py:514} INFO - 
[2021-12-28 13:48:29,487] {spark_submit.py:514} INFO - Main class:
[2021-12-28 13:48:29,488] {spark_submit.py:514} INFO - org.apache.spark.deploy.PythonRunner
[2021-12-28 13:48:29,489] {spark_submit.py:514} INFO - Arguments:
[2021-12-28 13:48:29,491] {spark_submit.py:514} INFO - file:/opt/***/jobs/get_ads_per_county.py
[2021-12-28 13:48:29,493] {spark_submit.py:514} INFO - null
[2021-12-28 13:48:29,494] {spark_submit.py:514} INFO - laois
[2021-12-28 13:48:29,498] {spark_submit.py:514} INFO - --verbose
[2021-12-28 13:48:29,503] {spark_submit.py:514} INFO - Spark config:
[2021-12-28 13:48:29,504] {spark_submit.py:514} INFO - (spark.app.name,scrap data)
[2021-12-28 13:48:29,505] {spark_submit.py:514} INFO - (spark.master,spark://spark:7077)
[2021-12-28 13:48:29,506] {spark_submit.py:514} INFO - (spark.submit.pyFiles,)
[2021-12-28 13:48:29,507] {spark_submit.py:514} INFO - (spark.submit.deployMode,client)
[2021-12-28 13:48:29,508] {spark_submit.py:514} INFO - Classpath elements:
[2021-12-28 13:48:29,510] {spark_submit.py:514} INFO - 
[2021-12-28 13:48:29,511] {spark_submit.py:514} INFO - 
[2021-12-28 13:48:29,513] {spark_submit.py:514} INFO - 
[2021-12-28 13:48:31,466] {spark_submit.py:514} INFO - Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
[2021-12-28 13:48:31,520] {spark_submit.py:514} INFO - 21/12/28 13:48:31 INFO SparkContext: Running Spark version 3.2.0
[2021-12-28 13:48:32,044] {spark_submit.py:514} INFO - 21/12/28 13:48:32 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2021-12-28 13:48:32,693] {spark_submit.py:514} INFO - 21/12/28 13:48:32 INFO ResourceUtils: ==============================================================
[2021-12-28 13:48:32,695] {spark_submit.py:514} INFO - 21/12/28 13:48:32 INFO ResourceUtils: No custom resources configured for spark.driver.
[2021-12-28 13:48:32,697] {spark_submit.py:514} INFO - 21/12/28 13:48:32 INFO ResourceUtils: ==============================================================
[2021-12-28 13:48:32,699] {spark_submit.py:514} INFO - 21/12/28 13:48:32 INFO SparkContext: Submitted application: Get Ads per county
[2021-12-28 13:48:32,793] {spark_submit.py:514} INFO - 21/12/28 13:48:32 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2021-12-28 13:48:32,853] {spark_submit.py:514} INFO - 21/12/28 13:48:32 INFO ResourceProfile: Limiting resource is cpu
[2021-12-28 13:48:32,859] {spark_submit.py:514} INFO - 21/12/28 13:48:32 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2021-12-28 13:48:33,023] {spark_submit.py:514} INFO - 21/12/28 13:48:33 INFO SecurityManager: Changing view acls to: ***
[2021-12-28 13:48:33,025] {spark_submit.py:514} INFO - 21/12/28 13:48:33 INFO SecurityManager: Changing modify acls to: ***
[2021-12-28 13:48:33,027] {spark_submit.py:514} INFO - 21/12/28 13:48:33 INFO SecurityManager: Changing view acls groups to:
[2021-12-28 13:48:33,029] {spark_submit.py:514} INFO - 21/12/28 13:48:33 INFO SecurityManager: Changing modify acls groups to:
[2021-12-28 13:48:33,030] {spark_submit.py:514} INFO - 21/12/28 13:48:33 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(***); groups with view permissions: Set(); users  with modify permissions: Set(***); groups with modify permissions: Set()
[2021-12-28 13:48:34,620] {spark_submit.py:514} INFO - 21/12/28 13:48:34 INFO Utils: Successfully started service 'sparkDriver' on port 36743.
[2021-12-28 13:48:34,745] {spark_submit.py:514} INFO - 21/12/28 13:48:34 INFO SparkEnv: Registering MapOutputTracker
[2021-12-28 13:48:34,933] {spark_submit.py:514} INFO - 21/12/28 13:48:34 INFO SparkEnv: Registering BlockManagerMaster
[2021-12-28 13:48:35,046] {spark_submit.py:514} INFO - 21/12/28 13:48:35 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2021-12-28 13:48:35,048] {spark_submit.py:514} INFO - 21/12/28 13:48:35 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2021-12-28 13:48:35,086] {spark_submit.py:514} INFO - 21/12/28 13:48:35 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2021-12-28 13:48:35,229] {spark_submit.py:514} INFO - 21/12/28 13:48:35 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-830430b4-c355-47bd-80d5-ea518385e654
[2021-12-28 13:48:35,393] {spark_submit.py:514} INFO - 21/12/28 13:48:35 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2021-12-28 13:48:35,478] {spark_submit.py:514} INFO - 21/12/28 13:48:35 INFO SparkEnv: Registering OutputCommitCoordinator
[2021-12-28 13:48:36,186] {spark_submit.py:514} INFO - 21/12/28 13:48:36 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2021-12-28 13:48:36,189] {spark_submit.py:514} INFO - 21/12/28 13:48:36 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.
[2021-12-28 13:48:36,191] {spark_submit.py:514} INFO - 21/12/28 13:48:36 WARN Utils: Service 'SparkUI' could not bind on port 4042. Attempting port 4043.
[2021-12-28 13:48:36,192] {spark_submit.py:514} INFO - 21/12/28 13:48:36 WARN Utils: Service 'SparkUI' could not bind on port 4043. Attempting port 4044.
[2021-12-28 13:48:36,193] {spark_submit.py:514} INFO - 21/12/28 13:48:36 WARN Utils: Service 'SparkUI' could not bind on port 4044. Attempting port 4045.
[2021-12-28 13:48:36,217] {spark_submit.py:514} INFO - 21/12/28 13:48:36 INFO Utils: Successfully started service 'SparkUI' on port 4045.
[2021-12-28 13:48:36,439] {spark_submit.py:514} INFO - 21/12/28 13:48:36 INFO SparkUI: Bound SparkUI to 0.0.0.0, and started at http://0c125a5bba95:4045
[2021-12-28 13:48:37,249] {spark_submit.py:514} INFO - 21/12/28 13:48:37 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2021-12-28 13:48:37,700] {spark_submit.py:514} INFO - 21/12/28 13:48:37 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master spark:7077
[2021-12-28 13:48:37,701] {spark_submit.py:514} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2021-12-28 13:48:37,704] {spark_submit.py:514} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:301)
[2021-12-28 13:48:37,708] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2021-12-28 13:48:37,711] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:101)
[2021-12-28 13:48:37,712] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:109)
[2021-12-28 13:48:37,713] {spark_submit.py:514} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:107)
[2021-12-28 13:48:37,714] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2021-12-28 13:48:37,715] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2021-12-28 13:48:37,716] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2021-12-28 13:48:37,716] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2021-12-28 13:48:37,718] {spark_submit.py:514} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-28 13:48:37,719] {spark_submit.py:514} INFO - Caused by: java.io.IOException: Failed to connect to spark:7077
[2021-12-28 13:48:37,720] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:288)
[2021-12-28 13:48:37,721] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:218)
[2021-12-28 13:48:37,722] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:230)
[2021-12-28 13:48:37,722] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2021-12-28 13:48:37,723] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2021-12-28 13:48:37,724] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2021-12-28 13:48:37,725] {spark_submit.py:514} INFO - ... 4 more
[2021-12-28 13:48:37,726] {spark_submit.py:514} INFO - Caused by: java.net.UnknownHostException: spark
[2021-12-28 13:48:37,726] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
[2021-12-28 13:48:37,727] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509)
[2021-12-28 13:48:37,728] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1368)
[2021-12-28 13:48:37,729] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1302)
[2021-12-28 13:48:37,730] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getByName(InetAddress.java:1252)
[2021-12-28 13:48:37,731] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156)
[2021-12-28 13:48:37,731] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153)
[2021-12-28 13:48:37,732] {spark_submit.py:514} INFO - at java.base/java.security.AccessController.doPrivileged(Native Method)
[2021-12-28 13:48:37,733] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153)
[2021-12-28 13:48:37,734] {spark_submit.py:514} INFO - at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41)
[2021-12-28 13:48:37,735] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
[2021-12-28 13:48:37,735] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53)
[2021-12-28 13:48:37,737] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
[2021-12-28 13:48:37,738] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
[2021-12-28 13:48:37,739] {spark_submit.py:514} INFO - at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
[2021-12-28 13:48:37,741] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:206)
[2021-12-28 13:48:37,741] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46)
[2021-12-28 13:48:37,742] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:180)
[2021-12-28 13:48:37,743] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:166)
[2021-12-28 13:48:37,745] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
[2021-12-28 13:48:37,746] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
[2021-12-28 13:48:37,747] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
[2021-12-28 13:48:37,748] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
[2021-12-28 13:48:37,749] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
[2021-12-28 13:48:37,750] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
[2021-12-28 13:48:37,752] {spark_submit.py:514} INFO - at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
[2021-12-28 13:48:37,753] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:1008)
[2021-12-28 13:48:37,755] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:516)
[2021-12-28 13:48:37,756] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
[2021-12-28 13:48:37,757] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
[2021-12-28 13:48:37,759] {spark_submit.py:514} INFO - at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[2021-12-28 13:48:37,760] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
[2021-12-28 13:48:37,761] {spark_submit.py:514} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[2021-12-28 13:48:37,765] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[2021-12-28 13:48:37,767] {spark_submit.py:514} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2021-12-28 13:48:37,770] {spark_submit.py:514} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2021-12-28 13:48:37,771] {spark_submit.py:514} INFO - ... 1 more
[2021-12-28 13:48:57,195] {spark_submit.py:514} INFO - 21/12/28 13:48:57 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2021-12-28 13:48:57,212] {spark_submit.py:514} INFO - 21/12/28 13:48:57 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master spark:7077
[2021-12-28 13:48:57,213] {spark_submit.py:514} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2021-12-28 13:48:57,214] {spark_submit.py:514} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:301)
[2021-12-28 13:48:57,214] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2021-12-28 13:48:57,215] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:101)
[2021-12-28 13:48:57,217] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:109)
[2021-12-28 13:48:57,218] {spark_submit.py:514} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:107)
[2021-12-28 13:48:57,219] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2021-12-28 13:48:57,219] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2021-12-28 13:48:57,221] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2021-12-28 13:48:57,222] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2021-12-28 13:48:57,223] {spark_submit.py:514} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-28 13:48:57,223] {spark_submit.py:514} INFO - Caused by: java.io.IOException: Failed to connect to spark:7077
[2021-12-28 13:48:57,224] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:288)
[2021-12-28 13:48:57,225] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:218)
[2021-12-28 13:48:57,226] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:230)
[2021-12-28 13:48:57,226] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2021-12-28 13:48:57,227] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2021-12-28 13:48:57,228] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2021-12-28 13:48:57,229] {spark_submit.py:514} INFO - ... 4 more
[2021-12-28 13:48:57,229] {spark_submit.py:514} INFO - Caused by: java.net.UnknownHostException: spark
[2021-12-28 13:48:57,230] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
[2021-12-28 13:48:57,231] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509)
[2021-12-28 13:48:57,232] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1368)
[2021-12-28 13:48:57,233] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1302)
[2021-12-28 13:48:57,233] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getByName(InetAddress.java:1252)
[2021-12-28 13:48:57,234] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156)
[2021-12-28 13:48:57,235] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153)
[2021-12-28 13:48:57,236] {spark_submit.py:514} INFO - at java.base/java.security.AccessController.doPrivileged(Native Method)
[2021-12-28 13:48:57,236] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153)
[2021-12-28 13:48:57,237] {spark_submit.py:514} INFO - at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41)
[2021-12-28 13:48:57,238] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
[2021-12-28 13:48:57,239] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53)
[2021-12-28 13:48:57,241] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
[2021-12-28 13:48:57,241] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
[2021-12-28 13:48:57,242] {spark_submit.py:514} INFO - at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
[2021-12-28 13:48:57,243] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:206)
[2021-12-28 13:48:57,244] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46)
[2021-12-28 13:48:57,245] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:180)
[2021-12-28 13:48:57,245] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:166)
[2021-12-28 13:48:57,246] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
[2021-12-28 13:48:57,247] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
[2021-12-28 13:48:57,247] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
[2021-12-28 13:48:57,248] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
[2021-12-28 13:48:57,249] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
[2021-12-28 13:48:57,250] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
[2021-12-28 13:48:57,251] {spark_submit.py:514} INFO - at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
[2021-12-28 13:48:57,252] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:1008)
[2021-12-28 13:48:57,253] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:516)
[2021-12-28 13:48:57,253] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
[2021-12-28 13:48:57,254] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
[2021-12-28 13:48:57,255] {spark_submit.py:514} INFO - at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[2021-12-28 13:48:57,256] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
[2021-12-28 13:48:57,256] {spark_submit.py:514} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[2021-12-28 13:48:57,257] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[2021-12-28 13:48:57,258] {spark_submit.py:514} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2021-12-28 13:48:57,259] {spark_submit.py:514} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2021-12-28 13:48:57,260] {spark_submit.py:514} INFO - ... 1 more
[2021-12-28 13:49:17,160] {spark_submit.py:514} INFO - 21/12/28 13:49:17 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2021-12-28 13:49:17,178] {spark_submit.py:514} INFO - 21/12/28 13:49:17 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master spark:7077
[2021-12-28 13:49:17,179] {spark_submit.py:514} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2021-12-28 13:49:17,180] {spark_submit.py:514} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:301)
[2021-12-28 13:49:17,181] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2021-12-28 13:49:17,182] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:101)
[2021-12-28 13:49:17,183] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:109)
[2021-12-28 13:49:17,184] {spark_submit.py:514} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:107)
[2021-12-28 13:49:17,185] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2021-12-28 13:49:17,187] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2021-12-28 13:49:17,188] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2021-12-28 13:49:17,189] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2021-12-28 13:49:17,189] {spark_submit.py:514} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-28 13:49:17,190] {spark_submit.py:514} INFO - Caused by: java.io.IOException: Failed to connect to spark:7077
[2021-12-28 13:49:17,191] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:288)
[2021-12-28 13:49:17,192] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:218)
[2021-12-28 13:49:17,193] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:230)
[2021-12-28 13:49:17,194] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2021-12-28 13:49:17,195] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2021-12-28 13:49:17,195] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2021-12-28 13:49:17,196] {spark_submit.py:514} INFO - ... 4 more
[2021-12-28 13:49:17,197] {spark_submit.py:514} INFO - Caused by: java.net.UnknownHostException: spark
[2021-12-28 13:49:17,198] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
[2021-12-28 13:49:17,198] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509)
[2021-12-28 13:49:17,199] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1368)
[2021-12-28 13:49:17,200] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1302)
[2021-12-28 13:49:17,201] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getByName(InetAddress.java:1252)
[2021-12-28 13:49:17,202] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156)
[2021-12-28 13:49:17,202] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153)
[2021-12-28 13:49:17,203] {spark_submit.py:514} INFO - at java.base/java.security.AccessController.doPrivileged(Native Method)
[2021-12-28 13:49:17,204] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153)
[2021-12-28 13:49:17,205] {spark_submit.py:514} INFO - at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41)
[2021-12-28 13:49:17,205] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
[2021-12-28 13:49:17,206] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53)
[2021-12-28 13:49:17,207] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
[2021-12-28 13:49:17,208] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
[2021-12-28 13:49:17,209] {spark_submit.py:514} INFO - at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
[2021-12-28 13:49:17,209] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:206)
[2021-12-28 13:49:17,210] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46)
[2021-12-28 13:49:17,211] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:180)
[2021-12-28 13:49:17,213] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:166)
[2021-12-28 13:49:17,213] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
[2021-12-28 13:49:17,214] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
[2021-12-28 13:49:17,215] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
[2021-12-28 13:49:17,215] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
[2021-12-28 13:49:17,216] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
[2021-12-28 13:49:17,217] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
[2021-12-28 13:49:17,218] {spark_submit.py:514} INFO - at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
[2021-12-28 13:49:17,218] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:1008)
[2021-12-28 13:49:17,219] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:516)
[2021-12-28 13:49:17,220] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
[2021-12-28 13:49:17,220] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
[2021-12-28 13:49:17,221] {spark_submit.py:514} INFO - at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[2021-12-28 13:49:17,222] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
[2021-12-28 13:49:17,223] {spark_submit.py:514} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[2021-12-28 13:49:17,223] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[2021-12-28 13:49:17,224] {spark_submit.py:514} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2021-12-28 13:49:17,225] {spark_submit.py:514} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2021-12-28 13:49:17,226] {spark_submit.py:514} INFO - ... 1 more
[2021-12-28 13:49:37,163] {spark_submit.py:514} INFO - 21/12/28 13:49:37 ERROR StandaloneSchedulerBackend: Application has been killed. Reason: All masters are unresponsive! Giving up.
[2021-12-28 13:49:37,175] {spark_submit.py:514} INFO - 21/12/28 13:49:37 WARN StandaloneSchedulerBackend: Application ID is not initialized yet.
[2021-12-28 13:49:37,197] {spark_submit.py:514} INFO - 21/12/28 13:49:37 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 37213.
[2021-12-28 13:49:37,198] {spark_submit.py:514} INFO - 21/12/28 13:49:37 INFO NettyBlockTransferService: Server created on 0c125a5bba95:37213
[2021-12-28 13:49:37,200] {spark_submit.py:514} INFO - 21/12/28 13:49:37 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2021-12-28 13:49:37,217] {spark_submit.py:514} INFO - 21/12/28 13:49:37 INFO SparkUI: Stopped Spark web UI at http://0c125a5bba95:4045
[2021-12-28 13:49:37,225] {spark_submit.py:514} INFO - 21/12/28 13:49:37 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 0c125a5bba95, 37213, None)
[2021-12-28 13:49:37,229] {spark_submit.py:514} INFO - 21/12/28 13:49:37 INFO StandaloneSchedulerBackend: Shutting down all executors
[2021-12-28 13:49:37,237] {spark_submit.py:514} INFO - 21/12/28 13:49:37 INFO BlockManagerMasterEndpoint: Registering block manager 0c125a5bba95:37213 with 434.4 MiB RAM, BlockManagerId(driver, 0c125a5bba95, 37213, None)
[2021-12-28 13:49:37,239] {spark_submit.py:514} INFO - 21/12/28 13:49:37 INFO CoarseGrainedSchedulerBackend$DriverEndpoint: Asking each executor to shut down
[2021-12-28 13:49:37,244] {spark_submit.py:514} INFO - 21/12/28 13:49:37 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 0c125a5bba95, 37213, None)
[2021-12-28 13:49:37,245] {spark_submit.py:514} INFO - 21/12/28 13:49:37 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 0c125a5bba95, 37213, None)
[2021-12-28 13:49:37,249] {spark_submit.py:514} INFO - 21/12/28 13:49:37 WARN StandaloneAppClient$ClientEndpoint: Drop UnregisterApplication(null) because has not yet connected to master
[2021-12-28 13:49:37,286] {spark_submit.py:514} INFO - 21/12/28 13:49:37 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2021-12-28 13:49:37,323] {spark_submit.py:514} INFO - 21/12/28 13:49:37 INFO MemoryStore: MemoryStore cleared
[2021-12-28 13:49:37,324] {spark_submit.py:514} INFO - 21/12/28 13:49:37 INFO BlockManager: BlockManager stopped
[2021-12-28 13:49:37,341] {spark_submit.py:514} INFO - 21/12/28 13:49:37 INFO BlockManagerMaster: BlockManagerMaster stopped
[2021-12-28 13:49:37,347] {spark_submit.py:514} INFO - 21/12/28 13:49:37 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2021-12-28 13:49:37,372] {spark_submit.py:514} INFO - 21/12/28 13:49:37 INFO SparkContext: Successfully stopped SparkContext
[2021-12-28 13:49:37,519] {spark_submit.py:514} INFO - 21/12/28 13:49:37 ERROR SparkContext: Error initializing SparkContext.
[2021-12-28 13:49:37,520] {spark_submit.py:514} INFO - java.lang.IllegalArgumentException: requirement failed: Can only call getServletHandlers on a running MetricsSystem
[2021-12-28 13:49:37,522] {spark_submit.py:514} INFO - at scala.Predef$.require(Predef.scala:281)
[2021-12-28 13:49:37,523] {spark_submit.py:514} INFO - at org.apache.spark.metrics.MetricsSystem.getServletHandlers(MetricsSystem.scala:89)
[2021-12-28 13:49:37,524] {spark_submit.py:514} INFO - at org.apache.spark.SparkContext.<init>(SparkContext.scala:603)
[2021-12-28 13:49:37,529] {spark_submit.py:514} INFO - at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2021-12-28 13:49:37,530] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2021-12-28 13:49:37,532] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2021-12-28 13:49:37,533] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2021-12-28 13:49:37,534] {spark_submit.py:514} INFO - at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[2021-12-28 13:49:37,535] {spark_submit.py:514} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2021-12-28 13:49:37,536] {spark_submit.py:514} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2021-12-28 13:49:37,537] {spark_submit.py:514} INFO - at py4j.Gateway.invoke(Gateway.java:238)
[2021-12-28 13:49:37,538] {spark_submit.py:514} INFO - at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2021-12-28 13:49:37,539] {spark_submit.py:514} INFO - at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2021-12-28 13:49:37,540] {spark_submit.py:514} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2021-12-28 13:49:37,541] {spark_submit.py:514} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2021-12-28 13:49:37,543] {spark_submit.py:514} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-28 13:49:37,544] {spark_submit.py:514} INFO - 21/12/28 13:49:37 INFO SparkContext: SparkContext already stopped.
[2021-12-28 13:49:37,545] {spark_submit.py:514} INFO - Traceback (most recent call last):
[2021-12-28 13:49:37,546] {spark_submit.py:514} INFO - File "/opt/***/jobs/get_ads_per_county.py", line 13, in <module>
[2021-12-28 13:49:37,548] {spark_submit.py:514} INFO - .appName("Get Ads per county") \
[2021-12-28 13:49:37,549] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/session.py", line 228, in getOrCreate
[2021-12-28 13:49:37,550] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 392, in getOrCreate
[2021-12-28 13:49:37,551] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 147, in __init__
[2021-12-28 13:49:37,552] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 209, in _do_init
[2021-12-28 13:49:37,553] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 329, in _initialize_context
[2021-12-28 13:49:37,553] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/py4j-0.10.9.2-src.zip/py4j/java_gateway.py", line 1574, in __call__
[2021-12-28 13:49:37,555] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/py4j-0.10.9.2-src.zip/py4j/protocol.py", line 328, in get_return_value
[2021-12-28 13:49:37,555] {spark_submit.py:514} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling None.org.apache.spark.api.java.JavaSparkContext.
[2021-12-28 13:49:37,556] {spark_submit.py:514} INFO - : java.lang.IllegalArgumentException: requirement failed: Can only call getServletHandlers on a running MetricsSystem
[2021-12-28 13:49:37,557] {spark_submit.py:514} INFO - at scala.Predef$.require(Predef.scala:281)
[2021-12-28 13:49:37,558] {spark_submit.py:514} INFO - at org.apache.spark.metrics.MetricsSystem.getServletHandlers(MetricsSystem.scala:89)
[2021-12-28 13:49:37,559] {spark_submit.py:514} INFO - at org.apache.spark.SparkContext.<init>(SparkContext.scala:603)
[2021-12-28 13:49:37,560] {spark_submit.py:514} INFO - at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2021-12-28 13:49:37,561] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2021-12-28 13:49:37,564] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2021-12-28 13:49:37,565] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2021-12-28 13:49:37,565] {spark_submit.py:514} INFO - at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[2021-12-28 13:49:37,566] {spark_submit.py:514} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2021-12-28 13:49:37,567] {spark_submit.py:514} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2021-12-28 13:49:37,568] {spark_submit.py:514} INFO - at py4j.Gateway.invoke(Gateway.java:238)
[2021-12-28 13:49:37,569] {spark_submit.py:514} INFO - at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2021-12-28 13:49:37,570] {spark_submit.py:514} INFO - at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2021-12-28 13:49:37,571] {spark_submit.py:514} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2021-12-28 13:49:37,572] {spark_submit.py:514} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2021-12-28 13:49:37,573] {spark_submit.py:514} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-28 13:49:37,574] {spark_submit.py:514} INFO - 
[2021-12-28 13:49:37,685] {spark_submit.py:514} INFO - 21/12/28 13:49:37 INFO ShutdownHookManager: Shutdown hook called
[2021-12-28 13:49:37,687] {spark_submit.py:514} INFO - 21/12/28 13:49:37 INFO ShutdownHookManager: Deleting directory /tmp/spark-a060c656-64c3-4168-ad09-1f35e399f6ad
[2021-12-28 13:49:37,693] {spark_submit.py:514} INFO - 21/12/28 13:49:37 INFO ShutdownHookManager: Deleting directory /tmp/spark-00da7d07-d6d7-4030-a4db-f7d2227cf095
[2021-12-28 13:49:38,106] {taskinstance.py:1703} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 179, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 446, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark:7077 --conf spark.master=spark://spark:7077 --name scrap data --verbose /opt/***/jobs/get_ads_per_county.py laois. Error code is: 1.
[2021-12-28 13:49:38,116] {taskinstance.py:1280} INFO - Marking task as FAILED. dag_id=scraping_daft_laois, task_id=scrap_data, execution_date=20211227T095500, start_date=20211228T134822, end_date=20211228T134938
[2021-12-28 13:49:38,181] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/email.py:102: PendingDeprecationWarning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=smtp_mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2021-12-28 13:49:38,186] {email.py:208} INFO - Email alerting: attempt 1
[2021-12-28 13:49:38,693] {email.py:220} INFO - Sent an alert email to ['clement.liscoet@gmail.com']
[2021-12-28 13:49:39,971] {standard_task_runner.py:91} ERROR - Failed to execute job 5117 for task scrap_data
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 179, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 446, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark:7077 --conf spark.master=spark://spark:7077 --name scrap data --verbose /opt/***/jobs/get_ads_per_county.py laois. Error code is: 1.
[2021-12-28 13:49:40,013] {local_task_job.py:154} INFO - Task exited with return code 1
[2021-12-28 13:49:40,468] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
