[2021-12-29 12:10:01,017] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: scraping_daft_donegal.scrap_data scheduled__2021-12-28T09:25:00+00:00 [queued]>
[2021-12-29 12:10:01,038] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: scraping_daft_donegal.scrap_data scheduled__2021-12-28T09:25:00+00:00 [queued]>
[2021-12-29 12:10:01,041] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-29 12:10:01,043] {taskinstance.py:1242} INFO - Starting attempt 3 of 4
[2021-12-29 12:10:01,044] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-29 12:10:01,065] {taskinstance.py:1262} INFO - Executing <Task(SparkSubmitOperator): scrap_data> on 2021-12-28 09:25:00+00:00
[2021-12-29 12:10:01,075] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'scraping_daft_donegal', 'scrap_data', 'scheduled__2021-12-28T09:25:00+00:00', '--job-id', '5372', '--raw', '--subdir', 'DAGS_FOLDER/scraping_daft_donegal.py', '--cfg-path', '/tmp/tmprwhb_0cg', '--error-file', '/tmp/tmp0zvfoycx']
[2021-12-29 12:10:01,077] {standard_task_runner.py:77} INFO - Job 5372: Subtask scrap_data
[2021-12-29 12:10:01,070] {standard_task_runner.py:52} INFO - Started process 31516 to run task
[2021-12-29 12:10:01,210] {logging_mixin.py:109} INFO - Running <TaskInstance: scraping_daft_donegal.scrap_data scheduled__2021-12-28T09:25:00+00:00 [running]> on host 6bdda4c19a85
[2021-12-29 12:10:01,411] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=clement.liscoet@gmail.com
AIRFLOW_CTX_DAG_OWNER=clemoni
AIRFLOW_CTX_DAG_ID=scraping_daft_donegal
AIRFLOW_CTX_TASK_ID=scrap_data
AIRFLOW_CTX_EXECUTION_DATE=2021-12-28T09:25:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-28T09:25:00+00:00
[2021-12-29 12:10:01,440] {base.py:79} INFO - Using connection to: id: spark_default. Host: spark://spark:7077, Port: None, Schema: , Login: ***, Password: ***, extra: {}
[2021-12-29 12:10:01,444] {spark_submit.py:360} INFO - Spark-Submit cmd: spark-submit --master spark://spark:7077 --conf spark.master=spark://spark:7077 --name scrap data --verbose /opt/***/jobs/get_ads_per_county.py donegal
[2021-12-29 12:10:04,696] {spark_submit.py:514} INFO - Using properties file: null
[2021-12-29 12:10:05,130] {spark_submit.py:514} INFO - WARNING: An illegal reflective access operation has occurred
[2021-12-29 12:10:05,133] {spark_submit.py:514} INFO - WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/home/***/.local/lib/python3.6/site-packages/pyspark/jars/spark-unsafe_2.12-3.2.0.jar) to constructor java.nio.DirectByteBuffer(long,int)
[2021-12-29 12:10:05,139] {spark_submit.py:514} INFO - WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
[2021-12-29 12:10:05,143] {spark_submit.py:514} INFO - WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[2021-12-29 12:10:05,152] {spark_submit.py:514} INFO - WARNING: All illegal access operations will be denied in a future release
[2021-12-29 12:10:05,347] {spark_submit.py:514} INFO - Parsed arguments:
[2021-12-29 12:10:05,349] {spark_submit.py:514} INFO - master                  spark://spark:7077
[2021-12-29 12:10:05,350] {spark_submit.py:514} INFO - deployMode              null
[2021-12-29 12:10:05,353] {spark_submit.py:514} INFO - executorMemory          null
[2021-12-29 12:10:05,355] {spark_submit.py:514} INFO - executorCores           null
[2021-12-29 12:10:05,357] {spark_submit.py:514} INFO - totalExecutorCores      null
[2021-12-29 12:10:05,359] {spark_submit.py:514} INFO - propertiesFile          null
[2021-12-29 12:10:05,362] {spark_submit.py:514} INFO - driverMemory            null
[2021-12-29 12:10:05,365] {spark_submit.py:514} INFO - driverCores             null
[2021-12-29 12:10:05,367] {spark_submit.py:514} INFO - driverExtraClassPath    null
[2021-12-29 12:10:05,373] {spark_submit.py:514} INFO - driverExtraLibraryPath  null
[2021-12-29 12:10:05,376] {spark_submit.py:514} INFO - driverExtraJavaOptions  null
[2021-12-29 12:10:05,379] {spark_submit.py:514} INFO - supervise               false
[2021-12-29 12:10:05,386] {spark_submit.py:514} INFO - queue                   null
[2021-12-29 12:10:05,391] {spark_submit.py:514} INFO - numExecutors            null
[2021-12-29 12:10:05,393] {spark_submit.py:514} INFO - files                   null
[2021-12-29 12:10:05,396] {spark_submit.py:514} INFO - pyFiles                 null
[2021-12-29 12:10:05,398] {spark_submit.py:514} INFO - archives                null
[2021-12-29 12:10:05,399] {spark_submit.py:514} INFO - mainClass               null
[2021-12-29 12:10:05,407] {spark_submit.py:514} INFO - primaryResource         file:/opt/***/jobs/get_ads_per_county.py
[2021-12-29 12:10:05,409] {spark_submit.py:514} INFO - name                    scrap data
[2021-12-29 12:10:05,411] {spark_submit.py:514} INFO - childArgs               [donegal]
[2021-12-29 12:10:05,415] {spark_submit.py:514} INFO - jars                    null
[2021-12-29 12:10:05,418] {spark_submit.py:514} INFO - packages                null
[2021-12-29 12:10:05,441] {spark_submit.py:514} INFO - packagesExclusions      null
[2021-12-29 12:10:05,446] {spark_submit.py:514} INFO - repositories            null
[2021-12-29 12:10:05,449] {spark_submit.py:514} INFO - verbose                 true
[2021-12-29 12:10:05,450] {spark_submit.py:514} INFO - 
[2021-12-29 12:10:05,451] {spark_submit.py:514} INFO - Spark properties used, including those specified through
[2021-12-29 12:10:05,453] {spark_submit.py:514} INFO - --conf and those from the properties file null:
[2021-12-29 12:10:05,455] {spark_submit.py:514} INFO - (spark.master,spark://spark:7077)
[2021-12-29 12:10:05,458] {spark_submit.py:514} INFO - 
[2021-12-29 12:10:05,461] {spark_submit.py:514} INFO - 
[2021-12-29 12:10:06,725] {spark_submit.py:514} INFO - Main class:
[2021-12-29 12:10:06,729] {spark_submit.py:514} INFO - org.apache.spark.deploy.PythonRunner
[2021-12-29 12:10:06,732] {spark_submit.py:514} INFO - Arguments:
[2021-12-29 12:10:06,738] {spark_submit.py:514} INFO - file:/opt/***/jobs/get_ads_per_county.py
[2021-12-29 12:10:06,741] {spark_submit.py:514} INFO - null
[2021-12-29 12:10:06,746] {spark_submit.py:514} INFO - donegal
[2021-12-29 12:10:06,753] {spark_submit.py:514} INFO - --verbose
[2021-12-29 12:10:06,755] {spark_submit.py:514} INFO - Spark config:
[2021-12-29 12:10:06,757] {spark_submit.py:514} INFO - (spark.app.name,scrap data)
[2021-12-29 12:10:06,758] {spark_submit.py:514} INFO - (spark.master,spark://spark:7077)
[2021-12-29 12:10:06,760] {spark_submit.py:514} INFO - (spark.submit.pyFiles,)
[2021-12-29 12:10:06,763] {spark_submit.py:514} INFO - (spark.submit.deployMode,client)
[2021-12-29 12:10:06,765] {spark_submit.py:514} INFO - Classpath elements:
[2021-12-29 12:10:06,766] {spark_submit.py:514} INFO - 
[2021-12-29 12:10:06,767] {spark_submit.py:514} INFO - 
[2021-12-29 12:10:06,769] {spark_submit.py:514} INFO - 
[2021-12-29 12:10:10,881] {spark_submit.py:514} INFO - Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
[2021-12-29 12:10:11,003] {spark_submit.py:514} INFO - 21/12/29 12:10:11 INFO SparkContext: Running Spark version 3.2.0
[2021-12-29 12:10:12,311] {spark_submit.py:514} INFO - 21/12/29 12:10:12 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2021-12-29 12:10:13,670] {spark_submit.py:514} INFO - 21/12/29 12:10:13 INFO ResourceUtils: ==============================================================
[2021-12-29 12:10:13,672] {spark_submit.py:514} INFO - 21/12/29 12:10:13 INFO ResourceUtils: No custom resources configured for spark.driver.
[2021-12-29 12:10:13,709] {spark_submit.py:514} INFO - 21/12/29 12:10:13 INFO ResourceUtils: ==============================================================
[2021-12-29 12:10:13,717] {spark_submit.py:514} INFO - 21/12/29 12:10:13 INFO SparkContext: Submitted application: Get Ads per county
[2021-12-29 12:10:14,123] {spark_submit.py:514} INFO - 21/12/29 12:10:14 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2021-12-29 12:10:14,280] {spark_submit.py:514} INFO - 21/12/29 12:10:14 INFO ResourceProfile: Limiting resource is cpu
[2021-12-29 12:10:14,294] {spark_submit.py:514} INFO - 21/12/29 12:10:14 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2021-12-29 12:10:14,955] {spark_submit.py:514} INFO - 21/12/29 12:10:14 INFO SecurityManager: Changing view acls to: ***
[2021-12-29 12:10:14,987] {spark_submit.py:514} INFO - 21/12/29 12:10:14 INFO SecurityManager: Changing modify acls to: ***
[2021-12-29 12:10:15,011] {spark_submit.py:514} INFO - 21/12/29 12:10:14 INFO SecurityManager: Changing view acls groups to:
[2021-12-29 12:10:15,043] {spark_submit.py:514} INFO - 21/12/29 12:10:15 INFO SecurityManager: Changing modify acls groups to:
[2021-12-29 12:10:15,093] {spark_submit.py:514} INFO - 21/12/29 12:10:15 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(***); groups with view permissions: Set(); users  with modify permissions: Set(***); groups with modify permissions: Set()
[2021-12-29 12:10:18,101] {spark_submit.py:514} INFO - 21/12/29 12:10:18 INFO Utils: Successfully started service 'sparkDriver' on port 42989.
[2021-12-29 12:10:18,505] {spark_submit.py:514} INFO - 21/12/29 12:10:18 INFO SparkEnv: Registering MapOutputTracker
[2021-12-29 12:10:19,290] {spark_submit.py:514} INFO - 21/12/29 12:10:19 INFO SparkEnv: Registering BlockManagerMaster
[2021-12-29 12:10:19,535] {spark_submit.py:514} INFO - 21/12/29 12:10:19 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2021-12-29 12:10:19,539] {spark_submit.py:514} INFO - 21/12/29 12:10:19 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2021-12-29 12:10:19,584] {spark_submit.py:514} INFO - 21/12/29 12:10:19 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2021-12-29 12:10:19,873] {spark_submit.py:514} INFO - 21/12/29 12:10:19 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-c64fff82-2ac0-4495-abf8-ae0091fd3a97
[2021-12-29 12:10:19,951] {spark_submit.py:514} INFO - 21/12/29 12:10:19 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2021-12-29 12:10:20,085] {spark_submit.py:514} INFO - 21/12/29 12:10:20 INFO SparkEnv: Registering OutputCommitCoordinator
[2021-12-29 12:10:21,932] {spark_submit.py:514} INFO - 21/12/29 12:10:21 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2021-12-29 12:10:21,934] {spark_submit.py:514} INFO - 21/12/29 12:10:21 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.
[2021-12-29 12:10:22,032] {spark_submit.py:514} INFO - 21/12/29 12:10:22 INFO Utils: Successfully started service 'SparkUI' on port 4042.
[2021-12-29 12:10:22,683] {spark_submit.py:514} INFO - 21/12/29 12:10:22 INFO SparkUI: Bound SparkUI to 0.0.0.0, and started at http://6bdda4c19a85:4042
[2021-12-29 12:10:24,928] {spark_submit.py:514} INFO - 21/12/29 12:10:24 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2021-12-29 12:10:25,277] {spark_submit.py:514} INFO - 21/12/29 12:10:25 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master spark:7077
[2021-12-29 12:10:25,278] {spark_submit.py:514} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2021-12-29 12:10:25,279] {spark_submit.py:514} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:301)
[2021-12-29 12:10:25,280] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2021-12-29 12:10:25,281] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:101)
[2021-12-29 12:10:25,283] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:109)
[2021-12-29 12:10:25,284] {spark_submit.py:514} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:107)
[2021-12-29 12:10:25,285] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2021-12-29 12:10:25,286] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2021-12-29 12:10:25,287] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2021-12-29 12:10:25,288] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2021-12-29 12:10:25,289] {spark_submit.py:514} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-29 12:10:25,289] {spark_submit.py:514} INFO - Caused by: java.io.IOException: Failed to connect to spark:7077
[2021-12-29 12:10:25,290] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:288)
[2021-12-29 12:10:25,291] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:218)
[2021-12-29 12:10:25,292] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:230)
[2021-12-29 12:10:25,293] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2021-12-29 12:10:25,294] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2021-12-29 12:10:25,295] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2021-12-29 12:10:25,295] {spark_submit.py:514} INFO - ... 4 more
[2021-12-29 12:10:25,296] {spark_submit.py:514} INFO - Caused by: java.net.UnknownHostException: spark
[2021-12-29 12:10:25,297] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
[2021-12-29 12:10:25,298] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509)
[2021-12-29 12:10:25,299] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1368)
[2021-12-29 12:10:25,300] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1302)
[2021-12-29 12:10:25,301] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getByName(InetAddress.java:1252)
[2021-12-29 12:10:25,302] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156)
[2021-12-29 12:10:25,303] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153)
[2021-12-29 12:10:25,304] {spark_submit.py:514} INFO - at java.base/java.security.AccessController.doPrivileged(Native Method)
[2021-12-29 12:10:25,305] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153)
[2021-12-29 12:10:25,305] {spark_submit.py:514} INFO - at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41)
[2021-12-29 12:10:25,306] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
[2021-12-29 12:10:25,307] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53)
[2021-12-29 12:10:25,308] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
[2021-12-29 12:10:25,309] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
[2021-12-29 12:10:25,310] {spark_submit.py:514} INFO - at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
[2021-12-29 12:10:25,311] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:206)
[2021-12-29 12:10:25,313] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46)
[2021-12-29 12:10:25,314] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:180)
[2021-12-29 12:10:25,314] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:166)
[2021-12-29 12:10:25,316] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
[2021-12-29 12:10:25,317] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
[2021-12-29 12:10:25,317] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
[2021-12-29 12:10:25,318] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
[2021-12-29 12:10:25,319] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
[2021-12-29 12:10:25,321] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
[2021-12-29 12:10:25,322] {spark_submit.py:514} INFO - at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
[2021-12-29 12:10:25,323] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:1008)
[2021-12-29 12:10:25,324] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:516)
[2021-12-29 12:10:25,325] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
[2021-12-29 12:10:25,326] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
[2021-12-29 12:10:25,327] {spark_submit.py:514} INFO - at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[2021-12-29 12:10:25,329] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
[2021-12-29 12:10:25,330] {spark_submit.py:514} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[2021-12-29 12:10:25,331] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[2021-12-29 12:10:25,333] {spark_submit.py:514} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2021-12-29 12:10:25,333] {spark_submit.py:514} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2021-12-29 12:10:25,334] {spark_submit.py:514} INFO - ... 1 more
[2021-12-29 12:10:44,847] {spark_submit.py:514} INFO - 21/12/29 12:10:44 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2021-12-29 12:10:44,872] {spark_submit.py:514} INFO - 21/12/29 12:10:44 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master spark:7077
[2021-12-29 12:10:44,873] {spark_submit.py:514} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2021-12-29 12:10:44,875] {spark_submit.py:514} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:301)
[2021-12-29 12:10:44,876] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2021-12-29 12:10:44,879] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:101)
[2021-12-29 12:10:44,880] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:109)
[2021-12-29 12:10:44,881] {spark_submit.py:514} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:107)
[2021-12-29 12:10:44,882] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2021-12-29 12:10:44,887] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2021-12-29 12:10:44,889] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2021-12-29 12:10:44,891] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2021-12-29 12:10:44,892] {spark_submit.py:514} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-29 12:10:44,894] {spark_submit.py:514} INFO - Caused by: java.io.IOException: Failed to connect to spark:7077
[2021-12-29 12:10:44,897] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:288)
[2021-12-29 12:10:44,900] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:218)
[2021-12-29 12:10:44,902] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:230)
[2021-12-29 12:10:44,902] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2021-12-29 12:10:44,903] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2021-12-29 12:10:44,905] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2021-12-29 12:10:44,906] {spark_submit.py:514} INFO - ... 4 more
[2021-12-29 12:10:44,906] {spark_submit.py:514} INFO - Caused by: java.net.UnknownHostException: spark
[2021-12-29 12:10:44,907] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
[2021-12-29 12:10:44,908] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509)
[2021-12-29 12:10:44,909] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1368)
[2021-12-29 12:10:44,910] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1302)
[2021-12-29 12:10:44,911] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getByName(InetAddress.java:1252)
[2021-12-29 12:10:44,912] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156)
[2021-12-29 12:10:44,913] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153)
[2021-12-29 12:10:44,914] {spark_submit.py:514} INFO - at java.base/java.security.AccessController.doPrivileged(Native Method)
[2021-12-29 12:10:44,915] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153)
[2021-12-29 12:10:44,916] {spark_submit.py:514} INFO - at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41)
[2021-12-29 12:10:44,917] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
[2021-12-29 12:10:44,919] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53)
[2021-12-29 12:10:44,920] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
[2021-12-29 12:10:44,921] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
[2021-12-29 12:10:44,922] {spark_submit.py:514} INFO - at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
[2021-12-29 12:10:44,923] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:206)
[2021-12-29 12:10:44,924] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46)
[2021-12-29 12:10:44,925] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:180)
[2021-12-29 12:10:44,926] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:166)
[2021-12-29 12:10:44,927] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
[2021-12-29 12:10:44,928] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
[2021-12-29 12:10:44,929] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
[2021-12-29 12:10:44,930] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
[2021-12-29 12:10:44,931] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
[2021-12-29 12:10:44,932] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
[2021-12-29 12:10:44,932] {spark_submit.py:514} INFO - at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
[2021-12-29 12:10:44,933] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:1008)
[2021-12-29 12:10:44,934] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:516)
[2021-12-29 12:10:44,935] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
[2021-12-29 12:10:44,936] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
[2021-12-29 12:10:44,936] {spark_submit.py:514} INFO - at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[2021-12-29 12:10:44,937] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
[2021-12-29 12:10:44,938] {spark_submit.py:514} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[2021-12-29 12:10:44,939] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[2021-12-29 12:10:44,940] {spark_submit.py:514} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2021-12-29 12:10:44,940] {spark_submit.py:514} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2021-12-29 12:10:44,941] {spark_submit.py:514} INFO - ... 1 more
[2021-12-29 12:11:04,820] {spark_submit.py:514} INFO - 21/12/29 12:11:04 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2021-12-29 12:11:04,835] {spark_submit.py:514} INFO - 21/12/29 12:11:04 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master spark:7077
[2021-12-29 12:11:04,836] {spark_submit.py:514} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2021-12-29 12:11:04,837] {spark_submit.py:514} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:301)
[2021-12-29 12:11:04,838] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2021-12-29 12:11:04,838] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:101)
[2021-12-29 12:11:04,839] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:109)
[2021-12-29 12:11:04,840] {spark_submit.py:514} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:107)
[2021-12-29 12:11:04,841] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2021-12-29 12:11:04,842] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2021-12-29 12:11:04,842] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2021-12-29 12:11:04,843] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2021-12-29 12:11:04,845] {spark_submit.py:514} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-29 12:11:04,845] {spark_submit.py:514} INFO - Caused by: java.io.IOException: Failed to connect to spark:7077
[2021-12-29 12:11:04,846] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:288)
[2021-12-29 12:11:04,847] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:218)
[2021-12-29 12:11:04,848] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:230)
[2021-12-29 12:11:04,848] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2021-12-29 12:11:04,849] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2021-12-29 12:11:04,850] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2021-12-29 12:11:04,851] {spark_submit.py:514} INFO - ... 4 more
[2021-12-29 12:11:04,851] {spark_submit.py:514} INFO - Caused by: java.net.UnknownHostException: spark
[2021-12-29 12:11:04,852] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
[2021-12-29 12:11:04,853] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509)
[2021-12-29 12:11:04,853] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1368)
[2021-12-29 12:11:04,854] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1302)
[2021-12-29 12:11:04,855] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getByName(InetAddress.java:1252)
[2021-12-29 12:11:04,855] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156)
[2021-12-29 12:11:04,856] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153)
[2021-12-29 12:11:04,857] {spark_submit.py:514} INFO - at java.base/java.security.AccessController.doPrivileged(Native Method)
[2021-12-29 12:11:04,857] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153)
[2021-12-29 12:11:04,858] {spark_submit.py:514} INFO - at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41)
[2021-12-29 12:11:04,859] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
[2021-12-29 12:11:04,859] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53)
[2021-12-29 12:11:04,860] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
[2021-12-29 12:11:04,861] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
[2021-12-29 12:11:04,862] {spark_submit.py:514} INFO - at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
[2021-12-29 12:11:04,862] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:206)
[2021-12-29 12:11:04,863] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46)
[2021-12-29 12:11:04,863] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:180)
[2021-12-29 12:11:04,864] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:166)
[2021-12-29 12:11:04,865] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
[2021-12-29 12:11:04,865] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
[2021-12-29 12:11:04,866] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
[2021-12-29 12:11:04,867] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
[2021-12-29 12:11:04,868] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
[2021-12-29 12:11:04,868] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
[2021-12-29 12:11:04,869] {spark_submit.py:514} INFO - at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
[2021-12-29 12:11:04,869] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:1008)
[2021-12-29 12:11:04,870] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:516)
[2021-12-29 12:11:04,871] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
[2021-12-29 12:11:04,871] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
[2021-12-29 12:11:04,872] {spark_submit.py:514} INFO - at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[2021-12-29 12:11:04,873] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
[2021-12-29 12:11:04,873] {spark_submit.py:514} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[2021-12-29 12:11:04,874] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[2021-12-29 12:11:04,874] {spark_submit.py:514} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2021-12-29 12:11:04,875] {spark_submit.py:514} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2021-12-29 12:11:04,876] {spark_submit.py:514} INFO - ... 1 more
[2021-12-29 12:11:24,822] {spark_submit.py:514} INFO - 21/12/29 12:11:24 ERROR StandaloneSchedulerBackend: Application has been killed. Reason: All masters are unresponsive! Giving up.
[2021-12-29 12:11:24,828] {spark_submit.py:514} INFO - 21/12/29 12:11:24 WARN StandaloneSchedulerBackend: Application ID is not initialized yet.
[2021-12-29 12:11:24,860] {spark_submit.py:514} INFO - 21/12/29 12:11:24 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 45711.
[2021-12-29 12:11:24,862] {spark_submit.py:514} INFO - 21/12/29 12:11:24 INFO NettyBlockTransferService: Server created on 6bdda4c19a85:45711
[2021-12-29 12:11:24,868] {spark_submit.py:514} INFO - 21/12/29 12:11:24 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2021-12-29 12:11:24,872] {spark_submit.py:514} INFO - 21/12/29 12:11:24 INFO SparkUI: Stopped Spark web UI at http://6bdda4c19a85:4042
[2021-12-29 12:11:24,892] {spark_submit.py:514} INFO - 21/12/29 12:11:24 INFO StandaloneSchedulerBackend: Shutting down all executors
[2021-12-29 12:11:24,900] {spark_submit.py:514} INFO - 21/12/29 12:11:24 INFO CoarseGrainedSchedulerBackend$DriverEndpoint: Asking each executor to shut down
[2021-12-29 12:11:24,902] {spark_submit.py:514} INFO - 21/12/29 12:11:24 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 6bdda4c19a85, 45711, None)
[2021-12-29 12:11:24,916] {spark_submit.py:514} INFO - 21/12/29 12:11:24 INFO BlockManagerMasterEndpoint: Registering block manager 6bdda4c19a85:45711 with 434.4 MiB RAM, BlockManagerId(driver, 6bdda4c19a85, 45711, None)
[2021-12-29 12:11:24,920] {spark_submit.py:514} INFO - 21/12/29 12:11:24 WARN StandaloneAppClient$ClientEndpoint: Drop UnregisterApplication(null) because has not yet connected to master
[2021-12-29 12:11:24,930] {spark_submit.py:514} INFO - 21/12/29 12:11:24 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 6bdda4c19a85, 45711, None)
[2021-12-29 12:11:24,937] {spark_submit.py:514} INFO - 21/12/29 12:11:24 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 6bdda4c19a85, 45711, None)
[2021-12-29 12:11:24,956] {spark_submit.py:514} INFO - 21/12/29 12:11:24 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2021-12-29 12:11:25,003] {spark_submit.py:514} INFO - 21/12/29 12:11:25 INFO MemoryStore: MemoryStore cleared
[2021-12-29 12:11:25,005] {spark_submit.py:514} INFO - 21/12/29 12:11:25 INFO BlockManager: BlockManager stopped
[2021-12-29 12:11:25,036] {spark_submit.py:514} INFO - 21/12/29 12:11:25 INFO BlockManagerMaster: BlockManagerMaster stopped
[2021-12-29 12:11:25,046] {spark_submit.py:514} INFO - 21/12/29 12:11:25 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2021-12-29 12:11:25,137] {spark_submit.py:514} INFO - 21/12/29 12:11:25 INFO SparkContext: Successfully stopped SparkContext
[2021-12-29 12:11:25,390] {spark_submit.py:514} INFO - 21/12/29 12:11:25 ERROR SparkContext: Error initializing SparkContext.
[2021-12-29 12:11:25,391] {spark_submit.py:514} INFO - java.lang.IllegalArgumentException: requirement failed: Can only call getServletHandlers on a running MetricsSystem
[2021-12-29 12:11:25,392] {spark_submit.py:514} INFO - at scala.Predef$.require(Predef.scala:281)
[2021-12-29 12:11:25,394] {spark_submit.py:514} INFO - at org.apache.spark.metrics.MetricsSystem.getServletHandlers(MetricsSystem.scala:89)
[2021-12-29 12:11:25,395] {spark_submit.py:514} INFO - at org.apache.spark.SparkContext.<init>(SparkContext.scala:603)
[2021-12-29 12:11:25,397] {spark_submit.py:514} INFO - at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2021-12-29 12:11:25,399] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2021-12-29 12:11:25,400] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2021-12-29 12:11:25,404] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2021-12-29 12:11:25,406] {spark_submit.py:514} INFO - at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[2021-12-29 12:11:25,407] {spark_submit.py:514} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2021-12-29 12:11:25,409] {spark_submit.py:514} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2021-12-29 12:11:25,411] {spark_submit.py:514} INFO - at py4j.Gateway.invoke(Gateway.java:238)
[2021-12-29 12:11:25,412] {spark_submit.py:514} INFO - at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2021-12-29 12:11:25,413] {spark_submit.py:514} INFO - at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2021-12-29 12:11:25,414] {spark_submit.py:514} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2021-12-29 12:11:25,416] {spark_submit.py:514} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2021-12-29 12:11:25,417] {spark_submit.py:514} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-29 12:11:25,417] {spark_submit.py:514} INFO - 21/12/29 12:11:25 INFO SparkContext: SparkContext already stopped.
[2021-12-29 12:11:25,419] {spark_submit.py:514} INFO - Traceback (most recent call last):
[2021-12-29 12:11:25,420] {spark_submit.py:514} INFO - File "/opt/***/jobs/get_ads_per_county.py", line 13, in <module>
[2021-12-29 12:11:25,421] {spark_submit.py:514} INFO - .appName("Get Ads per county") \
[2021-12-29 12:11:25,422] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/session.py", line 228, in getOrCreate
[2021-12-29 12:11:25,429] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 392, in getOrCreate
[2021-12-29 12:11:25,431] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 147, in __init__
[2021-12-29 12:11:25,434] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 209, in _do_init
[2021-12-29 12:11:25,435] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 329, in _initialize_context
[2021-12-29 12:11:25,436] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/py4j-0.10.9.2-src.zip/py4j/java_gateway.py", line 1574, in __call__
[2021-12-29 12:11:25,437] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/py4j-0.10.9.2-src.zip/py4j/protocol.py", line 328, in get_return_value
[2021-12-29 12:11:25,438] {spark_submit.py:514} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling None.org.apache.spark.api.java.JavaSparkContext.
[2021-12-29 12:11:25,439] {spark_submit.py:514} INFO - : java.lang.IllegalArgumentException: requirement failed: Can only call getServletHandlers on a running MetricsSystem
[2021-12-29 12:11:25,440] {spark_submit.py:514} INFO - at scala.Predef$.require(Predef.scala:281)
[2021-12-29 12:11:25,442] {spark_submit.py:514} INFO - at org.apache.spark.metrics.MetricsSystem.getServletHandlers(MetricsSystem.scala:89)
[2021-12-29 12:11:25,443] {spark_submit.py:514} INFO - at org.apache.spark.SparkContext.<init>(SparkContext.scala:603)
[2021-12-29 12:11:25,444] {spark_submit.py:514} INFO - at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2021-12-29 12:11:25,445] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2021-12-29 12:11:25,447] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2021-12-29 12:11:25,448] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2021-12-29 12:11:25,449] {spark_submit.py:514} INFO - at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[2021-12-29 12:11:25,450] {spark_submit.py:514} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2021-12-29 12:11:25,451] {spark_submit.py:514} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2021-12-29 12:11:25,452] {spark_submit.py:514} INFO - at py4j.Gateway.invoke(Gateway.java:238)
[2021-12-29 12:11:25,453] {spark_submit.py:514} INFO - at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2021-12-29 12:11:25,455] {spark_submit.py:514} INFO - at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2021-12-29 12:11:25,456] {spark_submit.py:514} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2021-12-29 12:11:25,457] {spark_submit.py:514} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2021-12-29 12:11:25,458] {spark_submit.py:514} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-29 12:11:25,460] {spark_submit.py:514} INFO - 
[2021-12-29 12:11:25,548] {spark_submit.py:514} INFO - 21/12/29 12:11:25 INFO ShutdownHookManager: Shutdown hook called
[2021-12-29 12:11:25,550] {spark_submit.py:514} INFO - 21/12/29 12:11:25 INFO ShutdownHookManager: Deleting directory /tmp/spark-e5d63430-bb6a-4cf9-837b-d53f5b2cecd8
[2021-12-29 12:11:25,556] {spark_submit.py:514} INFO - 21/12/29 12:11:25 INFO ShutdownHookManager: Deleting directory /tmp/spark-9956cffe-ddd2-4f9f-b055-b54d1b9aed73
[2021-12-29 12:11:25,717] {taskinstance.py:1703} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 179, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 446, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark:7077 --conf spark.master=spark://spark:7077 --name scrap data --verbose /opt/***/jobs/get_ads_per_county.py donegal. Error code is: 1.
[2021-12-29 12:11:25,725] {taskinstance.py:1280} INFO - Marking task as UP_FOR_RETRY. dag_id=scraping_daft_donegal, task_id=scrap_data, execution_date=20211228T092500, start_date=20211229T121001, end_date=20211229T121125
[2021-12-29 12:11:25,745] {standard_task_runner.py:91} ERROR - Failed to execute job 5372 for task scrap_data
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 179, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 446, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark:7077 --conf spark.master=spark://spark:7077 --name scrap data --verbose /opt/***/jobs/get_ads_per_county.py donegal. Error code is: 1.
[2021-12-29 12:11:25,784] {local_task_job.py:154} INFO - Task exited with return code 1
[2021-12-29 12:11:25,896] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
