[2021-12-28 13:43:24,093] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: scraping_daft_meath.persist_data scheduled__2021-12-27T10:25:00+00:00 [queued]>
[2021-12-28 13:43:24,203] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: scraping_daft_meath.persist_data scheduled__2021-12-27T10:25:00+00:00 [queued]>
[2021-12-28 13:43:24,205] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-28 13:43:24,207] {taskinstance.py:1242} INFO - Starting attempt 2 of 4
[2021-12-28 13:43:24,208] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-28 13:43:24,300] {taskinstance.py:1262} INFO - Executing <Task(SparkSubmitOperator): persist_data> on 2021-12-27 10:25:00+00:00
[2021-12-28 13:43:24,314] {standard_task_runner.py:52} INFO - Started process 54252 to run task
[2021-12-28 13:43:24,349] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'scraping_daft_meath', 'persist_data', 'scheduled__2021-12-27T10:25:00+00:00', '--job-id', '5108', '--raw', '--subdir', 'DAGS_FOLDER/scraping_daft_meath.py', '--cfg-path', '/tmp/tmpgqharhks', '--error-file', '/tmp/tmptm6jd71b']
[2021-12-28 13:43:24,356] {standard_task_runner.py:77} INFO - Job 5108: Subtask persist_data
[2021-12-28 13:43:24,656] {logging_mixin.py:109} INFO - Running <TaskInstance: scraping_daft_meath.persist_data scheduled__2021-12-27T10:25:00+00:00 [running]> on host 0c125a5bba95
[2021-12-28 13:43:25,144] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=clement.liscoet@gmail.com
AIRFLOW_CTX_DAG_OWNER=clemoni
AIRFLOW_CTX_DAG_ID=scraping_daft_meath
AIRFLOW_CTX_TASK_ID=persist_data
AIRFLOW_CTX_EXECUTION_DATE=2021-12-27T10:25:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-27T10:25:00+00:00
[2021-12-28 13:43:25,206] {base.py:79} INFO - Using connection to: id: spark_default. Host: spark://spark:7077, Port: None, Schema: , Login: ***, Password: ***, extra: {}
[2021-12-28 13:43:25,219] {spark_submit.py:360} INFO - Spark-Submit cmd: spark-submit --master spark://spark:7077 --conf spark.master=spark://spark:7077 --name persist data --verbose /opt/***/jobs/persist_db.py meath
[2021-12-28 13:43:32,411] {spark_submit.py:514} INFO - Using properties file: null
[2021-12-28 13:43:32,693] {spark_submit.py:514} INFO - WARNING: An illegal reflective access operation has occurred
[2021-12-28 13:43:32,695] {spark_submit.py:514} INFO - WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/home/***/.local/lib/python3.6/site-packages/pyspark/jars/spark-unsafe_2.12-3.2.0.jar) to constructor java.nio.DirectByteBuffer(long,int)
[2021-12-28 13:43:32,696] {spark_submit.py:514} INFO - WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
[2021-12-28 13:43:32,698] {spark_submit.py:514} INFO - WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[2021-12-28 13:43:32,699] {spark_submit.py:514} INFO - WARNING: All illegal access operations will be denied in a future release
[2021-12-28 13:43:32,795] {spark_submit.py:514} INFO - Parsed arguments:
[2021-12-28 13:43:32,797] {spark_submit.py:514} INFO - master                  spark://spark:7077
[2021-12-28 13:43:32,798] {spark_submit.py:514} INFO - deployMode              null
[2021-12-28 13:43:32,802] {spark_submit.py:514} INFO - executorMemory          null
[2021-12-28 13:43:32,803] {spark_submit.py:514} INFO - executorCores           null
[2021-12-28 13:43:32,804] {spark_submit.py:514} INFO - totalExecutorCores      null
[2021-12-28 13:43:32,805] {spark_submit.py:514} INFO - propertiesFile          null
[2021-12-28 13:43:32,806] {spark_submit.py:514} INFO - driverMemory            null
[2021-12-28 13:43:32,807] {spark_submit.py:514} INFO - driverCores             null
[2021-12-28 13:43:32,808] {spark_submit.py:514} INFO - driverExtraClassPath    null
[2021-12-28 13:43:32,809] {spark_submit.py:514} INFO - driverExtraLibraryPath  null
[2021-12-28 13:43:32,811] {spark_submit.py:514} INFO - driverExtraJavaOptions  null
[2021-12-28 13:43:32,812] {spark_submit.py:514} INFO - supervise               false
[2021-12-28 13:43:32,813] {spark_submit.py:514} INFO - queue                   null
[2021-12-28 13:43:32,814] {spark_submit.py:514} INFO - numExecutors            null
[2021-12-28 13:43:32,815] {spark_submit.py:514} INFO - files                   null
[2021-12-28 13:43:32,817] {spark_submit.py:514} INFO - pyFiles                 null
[2021-12-28 13:43:32,818] {spark_submit.py:514} INFO - archives                null
[2021-12-28 13:43:32,819] {spark_submit.py:514} INFO - mainClass               null
[2021-12-28 13:43:32,820] {spark_submit.py:514} INFO - primaryResource         file:/opt/***/jobs/persist_db.py
[2021-12-28 13:43:32,821] {spark_submit.py:514} INFO - name                    persist data
[2021-12-28 13:43:32,822] {spark_submit.py:514} INFO - childArgs               [meath]
[2021-12-28 13:43:32,823] {spark_submit.py:514} INFO - jars                    null
[2021-12-28 13:43:32,824] {spark_submit.py:514} INFO - packages                null
[2021-12-28 13:43:32,825] {spark_submit.py:514} INFO - packagesExclusions      null
[2021-12-28 13:43:32,825] {spark_submit.py:514} INFO - repositories            null
[2021-12-28 13:43:32,826] {spark_submit.py:514} INFO - verbose                 true
[2021-12-28 13:43:32,827] {spark_submit.py:514} INFO - 
[2021-12-28 13:43:32,828] {spark_submit.py:514} INFO - Spark properties used, including those specified through
[2021-12-28 13:43:32,830] {spark_submit.py:514} INFO - --conf and those from the properties file null:
[2021-12-28 13:43:32,831] {spark_submit.py:514} INFO - (spark.master,spark://spark:7077)
[2021-12-28 13:43:32,832] {spark_submit.py:514} INFO - 
[2021-12-28 13:43:32,833] {spark_submit.py:514} INFO - 
[2021-12-28 13:43:33,798] {spark_submit.py:514} INFO - Main class:
[2021-12-28 13:43:33,799] {spark_submit.py:514} INFO - org.apache.spark.deploy.PythonRunner
[2021-12-28 13:43:33,801] {spark_submit.py:514} INFO - Arguments:
[2021-12-28 13:43:33,802] {spark_submit.py:514} INFO - file:/opt/***/jobs/persist_db.py
[2021-12-28 13:43:33,803] {spark_submit.py:514} INFO - null
[2021-12-28 13:43:33,804] {spark_submit.py:514} INFO - meath
[2021-12-28 13:43:33,805] {spark_submit.py:514} INFO - --verbose
[2021-12-28 13:43:33,808] {spark_submit.py:514} INFO - Spark config:
[2021-12-28 13:43:33,809] {spark_submit.py:514} INFO - (spark.master,spark://spark:7077)
[2021-12-28 13:43:33,810] {spark_submit.py:514} INFO - (spark.app.name,persist data)
[2021-12-28 13:43:33,811] {spark_submit.py:514} INFO - (spark.submit.pyFiles,)
[2021-12-28 13:43:33,812] {spark_submit.py:514} INFO - (spark.submit.deployMode,client)
[2021-12-28 13:43:33,813] {spark_submit.py:514} INFO - Classpath elements:
[2021-12-28 13:43:33,814] {spark_submit.py:514} INFO - 
[2021-12-28 13:43:33,815] {spark_submit.py:514} INFO - 
[2021-12-28 13:43:33,816] {spark_submit.py:514} INFO - 
[2021-12-28 13:43:36,880] {spark_submit.py:514} INFO - Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
[2021-12-28 13:43:36,919] {spark_submit.py:514} INFO - 21/12/28 13:43:36 INFO SparkContext: Running Spark version 3.2.0
[2021-12-28 13:43:37,392] {spark_submit.py:514} INFO - 21/12/28 13:43:37 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2021-12-28 13:43:38,135] {spark_submit.py:514} INFO - 21/12/28 13:43:38 INFO ResourceUtils: ==============================================================
[2021-12-28 13:43:38,136] {spark_submit.py:514} INFO - 21/12/28 13:43:38 INFO ResourceUtils: No custom resources configured for spark.driver.
[2021-12-28 13:43:38,137] {spark_submit.py:514} INFO - 21/12/28 13:43:38 INFO ResourceUtils: ==============================================================
[2021-12-28 13:43:38,139] {spark_submit.py:514} INFO - 21/12/28 13:43:38 INFO SparkContext: Submitted application: Persist DB
[2021-12-28 13:43:38,224] {spark_submit.py:514} INFO - 21/12/28 13:43:38 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2021-12-28 13:43:38,267] {spark_submit.py:514} INFO - 21/12/28 13:43:38 INFO ResourceProfile: Limiting resource is cpu
[2021-12-28 13:43:38,270] {spark_submit.py:514} INFO - 21/12/28 13:43:38 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2021-12-28 13:43:38,627] {spark_submit.py:514} INFO - 21/12/28 13:43:38 INFO SecurityManager: Changing view acls to: ***
[2021-12-28 13:43:38,637] {spark_submit.py:514} INFO - 21/12/28 13:43:38 INFO SecurityManager: Changing modify acls to: ***
[2021-12-28 13:43:38,640] {spark_submit.py:514} INFO - 21/12/28 13:43:38 INFO SecurityManager: Changing view acls groups to:
[2021-12-28 13:43:38,643] {spark_submit.py:514} INFO - 21/12/28 13:43:38 INFO SecurityManager: Changing modify acls groups to:
[2021-12-28 13:43:38,650] {spark_submit.py:514} INFO - 21/12/28 13:43:38 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(***); groups with view permissions: Set(); users  with modify permissions: Set(***); groups with modify permissions: Set()
[2021-12-28 13:43:40,311] {spark_submit.py:514} INFO - 21/12/28 13:43:40 INFO Utils: Successfully started service 'sparkDriver' on port 40261.
[2021-12-28 13:43:40,545] {spark_submit.py:514} INFO - 21/12/28 13:43:40 INFO SparkEnv: Registering MapOutputTracker
[2021-12-28 13:43:40,670] {spark_submit.py:514} INFO - 21/12/28 13:43:40 INFO SparkEnv: Registering BlockManagerMaster
[2021-12-28 13:43:40,717] {spark_submit.py:514} INFO - 21/12/28 13:43:40 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2021-12-28 13:43:40,718] {spark_submit.py:514} INFO - 21/12/28 13:43:40 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2021-12-28 13:43:40,730] {spark_submit.py:514} INFO - 21/12/28 13:43:40 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2021-12-28 13:43:40,867] {spark_submit.py:514} INFO - 21/12/28 13:43:40 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-09c03969-ae9c-417a-b31c-bed171f67965
[2021-12-28 13:43:41,074] {spark_submit.py:514} INFO - 21/12/28 13:43:41 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2021-12-28 13:43:41,151] {spark_submit.py:514} INFO - 21/12/28 13:43:41 INFO SparkEnv: Registering OutputCommitCoordinator
[2021-12-28 13:43:42,016] {spark_submit.py:514} INFO - 21/12/28 13:43:42 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2021-12-28 13:43:42,018] {spark_submit.py:514} INFO - 21/12/28 13:43:42 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.
[2021-12-28 13:43:42,023] {spark_submit.py:514} INFO - 21/12/28 13:43:42 WARN Utils: Service 'SparkUI' could not bind on port 4042. Attempting port 4043.
[2021-12-28 13:43:42,030] {spark_submit.py:514} INFO - 21/12/28 13:43:42 WARN Utils: Service 'SparkUI' could not bind on port 4043. Attempting port 4044.
[2021-12-28 13:43:42,060] {spark_submit.py:514} INFO - 21/12/28 13:43:42 INFO Utils: Successfully started service 'SparkUI' on port 4044.
[2021-12-28 13:43:42,390] {spark_submit.py:514} INFO - 21/12/28 13:43:42 INFO SparkUI: Bound SparkUI to 0.0.0.0, and started at http://0c125a5bba95:4044
[2021-12-28 13:43:43,115] {spark_submit.py:514} INFO - 21/12/28 13:43:43 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2021-12-28 13:43:43,448] {spark_submit.py:514} INFO - 21/12/28 13:43:43 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master spark:7077
[2021-12-28 13:43:43,450] {spark_submit.py:514} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2021-12-28 13:43:43,451] {spark_submit.py:514} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:301)
[2021-12-28 13:43:43,453] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2021-12-28 13:43:43,456] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:101)
[2021-12-28 13:43:43,458] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:109)
[2021-12-28 13:43:43,459] {spark_submit.py:514} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:107)
[2021-12-28 13:43:43,460] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2021-12-28 13:43:43,462] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2021-12-28 13:43:43,463] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2021-12-28 13:43:43,464] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2021-12-28 13:43:43,465] {spark_submit.py:514} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-28 13:43:43,465] {spark_submit.py:514} INFO - Caused by: java.io.IOException: Failed to connect to spark:7077
[2021-12-28 13:43:43,466] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:288)
[2021-12-28 13:43:43,467] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:218)
[2021-12-28 13:43:43,468] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:230)
[2021-12-28 13:43:43,469] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2021-12-28 13:43:43,471] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2021-12-28 13:43:43,472] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2021-12-28 13:43:43,473] {spark_submit.py:514} INFO - ... 4 more
[2021-12-28 13:43:43,474] {spark_submit.py:514} INFO - Caused by: java.net.UnknownHostException: spark
[2021-12-28 13:43:43,476] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
[2021-12-28 13:43:43,477] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509)
[2021-12-28 13:43:43,478] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1368)
[2021-12-28 13:43:43,479] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1302)
[2021-12-28 13:43:43,480] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getByName(InetAddress.java:1252)
[2021-12-28 13:43:43,481] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156)
[2021-12-28 13:43:43,482] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153)
[2021-12-28 13:43:43,483] {spark_submit.py:514} INFO - at java.base/java.security.AccessController.doPrivileged(Native Method)
[2021-12-28 13:43:43,484] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153)
[2021-12-28 13:43:43,485] {spark_submit.py:514} INFO - at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41)
[2021-12-28 13:43:43,486] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
[2021-12-28 13:43:43,487] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53)
[2021-12-28 13:43:43,488] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
[2021-12-28 13:43:43,489] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
[2021-12-28 13:43:43,491] {spark_submit.py:514} INFO - at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
[2021-12-28 13:43:43,493] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:206)
[2021-12-28 13:43:43,497] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46)
[2021-12-28 13:43:43,498] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:180)
[2021-12-28 13:43:43,499] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:166)
[2021-12-28 13:43:43,500] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
[2021-12-28 13:43:43,501] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
[2021-12-28 13:43:43,502] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
[2021-12-28 13:43:43,503] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
[2021-12-28 13:43:43,504] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
[2021-12-28 13:43:43,505] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
[2021-12-28 13:43:43,508] {spark_submit.py:514} INFO - at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
[2021-12-28 13:43:43,511] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:1008)
[2021-12-28 13:43:43,513] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:516)
[2021-12-28 13:43:43,514] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
[2021-12-28 13:43:43,516] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
[2021-12-28 13:43:43,519] {spark_submit.py:514} INFO - at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[2021-12-28 13:43:43,521] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
[2021-12-28 13:43:43,523] {spark_submit.py:514} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[2021-12-28 13:43:43,525] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[2021-12-28 13:43:43,528] {spark_submit.py:514} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2021-12-28 13:43:43,531] {spark_submit.py:514} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2021-12-28 13:43:43,532] {spark_submit.py:514} INFO - ... 1 more
[2021-12-28 13:44:03,108] {spark_submit.py:514} INFO - 21/12/28 13:44:03 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2021-12-28 13:44:03,126] {spark_submit.py:514} INFO - 21/12/28 13:44:03 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master spark:7077
[2021-12-28 13:44:03,127] {spark_submit.py:514} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2021-12-28 13:44:03,128] {spark_submit.py:514} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:301)
[2021-12-28 13:44:03,129] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2021-12-28 13:44:03,130] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:101)
[2021-12-28 13:44:03,131] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:109)
[2021-12-28 13:44:03,133] {spark_submit.py:514} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:107)
[2021-12-28 13:44:03,133] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2021-12-28 13:44:03,134] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2021-12-28 13:44:03,135] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2021-12-28 13:44:03,136] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2021-12-28 13:44:03,137] {spark_submit.py:514} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-28 13:44:03,138] {spark_submit.py:514} INFO - Caused by: java.io.IOException: Failed to connect to spark:7077
[2021-12-28 13:44:03,139] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:288)
[2021-12-28 13:44:03,140] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:218)
[2021-12-28 13:44:03,141] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:230)
[2021-12-28 13:44:03,141] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2021-12-28 13:44:03,142] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2021-12-28 13:44:03,143] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2021-12-28 13:44:03,144] {spark_submit.py:514} INFO - ... 4 more
[2021-12-28 13:44:03,145] {spark_submit.py:514} INFO - Caused by: java.net.UnknownHostException: spark
[2021-12-28 13:44:03,146] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
[2021-12-28 13:44:03,146] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509)
[2021-12-28 13:44:03,147] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1368)
[2021-12-28 13:44:03,148] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1302)
[2021-12-28 13:44:03,149] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getByName(InetAddress.java:1252)
[2021-12-28 13:44:03,149] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156)
[2021-12-28 13:44:03,150] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153)
[2021-12-28 13:44:03,151] {spark_submit.py:514} INFO - at java.base/java.security.AccessController.doPrivileged(Native Method)
[2021-12-28 13:44:03,152] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153)
[2021-12-28 13:44:03,152] {spark_submit.py:514} INFO - at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41)
[2021-12-28 13:44:03,153] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
[2021-12-28 13:44:03,154] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53)
[2021-12-28 13:44:03,155] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
[2021-12-28 13:44:03,156] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
[2021-12-28 13:44:03,156] {spark_submit.py:514} INFO - at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
[2021-12-28 13:44:03,157] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:206)
[2021-12-28 13:44:03,158] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46)
[2021-12-28 13:44:03,159] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:180)
[2021-12-28 13:44:03,160] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:166)
[2021-12-28 13:44:03,161] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
[2021-12-28 13:44:03,161] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
[2021-12-28 13:44:03,162] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
[2021-12-28 13:44:03,163] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
[2021-12-28 13:44:03,164] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
[2021-12-28 13:44:03,164] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
[2021-12-28 13:44:03,165] {spark_submit.py:514} INFO - at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
[2021-12-28 13:44:03,166] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:1008)
[2021-12-28 13:44:03,166] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:516)
[2021-12-28 13:44:03,167] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
[2021-12-28 13:44:03,168] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
[2021-12-28 13:44:03,168] {spark_submit.py:514} INFO - at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[2021-12-28 13:44:03,169] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
[2021-12-28 13:44:03,170] {spark_submit.py:514} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[2021-12-28 13:44:03,170] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[2021-12-28 13:44:03,171] {spark_submit.py:514} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2021-12-28 13:44:03,172] {spark_submit.py:514} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2021-12-28 13:44:03,172] {spark_submit.py:514} INFO - ... 1 more
[2021-12-28 13:44:23,075] {spark_submit.py:514} INFO - 21/12/28 13:44:23 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2021-12-28 13:44:23,093] {spark_submit.py:514} INFO - 21/12/28 13:44:23 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master spark:7077
[2021-12-28 13:44:23,094] {spark_submit.py:514} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2021-12-28 13:44:23,095] {spark_submit.py:514} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:301)
[2021-12-28 13:44:23,097] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2021-12-28 13:44:23,103] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:101)
[2021-12-28 13:44:23,105] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:109)
[2021-12-28 13:44:23,109] {spark_submit.py:514} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:107)
[2021-12-28 13:44:23,110] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2021-12-28 13:44:23,114] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2021-12-28 13:44:23,116] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2021-12-28 13:44:23,117] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2021-12-28 13:44:23,117] {spark_submit.py:514} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-28 13:44:23,122] {spark_submit.py:514} INFO - Caused by: java.io.IOException: Failed to connect to spark:7077
[2021-12-28 13:44:23,123] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:288)
[2021-12-28 13:44:23,124] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:218)
[2021-12-28 13:44:23,125] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:230)
[2021-12-28 13:44:23,126] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2021-12-28 13:44:23,127] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2021-12-28 13:44:23,127] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2021-12-28 13:44:23,128] {spark_submit.py:514} INFO - ... 4 more
[2021-12-28 13:44:23,129] {spark_submit.py:514} INFO - Caused by: java.net.UnknownHostException: spark
[2021-12-28 13:44:23,130] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
[2021-12-28 13:44:23,131] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509)
[2021-12-28 13:44:23,131] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1368)
[2021-12-28 13:44:23,132] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1302)
[2021-12-28 13:44:23,133] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getByName(InetAddress.java:1252)
[2021-12-28 13:44:23,134] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156)
[2021-12-28 13:44:23,135] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153)
[2021-12-28 13:44:23,137] {spark_submit.py:514} INFO - at java.base/java.security.AccessController.doPrivileged(Native Method)
[2021-12-28 13:44:23,138] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153)
[2021-12-28 13:44:23,139] {spark_submit.py:514} INFO - at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41)
[2021-12-28 13:44:23,139] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
[2021-12-28 13:44:23,142] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53)
[2021-12-28 13:44:23,143] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
[2021-12-28 13:44:23,145] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
[2021-12-28 13:44:23,146] {spark_submit.py:514} INFO - at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
[2021-12-28 13:44:23,146] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:206)
[2021-12-28 13:44:23,147] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46)
[2021-12-28 13:44:23,148] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:180)
[2021-12-28 13:44:23,150] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:166)
[2021-12-28 13:44:23,152] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
[2021-12-28 13:44:23,154] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
[2021-12-28 13:44:23,155] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
[2021-12-28 13:44:23,156] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
[2021-12-28 13:44:23,157] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
[2021-12-28 13:44:23,158] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
[2021-12-28 13:44:23,159] {spark_submit.py:514} INFO - at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
[2021-12-28 13:44:23,160] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:1008)
[2021-12-28 13:44:23,161] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:516)
[2021-12-28 13:44:23,162] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
[2021-12-28 13:44:23,164] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
[2021-12-28 13:44:23,171] {spark_submit.py:514} INFO - at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[2021-12-28 13:44:23,173] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
[2021-12-28 13:44:23,174] {spark_submit.py:514} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[2021-12-28 13:44:23,175] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[2021-12-28 13:44:23,176] {spark_submit.py:514} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2021-12-28 13:44:23,177] {spark_submit.py:514} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2021-12-28 13:44:23,177] {spark_submit.py:514} INFO - ... 1 more
[2021-12-28 13:44:43,041] {spark_submit.py:514} INFO - 21/12/28 13:44:43 ERROR StandaloneSchedulerBackend: Application has been killed. Reason: All masters are unresponsive! Giving up.
[2021-12-28 13:44:43,049] {spark_submit.py:514} INFO - 21/12/28 13:44:43 WARN StandaloneSchedulerBackend: Application ID is not initialized yet.
[2021-12-28 13:44:43,074] {spark_submit.py:514} INFO - 21/12/28 13:44:43 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 33961.
[2021-12-28 13:44:43,075] {spark_submit.py:514} INFO - 21/12/28 13:44:43 INFO NettyBlockTransferService: Server created on 0c125a5bba95:33961
[2021-12-28 13:44:43,080] {spark_submit.py:514} INFO - 21/12/28 13:44:43 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2021-12-28 13:44:43,092] {spark_submit.py:514} INFO - 21/12/28 13:44:43 INFO SparkUI: Stopped Spark web UI at http://0c125a5bba95:4044
[2021-12-28 13:44:43,105] {spark_submit.py:514} INFO - 21/12/28 13:44:43 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 0c125a5bba95, 33961, None)
[2021-12-28 13:44:43,111] {spark_submit.py:514} INFO - 21/12/28 13:44:43 INFO StandaloneSchedulerBackend: Shutting down all executors
[2021-12-28 13:44:43,117] {spark_submit.py:514} INFO - 21/12/28 13:44:43 INFO CoarseGrainedSchedulerBackend$DriverEndpoint: Asking each executor to shut down
[2021-12-28 13:44:43,118] {spark_submit.py:514} INFO - 21/12/28 13:44:43 INFO BlockManagerMasterEndpoint: Registering block manager 0c125a5bba95:33961 with 434.4 MiB RAM, BlockManagerId(driver, 0c125a5bba95, 33961, None)
[2021-12-28 13:44:43,120] {spark_submit.py:514} INFO - 21/12/28 13:44:43 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 0c125a5bba95, 33961, None)
[2021-12-28 13:44:43,122] {spark_submit.py:514} INFO - 21/12/28 13:44:43 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 0c125a5bba95, 33961, None)
[2021-12-28 13:44:43,129] {spark_submit.py:514} INFO - 21/12/28 13:44:43 WARN StandaloneAppClient$ClientEndpoint: Drop UnregisterApplication(null) because has not yet connected to master
[2021-12-28 13:44:43,152] {spark_submit.py:514} INFO - 21/12/28 13:44:43 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2021-12-28 13:44:43,177] {spark_submit.py:514} INFO - 21/12/28 13:44:43 INFO MemoryStore: MemoryStore cleared
[2021-12-28 13:44:43,178] {spark_submit.py:514} INFO - 21/12/28 13:44:43 INFO BlockManager: BlockManager stopped
[2021-12-28 13:44:43,188] {spark_submit.py:514} INFO - 21/12/28 13:44:43 INFO BlockManagerMaster: BlockManagerMaster stopped
[2021-12-28 13:44:43,193] {spark_submit.py:514} INFO - 21/12/28 13:44:43 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2021-12-28 13:44:43,213] {spark_submit.py:514} INFO - 21/12/28 13:44:43 INFO SparkContext: Successfully stopped SparkContext
[2021-12-28 13:44:43,357] {spark_submit.py:514} INFO - 21/12/28 13:44:43 ERROR SparkContext: Error initializing SparkContext.
[2021-12-28 13:44:43,358] {spark_submit.py:514} INFO - java.lang.IllegalArgumentException: requirement failed: Can only call getServletHandlers on a running MetricsSystem
[2021-12-28 13:44:43,358] {spark_submit.py:514} INFO - at scala.Predef$.require(Predef.scala:281)
[2021-12-28 13:44:43,360] {spark_submit.py:514} INFO - at org.apache.spark.metrics.MetricsSystem.getServletHandlers(MetricsSystem.scala:89)
[2021-12-28 13:44:43,360] {spark_submit.py:514} INFO - at org.apache.spark.SparkContext.<init>(SparkContext.scala:603)
[2021-12-28 13:44:43,361] {spark_submit.py:514} INFO - at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2021-12-28 13:44:43,362] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2021-12-28 13:44:43,363] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2021-12-28 13:44:43,364] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2021-12-28 13:44:43,364] {spark_submit.py:514} INFO - at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[2021-12-28 13:44:43,365] {spark_submit.py:514} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2021-12-28 13:44:43,366] {spark_submit.py:514} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2021-12-28 13:44:43,367] {spark_submit.py:514} INFO - at py4j.Gateway.invoke(Gateway.java:238)
[2021-12-28 13:44:43,367] {spark_submit.py:514} INFO - at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2021-12-28 13:44:43,368] {spark_submit.py:514} INFO - at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2021-12-28 13:44:43,369] {spark_submit.py:514} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2021-12-28 13:44:43,369] {spark_submit.py:514} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2021-12-28 13:44:43,370] {spark_submit.py:514} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-28 13:44:43,371] {spark_submit.py:514} INFO - 21/12/28 13:44:43 INFO SparkContext: SparkContext already stopped.
[2021-12-28 13:44:43,371] {spark_submit.py:514} INFO - Traceback (most recent call last):
[2021-12-28 13:44:43,372] {spark_submit.py:514} INFO - File "/opt/***/jobs/persist_db.py", line 52, in <module>
[2021-12-28 13:44:43,373] {spark_submit.py:514} INFO - .config("spark.driver.bindAddress", "localhost") \
[2021-12-28 13:44:43,374] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/session.py", line 228, in getOrCreate
[2021-12-28 13:44:43,375] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 392, in getOrCreate
[2021-12-28 13:44:43,376] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 147, in __init__
[2021-12-28 13:44:43,377] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 209, in _do_init
[2021-12-28 13:44:43,377] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 329, in _initialize_context
[2021-12-28 13:44:43,378] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/py4j-0.10.9.2-src.zip/py4j/java_gateway.py", line 1574, in __call__
[2021-12-28 13:44:43,379] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/py4j-0.10.9.2-src.zip/py4j/protocol.py", line 328, in get_return_value
[2021-12-28 13:44:43,379] {spark_submit.py:514} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling None.org.apache.spark.api.java.JavaSparkContext.
[2021-12-28 13:44:43,380] {spark_submit.py:514} INFO - : java.lang.IllegalArgumentException: requirement failed: Can only call getServletHandlers on a running MetricsSystem
[2021-12-28 13:44:43,381] {spark_submit.py:514} INFO - at scala.Predef$.require(Predef.scala:281)
[2021-12-28 13:44:43,382] {spark_submit.py:514} INFO - at org.apache.spark.metrics.MetricsSystem.getServletHandlers(MetricsSystem.scala:89)
[2021-12-28 13:44:43,383] {spark_submit.py:514} INFO - at org.apache.spark.SparkContext.<init>(SparkContext.scala:603)
[2021-12-28 13:44:43,383] {spark_submit.py:514} INFO - at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2021-12-28 13:44:43,384] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2021-12-28 13:44:43,385] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2021-12-28 13:44:43,386] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2021-12-28 13:44:43,386] {spark_submit.py:514} INFO - at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[2021-12-28 13:44:43,387] {spark_submit.py:514} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2021-12-28 13:44:43,388] {spark_submit.py:514} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2021-12-28 13:44:43,389] {spark_submit.py:514} INFO - at py4j.Gateway.invoke(Gateway.java:238)
[2021-12-28 13:44:43,390] {spark_submit.py:514} INFO - at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2021-12-28 13:44:43,390] {spark_submit.py:514} INFO - at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2021-12-28 13:44:43,391] {spark_submit.py:514} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2021-12-28 13:44:43,392] {spark_submit.py:514} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2021-12-28 13:44:43,393] {spark_submit.py:514} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-28 13:44:43,394] {spark_submit.py:514} INFO - 
[2021-12-28 13:44:43,455] {spark_submit.py:514} INFO - 21/12/28 13:44:43 INFO ShutdownHookManager: Shutdown hook called
[2021-12-28 13:44:43,457] {spark_submit.py:514} INFO - 21/12/28 13:44:43 INFO ShutdownHookManager: Deleting directory /tmp/spark-9fdc9b25-f678-4d1c-809f-78f980db8b95
[2021-12-28 13:44:43,462] {spark_submit.py:514} INFO - 21/12/28 13:44:43 INFO ShutdownHookManager: Deleting directory /tmp/spark-c238815d-f227-4301-82f3-10898acbc271
[2021-12-28 13:44:43,576] {taskinstance.py:1703} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 179, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 446, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark:7077 --conf spark.master=spark://spark:7077 --name persist data --verbose /opt/***/jobs/persist_db.py meath. Error code is: 1.
[2021-12-28 13:44:43,586] {taskinstance.py:1280} INFO - Marking task as UP_FOR_RETRY. dag_id=scraping_daft_meath, task_id=persist_data, execution_date=20211227T102500, start_date=20211228T134324, end_date=20211228T134443
[2021-12-28 13:44:43,607] {standard_task_runner.py:91} ERROR - Failed to execute job 5108 for task persist_data
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 179, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 446, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark:7077 --conf spark.master=spark://spark:7077 --name persist data --verbose /opt/***/jobs/persist_db.py meath. Error code is: 1.
[2021-12-28 13:44:43,628] {local_task_job.py:154} INFO - Task exited with return code 1
[2021-12-28 13:44:43,719] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
